"""293 individually authored mnemonic scenes, preserving source part order.

Each row explicitly selects its props and spatial layout. The source lookup only
supplies immutable labels; it never invents a story or chooses a visual fallback.
Specs are kind,x,y,scale[,rotation[,z]] in viewer coordinates. Scene stories
describe invented learning associations, not character-history assertions.
"""
import json
from pathlib import Path


ROWS = [
    ('关心','guard-heart','A doorway and shield shut danger out of a heart. Keeping someone’s feelings safe is your picture for caring about them.','door,-.85,0,1.2 heart,.85,0,1.3','second-shield,0,-.9,.6'),
    ('祝','brother-blessing','An older brother brings an offering to the altar and wishes you well. The offering is an invented blessing cue.','second-altar,-.8,-.15,1.1 man,.9,0,1.1','flower,.05,.7,.6'),
    ('层','cloud-floor','A reclining figure rests on one cloud, with another cloud above. Each cloud becomes a separate layer or floor.','second-recliner,-.7,-.45,1.1 cloud,.75,.55,1.2','cloud,-.75,-.75,1.3'),
    ('班','two-kings-shift','A knife separates two crowned rulers into different work shifts. Remember a class or shift as its own organized group.','second-crown,-1.3,.1,.8 knife,0,0,.9 second-crown,1.3,.1,.8','clock,0,-.75,.65'),
    ('坏','broken-earth','A red no-sign stands above cracked earth: the ground is no longer sound. Bad or broken is the warning.','earth,-.75,-.4,1.2 second-cross,.8,.35,1.3','second-broken,0,-.05,.9'),
    ('一边','one-side-action','One bar marks the edge of a desk. Picture reading on that side while drinking tea: one action alongside another.','bar,-.9,.4,1 second-strip,.85,-.25,1.2','book,-.75,-.5,.7 cup,.8,.5,.7'),
    ('鞋','leather-earth-shoe','A leather patch lies above two stacked earth blocks. Imagine shaping this raised sole into a sturdy leather shoe.','second-leather,-.8,.15,1.2 earth,.8,-.35,1.1','earth,.8,-.6,.85 shoe,0,.8,.9'),
    ('习惯','practice-habit','A practice wing circles a repeating loop. The same flight every day becomes a habit, not a new decision.','feather,-.8,0,1.3 second-cycle,.8,0,1.3','calendar,0,-.8,.7'),
    ('变化','changing-shape','A change arrow leads to a transformed puzzle piece. Imagine a square changing its shape to fit a new partner.','second-cycle,-.85,0,1.2 second-puzzle,.85,0,1.2','arrow,0,-.75,.65'),
    ('周末','week-end','An around-the-week loop reaches the tip of a calendar strip. At that end, close your work book for the weekend.','second-cycle,-.85,.15,1.2 second-strip,.85,-.1,1.1','calendar,.85,.7,.65 book,-.85,-.65,.6'),
    ('忘记','lost-memory','A memory note slips into the discard bin while a second note stays in the book. Remember the missing note: forget.','second-bin,-.8,-.25,1.2 book,.85,.0,1.25','paper,-.8,.7,.55'),
    ('打算','hammer-calculation','A hammer pauses beside a counting board. Calculate before striking: the intended action is still a plan.','second-hammer,-.85,.1,1.2 count-5,.85,0,1.2','paper,0,-.75,.65'),
    ('极','tree-limit','A tree grows beside a reaching hand at its very top. The reach has gone to an extreme height.','tree,-.65,-.2,1.5 hand,.9,.9,.8','arrow,.7,-.1,.6,1.5708'),
    ('举行','raised-event','Raised hands lift a festival flag while walking guests arrive. Raising and gathering make an event happen.','hand,-.8,.4,1.15 walker,.85,-.15,1.1','flag,0,.85,.85 second-platform,0,-.8,1.2'),
    ('水平','water-level','A flat bar floats at the water’s surface. Use that shared level as your picture for a standard.','water,0,-.55,1.8 bar,0,-.77,1.9','second-ruler,0,.7,1.1'),
    ('借','old-day-loan','A person borrows an old-day book from yesterday’s calendar shelf. A return arrow promises the loan will go back.','person,-.85,-.05,1.15 calendar,.85,.15,1.1','book,0,-.6,.7 arrow,.85,-.75,.55,3.14159'),
    ('东','seven-small-east','Seven tiny beads sit beneath a small rising sun on the right. This deliberately odd sunrise is your cue for east.','count-7,-.85,-.35,1 sun,.85,.5,.7','arrow,.9,-.65,.65'),
    ('害怕','harm-fear','A warning triangle announces harm while a frightened face hides behind a shield. Seeing danger brings fear.','second-alarm,-.85,.2,1.2 face,.85,.15,1.1','second-shield,.85,-.7,.7'),
    ('照顾','shine-care','A lamp shines toward someone resting in bed. Looking after the sleeper carefully makes the light a care cue.','lamp,-.85,.25,1.2 second-recliner,.8,-.3,1.2','bed,.8,-.75,.85'),
    ('文化','writing-transform','Writing on a scroll passes through a change arrow into an art display. Shared writing and transformed traditions suggest culture.','paper,-.85,.2,1.2 second-cycle,.85,.15,1.15','brush,0,-.75,.8 flower,.85,.85,.6'),
    ('奇怪','odd-pair','A question bubble hovers over a mismatched puzzle and an upside-down cup. Two peculiar objects make the whole scene strange.','question,-.85,.25,1.15 second-puzzle,.85,0,1.1','cup,0,-.65,.7,3.14159'),
    ('南','horns-south','Ten beads gather beside an open frame, two horns and a dry broom. Imagine this odd marker pointing south.','count-10,-1.2,.65,.65 frame,1,.5,.75 horns,-1.1,-.65,.7 broom,1,-.6,.65','arrow,0,-.3,.55,-1.5708'),
    ('提高','lifting-high','A lifting hand pushes an arrow toward a tall tower. Move the arrow upward to improve or raise the level.','hand,-.85,-.15,1.2 tower,.85,.15,1.1','arrow,0,.25,.9,1.5708'),
    ('满意','full-idea','A completely full bowl sits beneath a glowing idea-lamp. Nothing more is needed: the imagined diner is satisfied.','bowl,-.85,-.35,1.45 lamp,.85,.25,1.2','rice,-.85,-.15,1.3 second-check,0,.85,.7'),
    ('经理','thread-manager','Threads run from a manager’s desk to a reason checklist. The manager keeps the work connected and the decisions orderly.','silk,-.85,.15,1.1 second-checklist,.85,.15,1.25','person,0,-.45,.8'),
    ('兴趣','excited-interest','An excitement star draws a curious eye toward a favorite book. Follow that attraction to remember interest.','star,-.85,.3,1.25 eye,.85,.3,1.25','book,0,-.65,.9'),
    ('帮忙','helping-busy','One hand helps another carry a busy pile of boxes. Lending a hand makes the workload lighter.','hand,-.85,.15,1.25 second-burden,.85,-.1,1.1','box,0,.6,.7'),
    ('成绩','achievement-result','A success trophy stands beside an achievement checklist. The checked results become your grades or performance record.','second-trophy,-.85,.15,1.2 second-checklist,.85,.15,1.2','book,0,-.7,.7'),
    ('聪明','clever-bright','A clever puzzle solver works beneath a bright sun. Fit the pieces and let the light make the answer clear.','second-puzzle,-.85,.0,1.25 sun,.85,.5,1.1','person,0,-.65,.65'),
    ('多么','many-exclamation','A heap of many beads spills beside a questioning curl. Imagine exclaiming “how many!” rather than quietly counting them.','count-9,-.85,0,1.15 hook,.85,.15,1.2','speech,0,.85,.7'),
    ('一会儿','brief-child-time','One bar gives a capable child a tiny turn with the clock. The little turn lasts only a little while.','bar,-1.25,.0,.7 second-check,0,.5,.7 leg,1.25,-.15,.85','clock,0,-.6,.85'),
    ('骑','strange-rider','An unusual question bubble floats above a horse with a saddle-like seat. Picture climbing onto the horse to ride.','horse,-.55,-.4,1.5 question,.9,.6,.9','person,-.5,.7,.65'),
    ('搬','hand-sorting-move','A hand lifts a box from a sorted group to a new shelf. Carry it across to remember moving objects.','hand,-.85,.25,1.1 shelf,.85,-.05,1.2','box,0,-.35,.8 arrow,0,.75,.7'),
    ('同事','same-task','Matching workers share one task board at the same desk. Their common assignment makes them colleagues.','second-puzzle,-.85,.15,1.1 second-checklist,.85,.15,1.1','person,-.55,-.75,.55 person,.55,-.75,.55'),
    ('舒服','relaxed-clothes','A relaxing reclining figure rests beside soft clothing on a sofa. Imagine how comfortable the outfit and seat feel.','second-recliner,-.8,.0,1.1 shirt,.85,.15,1.2','sofa,0,-.85,1.25'),
    ('体育','nurtured-body','A person trains the body while a nest-like basket holds sports equipment. Nurture strength through physical education.','person,-.8,-.05,1.2 second-nest,.85,-.25,1.1','ball,.85,.5,.7'),
    ('角','little-money-unit','A curled hook scoops one useful coin from ten. Set aside that single tenth to remember one jiao.','hook,-.8,.25,1.1 coins,.85,-.2,1.1','count-10,0,-.85,.9'),
    ('干净','dry-clean','A dry broom sweeps toward a clean white cloth. Finish sweeping and leave no dirt: dry and clean together.','broom,-.8,.05,1.2 towel,.8,.0,1.3','second-check,0,.85,.7'),
    ('安静','peaceful-quiet','A peaceful home stands beside a mouth covered by a soft cloth. Let the whole house settle into quiet.','house,-.8,.05,1.1 mouth,.8,.1,1.1','towel,.8,.1,.65,0,.2'),
    ('作业','made-homework','A making hand works through a businesslike task sheet beside a school book. The assignment becomes homework.','hand,-.8,.2,1.1 second-checklist,.85,.15,1.25','book,0,-.75,.8'),
    ('新鲜','new-fresh','A new delivery box stands beside a fresh fish. Imagine opening this just-delivered catch and its clean smell: fresh.','box,-.85,-.1,1.1 fish,.85,.15,1.2','second-check,0,.85,.65'),
    ('难过','sad-obstacle','A difficult barrier blocks a passing arrow. A heart droops below the stopped passage: remember feeling sad.','second-fence,-.8,.15,1.1 arrow,.85,.15,1.1','heart,0,-.75,.8'),
    ('客人','guest-person','A guest’s suitcase waits beside a person at an open door. Welcome the visitor rather than treating them as a resident.','suitcase,-.85,-.1,1.1 person,.85,-.05,1.1','door,0,.55,.85'),
    ('碗','stone-curve-bowl','A stone rests beside a curved crescent, with a bowl below. Imagine curving the stone into a rounded bowl.','second-broken,-.85,.2,1 moon,.85,.2,1','bowl,0,-.7,1.25'),
    ('刷','reclining-cloth-brush','A reclining figure cleans a cloth with a blade-shaped brush. The peculiar cleaning scene binds the three parts to brushing.','second-recliner,-1.2,-.3,.9 towel,0,.15,.9 knife,1.2,.1,.85','brush,0,-.8,.7'),
    ('练习','trained-wing','Training weights sit beside a practice wing and a repeat loop. Return to the same exercise until practice improves it.','second-weight,-.85,-.25,1 feather,.85,.25,1.1','second-cycle,0,.8,.7'),
    ('邻居','neighbor-home','Two neighboring homes face a shared fence. Picture the nearby resident stepping across to say hello.','house,-.85,.1,1.1 house,.85,.1,1.1','second-fence,0,-.85,.7'),
    ('校长','long-school-leader','A school book stands beside a long pointer. The principal uses the pointer to guide the whole school.','book,-.8,.0,1.35 pole,.8,.0,1.35','second-crown,0,.9,.75'),
    ('节日','sun-festival-joint','A tied joint holds a festival flag under the sun. Mark this special day as a holiday on the calendar.','second-knot,-.85,.0,1.2 sun,.85,.55,1.15','flag,0,-.2,.9 calendar,0,-.9,.55'),
    ('叔叔','uncle-pair','Two matching adult figures greet a child. Repeat the uncle cue twice to remember the friendly kinship word shūshu.','man,-.85,.0,1.1 man,.85,.0,1.1','child,0,-.75,.55'),
    ('街道','street-way','A row of houses borders a road that continues past them. Follow the street’s open way between the buildings.','house,-.85,.25,1.1 road,.85,-.45,1.4','house,.85,.6,.8'),
    ('感冒','feeling-cold','A face feels chilly while a warning flag dares to wave above it. The sneeze-like breath recalls catching a cold.','face,-.8,.15,1.15 flag,.85,.15,1.1','second-breath,0,-.6,.8 snow,0,.8,.65'),
    ('刻','boar-quarter','A little boar sits beside a knife that cuts a clock’s imagined hour into four pieces. One piece is a quarter-hour.','pig,-.85,-.15,1.05 knife,.85,.15,1.1','clock,0,.8,.85 count-4,0,-.8,.7'),
    ('锻炼','forge-refine','A forging hammer meets a refining flame. Treat your body like metal worked patiently stronger through exercise and training.','second-hammer,-.85,.15,1.15 flame,.85,.15,1.15','second-weight,0,-.75,.75'),
    ('夏','self-summer-return','One bar shades a self-mirror above returning footsteps. Picture walking back from your summer holiday in the heat.','bar,-1.2,.7,.7 mirror,0,.0,1 footprints,1.2,-.6,.9','sun,-1.3,-.35,.75'),
    ('刮','wind-tongue-blade','A tongue-shaped wind gust meets a knife’s sharp edge. Imagine the wind blowing so sharply it almost scrapes.','tongue,-.8,.2,1.1 knife,.85,.2,1.15','second-breath,0,-.65,1.1'),
    ('阿姨','auntie-call','An affectionate speech bubble floats beside an aunt carrying a little gift. Say āyí as you greet her warmly.','speech,-.85,.35,1.1 woman,.85,-.05,1.1','bag,0,-.65,.65'),
    ('超市','beyond-market','A beyond-the-barrier arrow reaches shelves full of goods. This bigger market is a supermarket, not just one stall.','arrow,-.85,.15,1.1 shelf,.85,.05,1.2','apple,.6,.4,.45 milk,1.1,-.1,.45 second-fence,-.8,-.55,.65'),
    ('着急','watching-urgency','A continuing eye watches an urgent warning beside a clock. Waiting for the hands to move makes you anxious and hurried.','eye,-.85,.2,1.2 second-alarm,.85,.2,1.1','clock,0,-.7,.9'),
    ('空调','empty-adjustment','An empty frame receives an adjustable cool-air fan. Imagine adjusting its airflow until the room is comfortable.','frame,-.85,.1,1.1 gear,.85,.1,1.1','second-breath,0,-.65,.9 snow,.9,.75,.5'),
    ('一共','one-total','One bar gathers several beads into a single bracket. Count the gathered group altogether, not separately.','bar,-.85,.25,1 second-brackets,.85,.1,1.3','count-6,.85,.1,.7'),
    ('爱好','lovely-hobby','A loving heart points toward a good, checked art project. Choose the activity you enjoy as your hobby.','heart,-.85,.15,1.15 second-check,.85,.15,1.15','brush,0,-.65,.8'),
    ('有名','has-name','A receiving hand holds a name tag above a crowd. Everyone knows that name: the person is famous.','second-cradle,-.85,-.15,1.1 second-tag,.85,.2,1.2','person,-.4,.8,.45 person,.4,.8,.45'),
    ('护照','guarding-passport','A protective shield faces a light shining onto a passport book. The guarded document lets its owner travel.','second-shield,-.85,.15,1.15 lamp,.85,.3,1.1','book,0,-.7,.9 plane,0,.9,.65'),
    ('年级','year-level','A year calendar stands beside ascending steps. Each new school year moves a student up another grade level.','calendar,-.85,.15,1.2 second-steps,.85,-.2,1.2','child,1,.65,.5'),
    ('普通话','shared-language','A general crowd shares an open passage and speech bubble. Imagine Mandarin connecting speakers through this common language channel.','person,-1.25,-.2,.9 gate,0,.05,.85 speech,1.25,.3,.9','arrow,0,-.8,.7'),
    ('对','hand-thumb-correct','A hand checks the position of a thumb-sized marker. When they line up, the green check says correct.','hand,-.85,.15,1.2 hand,.85,.15,.75','second-check,0,-.7,.85'),
    ('过','road-experience','A thumb-sized souvenir sits on a traveled road. Keep it as a reminder that you have experienced this journey before.','road,-.7,-.35,1.35 hand,.85,.3,.75','footprints,-.65,-.45,1'),
    ('而','beard-connector','A beard hangs between two linked blocks. Treat its strands as a bridge joining clauses: and, or whereas.','second-beard,0,.0,1.55','second-plus,-1.2,-.2,.65 second-chain,1.2,-.2,.65'),
    ('等','bamboo-temple-wait','Bamboo stands outside a temple-like house while a clock slowly turns. Sit by the bamboo and wait.','pole,-.85,.0,1.3 house,.85,.0,1.1','clock,0,-.75,.75'),
    ('与','give-with','Two cupped hands give and receive the same gift. Keep both together to remember and or with.','second-cradle,0,-.2,1.65','box,0,.65,.7 second-plus,1.15,.55,.6'),
    ('当','sparks-broom-time','Little sparks hover over a broom beside a clock. Imagine that when the sparks appear, the broom acts as your signal.','star,-.8,.45,1 broom,.85,-.15,1.2','clock,0,-.75,.65'),
    ('之','linking-path','A winding path links a person to their book. Treat that path as a literary ownership connection, not a spoken object.','road,0,-.3,1.7','person,-1.2,.45,.7 book,1.2,.45,.7 second-chain,0,.6,.6'),
    ('以','means-tool','A useful tool sends a motion arrow toward a finished box. Focus on the tool as the means used to achieve the result.','second-hammer,0,.0,1.5','arrow,-1.15,.5,.7 box,1.15,-.4,.75'),
    ('起来','rise-come','An upward arrow rises beside footsteps coming toward a chair. Imagine standing up and coming forward from your seat.','arrow,-.85,.15,1.2,1.5708 footprints,.85,-.35,1.2','chair,.75,.55,.85'),
    ('死','bone-ending','A broken bone-like fragment lies beside a spoon, with an extinguished lamp behind. The still scene remembers life ending.','second-broken,-.85,-.2,1.15 spoon,.85,-.15,1.15','lamp,0,.75,.65 second-cross,0,.75,.55,0,.25'),
    ('却','unexpected-kneeler','A departing arrow unexpectedly meets a kneeling figure. The sudden interruption marks yet or but, contrary to expectation.','arrow,-.85,.15,1.1 second-kneeler,.85,-.1,1.15','second-cross,0,.75,.65'),
    ('生活','growing-life','A growing sprout thrives beside a lively person. Daily water and care make the pair a picture of living life.','sprout,-.85,.0,1.3 person,.85,.0,1.15','water,0,-.8,.9'),
    ('发生','send-growth-happen','A sending arrow releases a seed toward a growing sprout. The new shoot marks something happening, rather than merely being planned.','arrow,-.85,.15,1.1 sprout,.85,.1,1.3','bean,0,-.65,.8'),
    ('不过','not-passing-however','A no-sign interrupts a passing arrow beside a fence. Imagine the interruption as a turn in your sentence: however.','second-cross,-.85,.25,1.1 arrow,.85,.1,1.15','second-fence,0,-.55,.75'),
    ('所有','place-has-all','An open room contains a full receiving basket. Enclose every item there to remember all that the place has.','frame,-.85,.1,1.2 second-cradle,.85,-.2,1.1','count-6,.85,.3,.8 second-brackets,0,-.75,.75'),
    ('情况','feeling-situation','An emotion heart rests beside a scene map with a marker. Read both feelings and surroundings to understand the situation.','heart,-.85,.15,1.1 map,.85,.15,1.2','second-target,.85,.45,.45,0,.25'),
    ('最后','last-at-back','A bead group marks the main journey while trailing footprints approach a final target. Save this end stop for last: finally.','count-5,-.85,.2,1.1 footprints,.85,-.35,1.1','road,0,-.8,1.5 second-target,1.3,.45,.6'),
    ('成为','success-becomes','A success trophy passes through a transformation arrow into a new role’s crown. Imagine becoming what you worked toward.','second-trophy,-.85,.0,1.2 second-crown,.85,.25,1.15','arrow,0,-.75,.7'),
    ('行','steps-work','Left footsteps and a right footprint align into one usable path. The green check means this way works: okay.','footprints,-.85,-.25,1.1 foot,.85,-.15,1.1','second-check,0,.75,.9'),
    ('感觉','feel-notice','A hand feels a warm cup while an eye notices the sensation. Feeling and noticing meet in your awareness.','hand,-.85,.1,1.1 eye,.85,.25,1.15','cup,0,-.7,.9 steam,0,.8,.65'),
    ('继续','thread-continues','An unbroken thread joins a chain above payment coins, an invented cue for continuing a sale. Keep following the strand: continue.','silk,-.85,.2,1.1 second-chain,.85,.2,1.1','coins,.85,-.6,.7 arrow,0,.85,.65'),
    ('场','ground-event-unit','An earth arena sits inside a do-not-enter fence. Imagine counting one scheduled event held in that enclosed place.','field,-.85,-.3,1.3 second-fence,.85,.15,1.1','flag,0,.7,.75'),
    ('进行','entering-progress','An entering arrow leads walking feet through a gate. The motion already underway recalls carrying out an activity.','arrow,-.85,.2,1.1 walker,.85,-.1,1.1','gate,0,.25,1 footprints,0,-.75,.8'),
    ('通过','pass-through','An open gate admits a passing arrow from one side to the other. Nothing blocks the passage: pass through.','gate,-.85,.05,1.15 arrow,.85,.05,1.2','footprints,0,-.75,.85'),
    ('无','one-absent','One bar lies above a bent figure searching an empty plate. There is nothing there: without or no.','bar,-.85,.4,1 second-kneeler,.85,-.25,1.1','plate,-.7,-.7,1'),
    ('一切','one-cut-everything','One long bar is cut into several pieces, all gathered inside brackets. Every piece counts: everything, without leaving anything out.','bar,-.85,.25,1 knife,.85,.25,1.1','count-5,0,-.65,.9 second-brackets,0,-.65,1.2'),
    ('由','field-source','An arrow starts from one marked field and points outward. Use the field as the source: from or by.','field,0,-.25,1.8','arrow,0,.65,1.1 second-target,-1.2,-.1,.6'),
    ('任何','any-duty-gate','A duty bearer can choose any open question gate. No gate is singled out: any choice satisfies the idea.','second-burden,-.85,-.1,1.1 question,.85,.45,1.05','gate,.85,-.4,.8'),
    ('安全','peaceful-whole','A peaceful home stands beside a whole protective shield. Imagine shielding the entire home, keeping everything intact and safe.','house,-.85,.05,1.1 second-shield,.85,.05,1.2','second-check,0,.85,.65'),
    ('结果','knot-fruit-result','A tied knot holds a ripe fruit at the end of a growing branch. The fruit is the result you finally obtain.','second-knot,-.85,.1,1.2 fruit,.85,.1,1.3','sprout,0,-.75,.8'),
    ('完全','finished-whole','A completed checklist faces a whole, unbroken ring. Every requirement is filled and nothing is missing: completely.','second-checklist,-.85,.1,1.2 second-jade,.85,.1,1.2','second-check,0,-.75,.65'),
    ('发','send-away','An envelope sits at the start of a forward arrow. Imagine releasing it toward its recipient to remember send.','arrow,0,.0,1.8','envelope,-1.1,-.65,.8 second-cradle,1.1,-.6,.75'),
    ('计划','counted-plan','A counting board sits beside pencil marks on a route map. Work out the steps before starting: make a plan.','count-5,-.85,.15,1 pencil,.85,.15,1.2','map,0,-.75,.9'),
    ('可是','permission-but','A permission check faces an is-stamp, yet a fence interrupts their connection. Imagine saying yes to one fact, but adding another.','second-check,-.85,.15,1.1 stamp,.85,.15,1.1','second-fence,0,-.65,.8'),
    ('连','road-even-vehicle','A vehicle joins a road already crowded with travelers. Imagine saying even the vehicle is included in the group.','road,-.7,-.35,1.3 car,.85,.15,1.15','second-brackets,0,.65,.9'),
    ('呀','tooth-exclamation','A tooth pops beside an open mouth and a bright speech bubble. Hear a spontaneous yā or ya at the surprise.','mouth,-.85,.1,1.2 tooth,.85,.1,1.2','speech,0,.85,.75'),
    ('原因','source-because','A source spring feeds a cause marker and then a growing plant. Follow the flow backward to its reason or cause.','second-spring,-.85,.1,1.2 second-target,.85,.1,1.1','sprout,.85,-.75,.7 arrow,0,.85,.7'),
    ('消息','vanishing-breath-message','A vanishing curl of breath leaves an envelope behind. Imagine spoken news settling into a message you can keep.','second-cycle,-.85,.1,1.1 second-breath,.85,.1,1.15','envelope,0,-.75,.95'),
    ('只要','only-condition','Only one key opens a wanted gift box. As long as you have that key, the condition is met.','key,-.85,.15,1.15 heart,.85,.15,1.1','box,.85,-.7,.85 second-check,0,.85,.65'),
    ('干','one-ten-work','One bar stands beside ten counted beads and a hammer. Imagine checking off ten small jobs: do the work piece by piece.','bar,-.85,.35,1 count-10,.85,-.1,1.1','second-hammer,0,-.7,.8'),
    ('接受','receiving-acceptance','A reaching hand offers a gift into cupped receiving hands. Keeping the gift makes the action acceptance rather than refusal.','hand,-.85,.15,1.2 second-cradle,.85,-.15,1.2','box,0,.65,.7'),
    ('其中','that-middle','A pointing hand singles out the middle bead in a group. That marked bead is one among them.','hand,-.85,.25,1.1 second-target,.85,.15,1.1','count-5,.85,-.6,1'),
    ('成功','success-work','A success trophy stands above an achievement hammer. The finished work has earned its reward: success.','second-trophy,-.85,.1,1.2 second-hammer,.85,.1,1.2','second-check,0,-.75,.7'),
    ('甚至','extreme-arrival','An extreme pile of weights waits beyond an arrival arrow. Imagine the claim reaching even that surprising limit.','second-weight,-.85,-.15,1.35 arrow,.85,.2,1.15','second-alarm,0,.85,.65'),
    ('肯定','willing-fixed','A willing hand presses a check firmly onto a fixed plinth. The answer stays there without wobbling: certain.','hand,-.85,.25,1.1 second-platform,.85,-.4,1.2','second-check,.85,.4,.9'),
    ('当时','positioned-time','A position marker sits exactly on one calendar square beside a clock. Recall that precise moment: at that time.','second-target,-.85,.15,1.15 clock,.85,.15,1.2','calendar,0,-.75,.8'),
    ('调查','adjusted-check','An adjusting gear turns beside an eye checking a document. Tune the search and examine the evidence to investigate.','gear,-.85,.1,1.2 eye,.85,.2,1.2','paper,0,-.75,.8'),
    ('部分','divided-department','A department shelf holds only a divided portion of the whole pile. Focus on its allotted piece: a part.','shelf,-.85,.05,1.2 knife,.85,.15,1.1','count-4,0,-.75,.85'),
    ('能力','able-strength','A capability meter rises beside a strength weight. Together they picture what someone is able to do.','second-meter,-.85,.2,1.1 second-weight,.85,-.05,1.3','second-check,0,.85,.65'),
    ('保护','double-protection','A shield covers a home while a guarding person stands nearby. Both keep the vulnerable place protected.','second-shield,-.85,.1,1.2 person,.85,-.05,1.1','house,0,-.75,.75'),
    ('真正','true-correct','A proof checklist faces a green correctness check. Matching evidence and answer make the claim real and genuine.','second-checklist,-.85,.15,1.2 second-check,.85,.15,1.3','second-jade,0,-.7,.7'),
    ('支持','support-hold','A supporting post stands beside a holding hand under a shelf. Keep the load steady to remember support.','pole,-.85,-.05,1.2 hand,.85,.1,1.1','bar,0,.9,1.55'),
    ('掉','hand-high-drop','A hand releases a bead from a tall tower. The downward arrow traces its fall: drop.','hand,-.85,.6,1.1 tower,.85,-.05,1.1','arrow,-.8,-.45,.75,-1.5708 ball,0,-.85,.5'),
    ('改变','changing-self-shape','A self-mirror faces a change loop and a newly fitted puzzle. Imagine altering yourself and the shape of your situation.','mirror,-.85,.15,1.2 second-cycle,.85,.15,1.2','second-puzzle,0,-.75,.75'),
    ('方法','square-method','A square frame holds a sequence of tools beside a checklist. Follow the arranged method for solving the task.','frame,-.85,.1,1.15 second-checklist,.85,.1,1.2','second-hammer,0,-.75,.75'),
    ('保证','shielded-proof','A protective shield faces a signed proof sheet. Imagine the promise backed by both protection and evidence: a guarantee.','second-shield,-.85,.1,1.2 second-checklist,.85,.1,1.2','stamp,0,-.75,.7'),
    ('直接','straight-receive','A straight arrow sends a gift directly into waiting hands. No detour or extra stop interrupts the delivery.','arrow,-.85,.15,1.2 second-cradle,.85,-.05,1.2','box,0,.65,.65'),
    ('组织','group-weaving','Grouped threads weave into an orderly net. Interlacing many strands pictures organizing separate people into one connected structure.','silk,-.85,.15,1.1 net,.85,.15,1.1','second-chain,0,-.75,.8'),
    ('永远','forever-far','An endless loop sits beside a road stretching toward the far horizon. Keep following it to remember forever.','second-cycle,-.85,.15,1.2 road,.85,-.25,1.25','arrow,.85,.55,.85'),
    ('也许','bench-permission-maybe','An also-bench holds a permission check and a question bubble. Permission is possible, but the question keeps it uncertain: perhaps.','chair,-.85,-.1,1.2 second-check,.85,.15,1.1','question,0,.85,.85'),
    ('方面','square-face-aspect','A square frame isolates one face of a box. Look at that single side to remember an aspect.','frame,-.85,.1,1.15 face,.85,.1,1.1','box,0,-.75,.8'),
    ('活动','alive-moving','A lively person follows a movement arrow toward a ball. Living energy put into motion becomes an activity.','person,-.85,-.1,1.15 arrow,.85,.15,1.1','ball,0,-.75,.85'),
    ('考虑','exam-worry-consider','An exam book faces a worried question bubble. Pause between the choices and weigh them before deciding: consider.','book,-.85,.05,1.25 question,.85,.3,1.1','scale,0,-.75,.85'),
    ('份','person-portion','A person receives one divided slice of bread. One allotted share or copy is their portion.','person,-.85,-.05,1.15 knife,.85,.15,1.1','bread,0,-.75,.9'),
    ('提供','lift-supply','A lifting hand presents a supply basket of food. Bring needed things within reach to remember provide.','hand,-.85,.2,1.1 basket,.85,-.3,1.3','apple,.85,.45,.65'),
    ('指','hand-treat-point','A hand points straight toward a delicious sweet. Follow the finger to the treat: point or finger.','hand,-.85,.15,1.25 candy,.85,.15,1.3','arrow,0,-.75,.65'),
    ('精神','essence-spirit','An essence-like bright star floats beside a spirit lamp above a person. Picture their inner energy and mental alertness.','star,-.85,.25,1.15 lamp,.85,.25,1.15','person,0,-.75,.65'),
    ('使用','acting-use','An action-guiding hand reaches for a useful hammer. Put the tool into action rather than leaving it on display: use.','hand,-.85,.2,1.2 second-hammer,.85,.2,1.2','box,0,-.75,.8'),
    ('代表','replacement-display','A replacement figure stands on a display stage before a group. One person speaks for the others as their representative.','person,-.85,-.05,1.15 second-platform,.85,-.25,1.2','speech,.85,.65,.85'),
    ('任务','bearer-duty','A burden-bearing worker receives a duty checklist. The carried load and assigned steps define the task.','second-burden,-.85,-.05,1.15 second-checklist,.85,.1,1.2','second-check,0,-.75,.65'),
    ('联系','ears-tie-contact','Two listening ears are linked by a tied cord. Imagine their owners keeping in contact through that connection.','ear,-.85,.15,1.2 second-knot,.85,.15,1.2','ear,0,-.75,.65 phone,0,.85,.65'),
    ('因此','cause-this-therefore','A cause marker points to this marked spot where a plant grows. Follow cause to consequence: therefore.','second-target,-.85,.15,1.1 second-target,.85,.15,1.1','arrow,0,-.65,.85 sprout,.85,.85,.6'),
    ('台','cocoon-mouth-machine','A private cocoon stands beside a mouth-shaped opening, a platform and a gear. Imagine counting one machine on this stand.','coil,-.85,.2,1.1 mouth,.85,.2,1.1','second-platform,0,-.75,1.25 gear,0,.85,.65'),
    ('算','bamboo-tool-count','Bamboo counting rods stand beside a calculating tool of beads. Move the beads along the rods to calculate.','pole,-.85,.05,1.2 count-6,.85,.05,1.2','second-ruler,0,-.75,.85'),
    ('获得','caught-received','A net catches a prize and waiting hands receive it. The captured gift is now obtained.','net,-.85,.1,1.1 second-cradle,.85,-.15,1.2','second-trophy,0,.65,.75'),
    ('生命','growth-life-order','A sprout grows beside a protective life-order shield. Imagine the order keeping living growth safe: life itself.','sprout,-.85,.0,1.3 second-shield,.85,.1,1.2','heart,0,.85,.65'),
    ('留','gate-field-stay','A rabbit-hour gate opens onto a field, but a suitcase remains behind. Leave it there and stay rather than depart.','gate,-.85,.05,1.1 field,.85,-.25,1.2','suitcase,0,-.75,.85'),
    ('交','six-crossed-handover','Six coins lie beside crossed ribbons tying a parcel. Hand the parcel over with payment to remember hand in or pay.','count-6,-.85,.15,1 second-ribbons,.85,.15,1','envelope,.85,.15,1,0,-.13 second-cradle,0,-.75,.8'),
    ('全部','whole-departments','A whole unbroken ring stands beside a department shelf. Imagine gathering every shelf section into one complete collection: all, entire.','second-jade,-.85,.1,1.2 shelf,.85,.1,1.2','count-5,.85,-.35,.65 second-brackets,0,.85,.8'),
    ('刚刚','two-just-now','Two matching clocks stand beside a freshly received envelope. Repeat the tiny moment twice: it arrived just now.','clock,-.85,.1,1.2 clock,.85,.1,1.2','envelope,0,-.75,.8'),
    ('正常','correct-usual','A green check marks the usual calendar routine. Everything follows the expected pattern: normal.','second-check,-.85,.15,1.2 calendar,.85,.15,1.2','second-cycle,0,-.75,.75'),
    ('另外','another-outside','Another box waits outside an enclosing frame. Add this extra one to remember in addition or another.','box,-.85,.1,1.1 frame,.85,.1,1.2','box,1.65,-.75,.5 second-plus,0,.85,.65'),
    ('挺','hand-court-degree','A hand gestures toward a royal-court crown beside a partly filled meter. Judge the degree: quite impressive, rather high.','hand,-.85,.15,1.15 second-crown,.85,.3,1.15','second-meter,0,-.75,.95'),
    ('好像','good-resemblance','A good checked portrait faces its mirror image. They look alike, but the reflection only seems to be another person.','second-check,-.85,.15,1.1 mirror,.85,.15,1.2','face,0,-.75,.85'),
    ('到底','arrival-bottom','An arrival arrow points all the way to the bottom of a deep shelf. Get to the underlying answer: really, after all.','arrow,-.85,.2,1.1,-1.5708 shelf,.85,.1,1.2','second-target,.85,-.6,.6'),
    ('感谢','felt-thanks','A feeling heart receives a thank-you envelope and flowers. The warm exchange remembers gratitude rather than just polite words.','heart,-.85,.15,1.2 envelope,.85,.15,1.2','flower,0,-.65,.8'),
    ('坚持','firm-hold','A firm lock sits beside a hand still gripping its key. Keep holding through difficulty to remember persistence.','lock,-.85,.1,1.2 hand,.85,.1,1.2','key,0,-.75,.85'),
    ('座','sheltered-seat-unit','A shelter roof stands beside a seated figure and a model mountain. Imagine one seated building or mountain as a counted unit.','roof,-.85,.4,1.1 sitter,.85,-.3,1.05','mountain,0,-.85,.75'),
    ('技术','skill-technique','A skilled hand guides a precise tool into a gear. The controlled method links practical skill with technology.','hand,-.85,.15,1.15 gear,.85,.15,1.2','second-ruler,0,-.75,.85'),
    ('往','toward-marker','A broad arrow points toward a marked gate. Follow its direction rather than its starting point: toward.','arrow,0,.1,1.8','gate,1.2,-.55,.8 footprints,-1.2,-.65,.8'),
    ('严重','strict-heavy','A strict warning triangle rests above a heavy weight. Picture a problem with real weight: serious or severe.','second-alarm,-.85,.25,1.2 second-weight,.85,-.15,1.25','second-fence,0,-.85,.65'),
    ('包括','package-includes','A package stands beside including brackets enclosing several beads. Imagine gathering all these gifts into the package: include.','box,-.85,.1,1.15 second-brackets,.85,.1,1.2','count-4,.85,.1,.65'),
    ('原来','source-arrival','A source spring sits behind incoming footsteps. Trace the arrival back to where it began: originally, or it turns out.','second-spring,-.85,.15,1.2 footprints,.85,-.3,1.15','arrow,0,.85,.75,3.14159'),
    ('光','sparks-stool-light','Little sparks hover over a stool beside a glowing lamp. Imagine light rising from the stool into the room.','star,-.85,.4,1.1 chair,.85,-.25,1.1','lamp,0,.75,.75'),
    ('法律','method-law','A method checklist sits beside a measured rule. Together they form an ordered legal code that everyone must follow.','second-checklist,-.85,.15,1.2 second-ruler,.85,.15,1.2','scale,0,-.8,.75'),
    ('父亲','father-parent','A father figure stands beside a protective parent’s home. Picture the same adult caring for a child: father.','man,-.85,-.05,1.15 house,.85,.05,1.1','child,0,-.75,.65'),
    ('并且','combined-shelf','Two boxes combine on one shelf, with a plus sign above. Add the second fact to the first: and also.','second-plus,-.85,.15,1.15 shelf,.85,.15,1.15','box,.55,-.4,.45 box,1.05,-.4,.45'),
    ('收','cord-tap-collect','A tangled cord gathers scattered parcels while a tapping hand guides them into a basket. Collect and receive the incoming things.','second-knot,-.85,.15,1.2 hand,.85,.15,1.1','basket,0,-.7,1.1'),
    ('社会','community-can','Community homes surround a capability check. Picture people achieving things together through their shared society.','house,-.85,.1,1.1 second-check,.85,.15,1.2','person,0,-.75,.7 second-chain,0,.85,.7'),
    ('证明','proof-bright','A proof sheet sits under bright sunshine. The light lets everyone inspect the evidence and prove the claim.','second-checklist,-.85,.1,1.25 sun,.85,.5,1.1','eye,0,-.75,.75'),
    ('记者','memory-narrator','A memory notebook rests beside a narrator’s speech bubble and a pencil. The reporter records what they hear before telling it.','book,-.85,.1,1.25 speech,.85,.3,1.15','pencil,0,-.75,.8'),
    ('底','shelter-low-base','A shelter roof stands beside a low base and a downward arrow. Trace the imagined shelter down to its base: bottom.','roof,-.85,.4,1.1 second-platform,.85,-.5,1.1','arrow,0,.15,.65,-1.5708'),
    ('确实','certain-real','A certainty check faces a solid jade ring, with matching evidence below. The agreement says indeed: the claim is real.','second-check,-.85,.15,1.2 second-jade,.85,.15,1.2','second-checklist,0,-.75,.75'),
    ('不管','no-matter-pipe','A no-sign stands beside a managing pipe while water keeps flowing. Regardless of control, the action continues.','second-cross,-.85,.25,1.1 second-pipe,.85,.0,1.2','water,0,-.75,1.25 arrow,0,.85,.65'),
    ('受到','received-arrival','Receiving hands wait at the end of an arrival arrow. Imagine an effect arriving and being felt by its recipient.','second-cradle,-.85,-.15,1.2 arrow,.85,.15,1.1,3.14159','heart,0,.75,.75'),
    ('发展','sent-unfolding','A sending arrow opens a folded map into a wider layout. Growing opportunities unfold as the project develops.','arrow,-.85,.15,1.1 map,.85,.15,1.3','sprout,0,-.75,.8'),
    ('谈','speech-two-flames','A speech bubble warms between two flames. Picture an animated conversation, with both speakers contributing to the discussion.','speech,-.85,.3,1.15 flame,.85,.15,1.1','flame,.85,-.65,.65'),
    ('至少','arrival-few-minimum','An arrival arrow reaches the first few beads beyond a threshold. That small reached amount is the minimum: at least.','arrow,-.85,.15,1.1 count-3,.85,.15,1.15','bar,0,-.75,1.1'),
    ('解释','untie-release-explain','An untied knot opens beside a released speech bubble. Loosen the confusing message so someone can understand the explanation.','second-knot,-.85,.1,1.2 speech,.85,.3,1.2','second-check,0,-.75,.8'),
    ('负责','carry-responsibility','A burden-bearing worker holds a responsibility checklist. Taking charge means carrying the load and completing the listed duties.','second-burden,-.85,-.05,1.15 second-checklist,.85,.1,1.2','box,0,-.8,.6'),
    ('首先','head-first','A leader’s head stands beside the first bead at the start of a route. Begin with this one: first of all.','face,-.85,.1,1.15 count-1,.85,.1,1.2','arrow,0,-.75,.85'),
    ('理解','reason-untied','A reason checklist sits beside a loosened knot. Once the tangle is untied, the explanation becomes understandable.','second-checklist,-.85,.15,1.2 second-knot,.85,.15,1.2','second-check,0,-.75,.8'),
    ('报道','report-route','A report envelope travels along a road toward listeners. Following the route carries the news to its audience.','envelope,-.85,.25,1.2 road,.85,-.3,1.3','speech,0,.85,.75'),
    ('安排','peaceful-row','A peaceful home faces a neatly arranged row of chairs. Put each thing in its proper place to arrange the event.','house,-.85,.05,1.1 shelf,.85,.15,1.2','chair,.5,-.75,.45 chair,1.1,-.75,.45'),
    ('重新','heavy-new-again','A heavy old weight faces a newly wrapped box, with a return loop above. Start again and make a fresh attempt.','second-weight,-.85,-.15,1.2 box,.85,.1,1.15','second-cycle,0,.85,.8'),
    ('幸福','fortunate-blessing','A lucky star floats beside a blessing gift with a heart between. Imagine the lasting contentment of happiness.','star,-.85,.25,1.2 box,.85,-.1,1.2','heart,0,.75,.8'),
    ('自然','self-so-nature','A self-mirror reflects a sprout growing just as it is. Let the plant follow its own course: natural, or nature.','mirror,-.85,.1,1.2 sprout,.85,.0,1.3','tree,0,-.75,.65'),
    ('责任','responsibility-bearer','A responsibility sheet passes into a duty bearer’s hands. Accepting the sheet means accepting the obligation that comes with it.','second-checklist,-.85,.15,1.2 second-burden,.85,-.1,1.15','second-cradle,0,-.75,.65'),
    ('试','speech-formula-test','A speech bubble proposes a formula on a test sheet. Try it with a tool and check whether it works.','speech,-.85,.3,1.15 paper,.85,.1,1.2','second-hammer,0,-.75,.75 question,0,.85,.6'),
    ('弄','jade-hands-do','A jade ring stands beside two cupped hands and a tool. Imagine the hands handling and adjusting the jade: do or make.','second-jade,-.85,.25,1.2 second-cradle,.85,-.15,1.2','second-hammer,0,-.75,.65'),
    ('赢','winning-cup','A gold trophy stands above the finish line with a checked flag beside it. Picture reaching the winning position.','second-trophy,0,.0,1.8','flag,1.1,-.65,.75 second-check,-1.1,-.65,.75'),
    ('说明','speaking-bright','A speech bubble points toward a brightly lit diagram. Make the message clear enough to see: explain or illustrate.','speech,-.85,.3,1.2 sun,.85,.4,1.1','paper,0,-.75,.9'),
    ('许多','permitted-many','A permission check lets a large bead pile into a basket. Plenty are admitted: many, not just one or two.','second-check,-.85,.25,1.1 count-12,.85,.0,1.15','basket,0,-.75,.85'),
    ('压力','pressing-strength','A pressing weight bears down on a strong supporting post. Imagine the downward force as pressure on the support.','second-weight,0,.82,1.2 pole,0,-.55,1.2','arrow,-1.3,.15,.85,-1.5708'),
    ('由于','from-marker-cause','A source field sends water toward a marked point. The plant grows due to that source: because of it.','field,-.85,-.3,1.2 second-target,.85,.15,1.1','water,0,-.75,1 sprout,.85,.85,.65'),
    ('母亲','mother-parent','A mother figure stands beside the family home with a child. Picture her caring parent role to remember mother.','woman,-.85,-.05,1.15 house,.85,.05,1.1','child,0,-.75,.65'),
    ('放弃','release-discard','An open releasing hand lets a project fall toward a discard bin. Stop holding on to the attempt: give up.','hand,-.85,.4,1.1 second-bin,.85,-.15,1.2','paper,0,-.3,.7 arrow,0,.75,.65,-1.5708'),
    ('意见','idea-seeing','An idea-lamp shines beside an observing eye over a suggestion note. What you think and see becomes your opinion.','lamp,-.85,.25,1.2 eye,.85,.25,1.2','paper,0,-.75,.85'),
    ('过程','passing-process','A passing arrow moves along measured steps on a road. Watch the intermediate stages rather than just the destination: the process.','arrow,-.85,.2,1.1 second-steps,.85,-.25,1.2','road,0,-.85,1.3'),
    ('即使','immediate-action-condition','An immediate clock signal faces a hand making an action happen. Imagine the result continuing even if that condition changes.','clock,-.85,.15,1.2 hand,.85,.15,1.1','question,0,.85,.7 arrow,0,-.75,.75'),
    ('尽管','used-up-despite','An empty bowl sits beside a managing pipe, but water still flows onward. Even when supplies are exhausted: although, despite.','bowl,-.85,-.25,1.2 second-pipe,.85,.0,1.2','water,0,-.75,1.1 arrow,0,.85,.65'),
    ('各','returning-each','Returning footsteps lead to one mouth, with matching mouths elsewhere. Give each traveler their own separate greeting.','footprints,-.85,-.25,1.2 mouth,.85,.15,1.2','mouth,0,.85,.55 mouth,0,-.8,.55'),
    ('仍然','still-so','A continuing worker remains beside a sprout that keeps growing as before. The unchanged loop says still, despite passing time.','person,-.85,-.05,1.1 sprout,.85,.0,1.3','second-cycle,0,.85,.8 clock,0,-.75,.65'),
    ('值得','worth-receiving','A value scale balances a gift above receiving hands. If the gift deserves the effort, it is worth getting.','scale,-.85,.1,1.2 second-cradle,.85,-.15,1.2','box,.85,.65,.7'),
    ('经历','thread-history-journey','A work thread passes through calendar pages along a traveled road. Each past stage becomes part of your experience.','silk,-.85,.15,1.1 calendar,.85,.15,1.2','road,0,-.75,1.3 footprints,0,-.65,.8'),
    ('讨论','asking-debate','An asking question bubble faces a debating speech bubble above one table. Exchange the differing views to discuss the issue.','question,-.85,.35,1.15 speech,.85,.35,1.15','table,0,-.75,1.1'),
    ('超过','beyond-passage','A beyond arrow passes a marked boundary and continues onward. Its destination exceeds the old limit.','arrow,-.85,.2,1.2 arrow,.85,.2,1.2','bar,0,-.7,.95,1.5708 second-target,1.45,-.65,.5'),
    ('假','person-borrowed-mask','A person holds a borrowed mask beside their real face. The painted face looks convincing but is false or fake.','person,-.85,-.05,1.15 second-mask,.85,.15,1.2','second-cross,0,-.75,.65'),
    ('后来','behind-coming-later','Footsteps coming forward trail behind a clock marker. Place their arrival after the marked moment: later.','footprints,-.85,-.3,1.2 footprints,.85,-.3,1.2','clock,0,.65,1'),
    ('嘴','mouth-beak','A human mouth faces a bird’s pointed beak. Both open for feeding or calling; keep the human mouth as the word’s meaning.','mouth,-.85,.1,1.3 bird,.85,.15,1.15','speech,0,.85,.65'),
    ('无论','none-debate-regardless','A no-sign covers a debating bubble while an arrow keeps going. Whichever argument is raised, the action continues regardless.','second-cross,-.85,.25,1.1 speech,.85,.25,1.2','arrow,0,-.75,1'),
    ('紧张','tight-stretch','A tight knot holds a stretched ribbon between two posts. Feel the strain as a picture of tension or nervousness.','second-knot,-.85,.15,1.2 silk,.85,.15,1.2','pole,-1.5,-.6,.65 pole,1.5,-.6,.65'),
    ('省','few-eye-saving','An eye watches a small pile of coins and keeps some aside. Using fewer resources remembers economizing or saving.','count-3,-.85,.1,1.2 eye,.85,.2,1.2','coins,0,-.75,.9'),
    ('十分','ten-divided-very','Ten beads are divided into a full row of bright pieces. Imagine all ten out of ten: very, to a high degree.','count-10,-.85,.1,1.1 knife,.85,.15,1.1','second-meter,0,-.75,1'),
    ('陪','gate-booth-company','A traveler waits beside a hill gate and a talking booth. Stay beside them through the visit to accompany them.','gate,-.85,.1,1.1 second-booth,.85,.1,1.1','person,0,-.75,.65'),
    ('挂','hand-earth-hanging','A hand suspends a cord above two stacked earth blocks. Picture hanging a bag high enough to clear the ground.','hand,-.85,.4,1.1 earth,.85,-.3,1.1','earth,.85,-.65,.85 bag,-.8,-.65,.8'),
    ('本来','root-arrival-original','A tree’s root lies beside approaching footsteps, with a backward arrow. Trace the arrival back to its original starting point.','tree,-.85,-.05,1.2 footprints,.85,-.3,1.2','arrow,0,.85,.75,3.14159'),
    ('条件','strip-item-condition','A marked strip sits beside a required item on a checklist. Only when the item fits the strip is the condition met.','second-strip,-.85,.15,1.15 box,.85,.1,1.15','second-checklist,0,-.75,.85'),
    ('广告','shelter-announcement','A shelter-like kiosk holds a telling speech bubble and a bright product. Picture an advertisement calling attention to what is sold.','roof,-.85,.4,1.1 speech,.85,.3,1.15','box,0,-.75,.8'),
    ('警察','alert-investigation','An alert triangle stands beside an investigating eye and protective shield. Imagine a police officer watching carefully to keep people safe.','second-alarm,-.85,.2,1.15 eye,.85,.2,1.2','second-shield,0,-.75,.9 person,0,.85,.6'),
    ('关键','closed-key-point','A shut lock faces a key aimed exactly at its opening. The one point that opens the problem is the key point.','lock,-.85,.1,1.2 key,.85,.1,1.2','second-target,0,-.75,.7'),
    ('样子','pattern-child-appearance','A patterned shirt stands beside a child wearing a similar color. Notice the visible shape and style: appearance or manner.','shirt,-.85,.1,1.2 child,.85,-.05,1.1','mirror,0,-.75,.75'),
    ('困难','trapped-obstacle','A trapped figure sits inside a fence facing a tall barrier. Escaping requires effort: a difficult situation.','second-kneeler,-.85,-.2,1.1 second-fence,.85,.1,1.2','frame,-.85,.05,1.15'),
    ('专业','specialized-work','One precise gear is selected from a business shelf of tools. Concentrate on that field as a specialty or major.','gear,-.85,.15,1.2 shelf,.85,.1,1.2','second-target,0,-.75,.75'),
    ('难道','difficult-way-question','A difficult fence blocks a road under a large question bubble. Imagine asking in disbelief: could that really be the way?','second-fence,-.85,.15,1.1 road,.85,-.35,1.25','question,0,.8,1'),
    ('于是','marked-result-so','A marker receives water from a tipped cup, then a sprout appears beside an is-stamp. That consequence follows: so, thereupon.','second-target,-.85,.15,1.1 stamp,.85,.1,1.1','sprout,.85,.85,.6 arrow,0,-.75,.75'),
    ('规定','rule-fixed','A measured rule is fixed firmly onto a platform. The boundaries do not move: a stipulated rule.','second-ruler,-.85,.15,1.15 second-platform,.85,-.35,1.2','lock,.85,.5,.75'),
    ('正确','correct-certain','A correctness check faces a verified proof sheet. Matching answer and evidence makes the answer correct, not merely a guess.','second-check,-.85,.15,1.2 second-checklist,.85,.15,1.2','second-target,0,-.75,.75'),
    ('群','ruler-sheep-flock','A crowned ruler leads several sheep into one gathered flock. Imagine the whole group moving together.','second-crown,-.85,.35,1 sheep,.85,-.1,1.1','sheep,0,-.85,.6 sheep,1.45,.7,.5'),
    ('够','sentence-many-enough','A spoken sentence asks for beads; the many-bead bowl reaches its marked fill line. Now there is enough.','speech,-.85,.3,1.15 count-9,.85,.05,1.1','bowl,.85,-.65,.9 bar,0,-.85,.8'),
    ('方向','square-toward-direction','A square map faces an arrow pointing toward its chosen corner. Use the map and compass to remember direction.','frame,-.85,.1,1.1 arrow,.85,.15,1.2','second-compass,0,-.75,.9'),
    ('市场','market-ground','A market shelf stands on a broad open ground. Picture stalls gathering here to trade goods: a market.','shelf,-.85,.1,1.15 field,.85,-.3,1.3','apple,-.85,.4,.55 coins,0,-.75,.65'),
    ('教育','teaching-nurture','A teaching book stands beside a nest protecting eggs. Imagine nurturing a learner as carefully: education guides growth rather than simply testing.','book,-.85,.1,1.2 second-nest,.85,-.25,1.2','child,0,.85,.6'),
    ('取','ear-hand-taking','A hand reaches toward an ear-shaped token on a tray. Picture picking up the token to remember take or collect.','ear,-.85,.15,1.2 hand,.85,.15,1.2','plate,0,-.75,.9'),
    ('危险','precarious-danger','A precariously balanced weight stands beside a danger triangle. The unstable arrangement tells you to keep away.','second-weight,-.85,.4,1.1 second-alarm,.85,.2,1.2','pole,-.85,-.5,.9'),
    ('管理','pipe-reason-management','A managing pipe channels water beside a reason checklist. Direct the flow and make orderly decisions: manage.','second-pipe,-.85,.05,1.2 second-checklist,.85,.15,1.2','water,0,-.75,1.1'),
    ('乱','tongue-hook-disorder','A tongue tangles with a bent hook and loose cords. Their mixed-up positions make a picture of messy disorder.','tongue,-.85,.15,1.2 hook,.85,.15,1.2','silk,0,-.75,1.1'),
    ('适合','fitting-together','One fitted puzzle piece meets another at a matching join. Nothing needs forcing: the pair is suitable for each other.','second-puzzle,-.85,.1,1.2 second-puzzle,.85,.1,1.2','second-check,0,-.75,.8'),
    ('正式','correct-formal-pattern','A correctness check sits beside a formula sheet carrying a stamp. The approved pattern makes the document formal or official.','second-check,-.85,.15,1.15 paper,.85,.1,1.2','stamp,0,-.75,.8'),
    ('引起','pulling-rise-cause','A pulling hook lifts an upward arrow from the ground. One motion causes another to arise: cause or arouse.','hook,-.85,.15,1.2 arrow,.85,.15,1.2,1.5708','second-chain,0,-.75,.8'),
    ('从来','following-arrival-always','Following footsteps arrive along a repeating route. Imagine this path taken at every earlier time: ever or always.','footprints,-.85,-.25,1.2 footprints,.85,-.25,1.2','second-cycle,0,.75,1'),
    ('内容','inside-container-content','An inside frame surrounds a container of papers. Look at what is held within, not the outside shell: content.','frame,0,.12,1.4 basket,0,-.3,1.2','paper,0,.02,.65,0,.10'),
    ('律师','law-teacher','A legal rule stands beside a teaching book and scales. Imagine the trained professional explaining the law: a lawyer.','second-ruler,-.85,.15,1.15 book,.85,.1,1.2','scale,0,-.75,.85'),
    ('通知','passing-knowing','An open passage carries a message toward a knowing eye. Let the news reach the listener: notify.','gate,-.85,.1,1.1 eye,.85,.2,1.2','envelope,0,-.7,.8 arrow,0,.85,.65'),
    ('感情','felt-emotion','A touching hand faces a glowing emotion heart. The imagined warmth between them recalls feelings and affection.','hand,-.85,.15,1.15 heart,.85,.15,1.25','second-chain,0,-.75,.8'),
    ('目的','eye-ownership-purpose','An eye fixes on a target tagged as its own goal. The tag tells you what the effort is for: purpose.','eye,-.85,.15,1.2 second-tag,.85,.15,1.2','second-target,0,-.75,.9'),
    ('观众','observing-crowd','An observing eye faces a row of seated people and a stage. The gathered watchers are the audience.','eye,-.85,.3,1.2 person,.85,-.05,1.1','person,.35,-.8,.5 person,1.3,-.8,.5 second-platform,0,.85,.7'),
    ('国际','country-border','A country-like globe sits beside a border fence with a bridge across it. Crossing national borders pictures international connections.','globe,-.85,.1,1.2 second-fence,.85,.1,1.15','bridge,0,-.75,.9'),
    ('美丽','beautiful-lovely','A beautiful flower stands beside a lovely butterfly above a mirror. Picture their colors together as a memorable scene of beauty.','flower,-.85,.1,1.2 butterfly,.85,.2,1.2','mirror,0,-.75,.75'),
    ('经验','thread-tested-experience','A work thread runs past a checked test sheet. Repeated work and testing build practical know-how: experience.','silk,-.85,.15,1.1 second-checklist,.85,.15,1.2','gear,0,-.75,.8'),
    ('破','stone-skin-broken','A stone fragment splits a leather skin patch. Imagine the punctured surface as something broken or damaged.','second-broken,-.85,.1,1.2 second-leather,.85,.1,1.2','second-cross,0,-.75,.7'),
    ('科学','science-learning','A measuring tool stands beside a learning book under a curious eye. Observe, measure and learn: science.','second-ruler,-.85,.15,1.15 book,.85,.1,1.2','eye,0,.85,.75'),
    ('标准','marked-accuracy','A marked ruler faces an accurately centered target. Use this agreed measurement as the standard for judging others.','second-ruler,-.85,.15,1.2 second-target,.85,.15,1.2','second-check,0,-.75,.7'),
    ('职业','professional-work','A profession’s tool stands beside an organized business shelf. The work you do regularly becomes your profession.','second-hammer,-.85,.15,1.2 shelf,.85,.1,1.2','person,0,-.75,.65'),
    ('精彩','essence-colorful','An essence-like star shines beside a colorful butterfly and festival ribbons. Concentrated vividness makes a wonderful, brilliant performance.','star,-.85,.25,1.2 butterfly,.85,.15,1.2','silk,0,-.75,.95'),
    ('范围','model-surrounding','A model house is surrounded by a enclosing fence. Its boundary defines the area covered: range or scope.','house,-.85,.1,1.1 second-fence,.85,.1,1.15','second-brackets,0,-.75,.85'),
    ('速度','speed-degree','A fast-moving arrow faces a degree meter beside a racing car. The measured motion recalls speed.','arrow,-.85,.2,1.2 second-meter,.85,.2,1.1','car,0,-.75,.95'),
    ('实在','real-present','A solid jade ring rests at a precisely marked spot. It is really here, not just imagined: indeed or really.','second-jade,-.85,.15,1.2 second-target,.85,.15,1.2','second-check,0,-.75,.8'),
    ('效果','effect-fruit','A changed puzzle sits beside the fruit of completed work. Compare the before and after to see the effect.','second-puzzle,-.85,.1,1.2 fruit,.85,.1,1.3','arrow,0,-.75,.75'),
    ('遍','road-complete-round','A road leads past a flat banner and loops back to its start. One complete journey is one repetition.','road,-.85,-.3,1.3 flag,.85,.2,1.1','second-cycle,0,.85,.85'),
    ('经济','work-thread-aid','A work thread connects coin shelves across an aid bridge. Imagine resources moving through this connected system: the economy.','silk,-.85,.15,1.1 bridge,.85,-.15,1.1','coins,0,-.75,.9'),
    ('按照','pressed-lit-guide','A pressing hand holds a guide sheet under a lamp. Follow the illuminated directions: according to the guide.','hand,-.85,.2,1.1 lamp,.85,.2,1.15','paper,0,-.75,.85'),
    ('反对','reverse-facing','Two arrows face each other head-on instead of sharing a direction. Their opposing directions remember disagreement or opposition.','arrow,-.85,.15,1.2 arrow,.85,.15,1.2,3.14159','second-cross,0,-.75,.75'),
    ('竟然','finally-unexpected','A final finish flag suddenly appears beside an improbable growing sprout. The question overhead catches the surprise: unexpectedly.','flag,-.85,.2,1.1 sprout,.85,.0,1.3','question,0,.85,.85'),
    ('重点','heavy-dot-focus','A heavy weight rests above one bright dot on a target. Give that point the most attention: the main focus.','second-weight,-.85,-.1,1.25 second-target,.85,.15,1.2','eye,0,.85,.7'),
    ('倍','person-booth-multiplier','A person visits a spitting booth where one coin becomes two. Imagine that odd doubling machine as a multiplier.','person,-.85,-.05,1.1 second-booth,.85,.05,1.1','count-1,-.45,-.8,.65 count-2,.65,-.8,.65'),
    ('醒','wine-star-waking','A wine jar sits under a star while a sleeper opens their eyes. Picture waking up after the night.','bottle,-.85,.0,1.2 star,.85,.5,1.1','eye,0,-.65,.9'),
    ('讨厌','asking-dislike','An asking question bubble keeps pestering a face behind a no-sign. The repeated demands become annoying and disliked.','question,-.85,.3,1.1 second-cross,.85,.2,1.15','face,0,-.75,.8'),
    ('输','vehicle-lost-stamp','A vehicle arrives beside a yes-stamp, but its trophy is crossed out. In this imagined contest, that vehicle loses.','car,-.85,-.15,1.2 stamp,.85,.15,1.1','second-cross,0,-.65,.55,0,.35 second-trophy,0,-.65,.7'),
    ('咱们','inclusive-we','Two people, one addressing the other, gather inside a shared bracket. Include the listener too: we, including you.','person,-.85,-.05,1.1 person,.85,-.05,1.1','second-brackets,0,.2,1.7 speech,0,-.75,.7'),
    ('免费','exempt-cost','An exemption check crosses out the coin charge on a gift box. No payment is needed: free of charge.','second-check,-.85,.2,1.1 coins,.85,-.05,1.15','second-cross,.85,.15,.7,0,.25 box,0,-.75,.75'),
    ('否则','no-rule-otherwise','A no-answer cross sends a traveler toward a rule blade at the alternate gate. Choose the other branch: otherwise.','second-cross,-.85,.2,1.1 knife,.85,.2,1.1','gate,0,-.55,.85 arrow,0,.85,.65'),
    ('动作','moving-making','A movement arrow points toward a hand making a gesture. Watch the actual bodily action rather than just the intention.','arrow,-.85,.15,1.2 hand,.85,.15,1.2','person,0,-.75,.65'),
    ('俩','person-two','A person stands beside two joined beads, with a matching companion nearby. Count the two people together: both.','person,-.85,-.05,1.1 count-2,.85,.1,1.1','person,.85,-.8,.55'),
    ('著名','well-known-name','A spotlight-like sun shines on a name tag above a crowd. The name is widely recognized: famous.','sun,-.85,.5,1.1 second-tag,.85,.15,1.2','person,0,-.75,.65 person,.85,-.75,.65'),
    ('拒绝','refuse-cut-off','A refusing hand blocks a gift while a knife cuts the connecting cord. The offered connection is firmly refused.','hand,-.85,.2,1.1 knife,.85,.2,1.1','second-cross,0,.85,.75 silk,0,-.75,.85'),
    ('帅','blade-cloth-handsome','A neat blade trims a smart cloth beside a mirror. Imagine the polished outfit making its wearer look handsome.','knife,-.85,.2,1.15 towel,.85,.0,1.2','mirror,0,-.75,.85'),
    ('不仅','not-only-one','A no-sign rejects the single-bead limit while more beads enter. The scene includes not only that one, but others too.','second-cross,-.85,.2,1.1 count-1,.85,.2,1.1','count-4,0,-.75,.9 second-plus,0,.85,.65'),
    ('顺利','smooth-profit','A smooth road curves toward a pile of profit coins without obstacles. Imagine the journey going smoothly from start to finish.','road,-.85,-.3,1.25 coins,.85,-.1,1.15','arrow,0,.75,.9 second-check,0,-.8,.65'),
    ('艺术','art-technique','An art brush stands beside a precise carving tool and finished flower ornament. Creative work plus practiced technique becomes art.','brush,-.85,.15,1.2 second-hammer,.85,.15,1.2','flower,0,-.75,.85'),
    ('麻烦','numb-annoyed-trouble','A tangled thread numbs a hand while a frowning no-sign blocks the task. Imagine the annoying complication as trouble.','second-knot,-.85,.15,1.2 second-cross,.85,.2,1.1','hand,0,-.75,.75'),
    ('申请','extended-please-application','An extended hand presents an application sheet under a polite speech bubble. Reach out and ask for permission to apply.','hand,-.85,.2,1.2 speech,.85,.3,1.1','paper,0,-.75,.9'),
    ('演出','performing-exit','A dancer performs on a stage beside an exit gate. Imagine stepping out in front of the audience for a performance.','dancer,-.85,-.05,1.1 gate,.85,.05,1.1','second-platform,0,-.85,1.3 music,0,.85,.65'),
    ('竞争','upright-contest','Two upright racers reach for the same contested trophy. Only one can claim it first: competition.','person,-.85,-.05,1.1 hand,.85,.2,1.1','second-trophy,0,.85,.75 person,1.3,-.75,.45'),
    ('估计','estimated-count','A question bubble sits over a counting board and a partial ruler. Judge the amount without measuring exactly: estimate.','question,-.85,.3,1.1 count-7,.85,.05,1.1','second-ruler,0,-.75,.9'),
    ('失败','lost-failed','An empty receiving hand faces a broken project beneath a crossed-out trophy. The attempt has not achieved its goal: failure.','second-cradle,-.85,-.15,1.15 second-broken,.85,.0,1.2','second-trophy,0,.85,.7 second-cross,0,.85,.6,0,.3'),
    ('世纪','generation-record-century','A generation stands beside recording thread and a calendar of ten rows of ten years. The full hundred years make one century.','person,-.9,-.05,1.1 silk,.9,.15,1.1','second-century,0,-.65,1'),
    ('制造','manufactured-built','A manufacturing gear feeds parts toward a building hammer. The organized assembly produces a new object: manufacture.','gear,-.85,.15,1.2 second-hammer,.85,.15,1.2','box,0,-.75,.9'),
    ('不得不','no-alternative','Two no-signs close the side exits while receiving hands face the only open path. With no alternative, you have to proceed.','second-cross,-1.3,.15,.9 second-cradle,0,-.1,1 second-cross,1.3,.15,.9','arrow,0,.85,.8 gate,0,-.8,.65'),
    ('当地','positioned-ground-local','A position marker stands on a patch of ground beside its house. Focus on this very place and its local surroundings.','second-target,-.85,.15,1.1 earth,.85,-.3,1.3','house,.85,.65,.8'),
    ('允许','consent-permission','A consent check faces an opening gate with a second permission check. The way is authorized: allow.','second-check,-.85,.2,1.1 second-check,.85,.2,1.1','gate,0,-.65,.95'),
    ('大概','big-approximation','A big measuring frame surrounds a partly filled meter and a question. The size is close, not exact: approximately or probably.','frame,-.85,.15,1.2 second-meter,.85,.15,1.1','question,0,-.75,.75'),
    ('教授','teacher-award','A teaching book sits beside an award trophy at a scholar’s desk. Imagine the respected university teacher: a professor.','book,-.85,.1,1.2 second-trophy,.85,.15,1.2','elder,0,-.75,.65'),
    ('吸引','inhale-pull-attract','A breath stream draws toward a pulling hook holding a flower. Imagine the pleasant scent pulling your attention: attract.','second-breath,-.85,.15,1.2 hook,.85,.15,1.2','flower,0,-.75,.85'),
    ('顿','camp-page-meal-unit','A camp-like tent roof shelters a menu page beside one meal. Count that whole sitting as one meal occasion.','roof,-.85,.35,1.1 paper,.85,.15,1.2','bowl,0,-.75,1 rice,0,-.55,.8'),
    ('共同','together-same','A joining plus links two matching puzzle pieces. They share the same task and work jointly, not separately.','second-plus,-.85,.15,1.1 second-puzzle,.85,.15,1.2','person,0,-.75,.6 person,.85,-.75,.6'),
    ('杂志','mixed-determined-magazine','A mix of colorful pages sits beside a determined writing brush. Bind these varied articles into a magazine.','paper,-.85,.15,1.2 brush,.85,.15,1.2','book,0,-.75,.9 flower,0,.85,.6'),
]


def _specs(text, p):
    objects = []
    for token in text.split():
        values = token.split(',')
        if len(values) < 4 or len(values) > 6:
            raise ValueError('Invalid explicit prop specification: '+token)
        kind = values[0]
        x,y,scale = map(float,values[1:4])
        rotation = float(values[4]) if len(values)>4 else 0
        z = float(values[5]) if len(values)>5 else 0
        objects.append(p(kind,x,y,scale,z=z,rotation=rotation))
    return objects


def register(add, p):
    lessons = {lesson['word']:lesson for lesson in json.loads((Path(__file__).resolve().parents[2]/'public/data/lessons.json').read_text())}
    for word,slug,story,part_specs,extra_specs in ROWS:
        glyphs = [element['glyph'] for element in lessons[word]['memoryElements']]
        parts = _specs(part_specs,p)
        if len(parts) != len(glyphs):
            raise ValueError('Middle-batch source part count mismatch: '+word)
        add(word,'complete-second-'+slug,story,glyphs,parts,_specs(extra_specs,p))
