"""Explicit compositions for the first 294 previously unillustrated words.

Each row is authored for one selected lesson sense. Spatial symbols, opaque
compounds and grammar scenes are invented memory aids, not etymological claims.
Glyph order is read from the authoritative lesson, never inferred from a prop.
"""
import json
from pathlib import Path


# A part may be a prop name or (prop, x, y, scale, rotation, z).
# Supporting objects always have an explicit position and are not glyph labels.
ROWS = [
    ('高手','expert-hand','A hand reaches the top of a tall tower and holds a trophy: imagine an expert whose skill rises high.', [('tower',-1,-.12,1.15),('hand',.70,.45,1.3)], [('first-trophy',.80,-.70,.65)]),
    ('银行','silver-bank','Silver waits beside walking footsteps leading into a locked building: take your silver to the bank.', ['first-silver','footprints'], [('house',.75,.85,.70),('lock',-.10,-.92,.60)]),
    ('行走','walking-path','Footprints meet a walking person on the same road: both cues keep the action of walking in view.', ['footprints','walker'], [('road',0,-1.04,1.6)]),
    ('长大','growing-up','A long ribbon becomes a height measure beside a big person; a smaller child below recalls growing up.', ['silk','person'], [('child',1.10,-.90,.45),('arrow',0,.85,.55,1.5708)]),
    ('长江','yangtze-length','A long ribbon follows a river channel with a boat: use this long river as a mnemonic for the Yangtze, not a geographical map.', ['silk','water'], [('boat',1,.50,.70)]),
    ('重要','important-weight','A heavy weight balances beside a reaching hand that wants it: the weight marks an important matter worth attention.', ['first-weight','hand'], [('first-target',0,.95,.55)]),
    ('重复','repeat-weight','A heavy weight sits beside circling arrows; imagine lifting the same weight repeatedly to remember repeat.', ['first-weight','first-repeat'], [('hand',0,-.94,.60)]),
    ('便宜','inexpensive-fit','A handy key fits its lock for a small payment of coins: convenient and suitable make this an inexpensive purchase.', ['key','lock'], [('coins',0,-.98,.50)]),
    ('方便','convenient-square','A square frame surrounds a conveniently placed key: the key is easy to reach when needed.', [('first-square',-.82,.03,1.30),('key',-.82,.03,.88)], [('hand',1.05,-.38,.90)]),
    ('东西','east-west-stuff','East and west arrows flank a basket of assorted things. The directions are a playful cue; here 东西 means stuff, not directions.', [('arrow',-1,.18,.95),('arrow',1,.18,.95,3.14159)], [('basket',0,-.62,.9),('book',-.25,-.55,.32),('apple',.30,-.50,.35)]),
    ('马虎','careless-pair','A horse and tiger stand beside a spilled cup: imagine someone mixing their care labels up through carelessness.', ['horse','tiger'], [('cup',0,-.92,.55,.90),('water',.55,-1.02,.60)]),
    ('巧克力','chocolate-strength','A skillful hand overcomes a heavy weight with strength, earning a chocolate bar. This is a whole-word loanword mnemonic, not a literal translation.', ['hand','first-trophy','first-weight'], [('first-chocolate',0,.99,.68)]),
    ('不好意思','embarrassed-thought','A no sign interrupts a good smile, an idea lamp and a thinking heart: picture the awkward pause before saying sorry.', ['first-not','first-smile','lamp','heart'], [('person',0,-.95,.44)]),
    ('莫名其妙','baffling-name','A no sign covers a name badge while a pointing arrow presents a wonderful star: the unnamed marvel leaves you baffled.', ['first-not','first-badge','arrow','star'], [('question',0,.90,.65)]),
    ('理所当然','expected-fit','A reason book shows the place for a piece; a pin sets it in position and a check confirms the expected result.', ['book','frame','first-pin','first-check'], [('first-jewel',0,-.95,.55)]),
    ('自相矛盾','spear-shield-conflict','A self badge faces a mirror while a spear confronts a shield: incompatible claims made by the same speaker contradict each other.', ['first-badge','mirror','first-spear','first-shield'], [('speech',0,.91,.65)]),
    ('画蛇添足','snake-unneeded-feet','A brush draws a snake; an adding hand supplies a foot the snake does not need. The extra part spoils the picture.', ['brush','first-snake','hand','foot'], [('paper',0,-.94,.75)]),
    ('一举两得','one-lift-two-prizes','One bar marks one attempt; an upward arrow lifts two beads into a receiving hand: gain two results with one action.', ['bar',('arrow',-.52,.0,.74,1.5708),'count-2','hand'], [('first-trophy',0,-.95,.60)]),
    ('不知不觉','unnoticed-passage','No signs hide a knowledge book and an observing eye while an hourglass runs: time passes without you noticing.', ['first-not','book','first-not','eye'], [('first-hourglass',0,.94,.60)]),
    ('的','ownership-tag','A white page and spoon hang beside an identity badge and a bag: imagine 的 as the tag linking an owner to their thing.', ['paper','spoon'], [('first-badge',-.40,.98,.50),('bag',.40,-.88,.60)]),
    ('了','finished-hook','A bent cap drops onto a hook beside a completed check mark: the action has finished or the situation has changed.', [('hook',-.90,.16,.88,1.5708),'hook'], [('first-check',0,-.92,.90)]),
    ('我','my-hand-weapon','A hand holds a halberd beside my identity badge. Point back to the badge and say I or me.', ['hand','first-halberd'], [('first-badge',0,-.94,.65)]),
    ('是','is-matching','A sun shines on a cloth roll while a matching roll waits below: the check links this object with what it is.', ['sun','first-clothroll'], [('first-clothroll',1,-.95,.50),('first-check',-.20,-.84,.62)]),
    ('你','your-badge','A person stands beside a badge offered toward the viewer: address that person as you.', ['person','first-badge'], [('arrow',0,-.95,.68)]),
    ('在','at-this-place','A trophy for talent rests on a patch of earth: point to its location to remember at or in.', [('first-trophy',-.75,.10,1.1),('earth',.75,-.50,1.4)], [('first-pin',.75,.58,.60)]),
    ('不','not-allowed','A red prohibition sign blocks a path: it visibly turns an action into not doing it.', ['first-not'], [('road',0,-1.0,1.3)]),
    ('有','have-a-thing','A hand holds a golden coin above a bag: the possession is there, and the owner has it.', ['hand'], [('coins',0,-.55,.70),('bag',.90,-.65,.80)]),
    ('他','he-on-bench','A man stands beside the also-bench, with a badge identifying him: use the pair to recall he.', ['man','sofa'], [('first-badge',-1,.94,.45)]),
    ('这','this-near-writing','A road leads to a written page immediately in front of you: a nearby pointer identifies this page.', ['road','paper'], [('arrow',.20,-.85,.65)]),
    ('个','one-item-classifier','A person places one counting pole beside one apple: 个 is the general counter for an individual item.', ['person','pole'], [('apple',0,-.93,.65)]),
    ('和','grain-and-mouth','A stalk of grain and a mouth join over one bowl: imagine 和 as the link saying grain and mouth together.', ['wheat','mouth'], [('first-link',0,-.93,.65)]),
    ('我们','we-group','My badge joins a group of people over a shared table: me plus the group becomes we.', ['first-badge','first-group'], [('table',0,-.91,.80)]),
    ('会','learned-cloud-skill','A person works beneath a cloud with a key and lock: imagine a learned skill that lets the person know how to unlock it.', ['person','cloud'], [('key',.95,-.78,.60),('lock',0,-.95,.55)]),
    ('都','all-through-gate','A narrator speaks beside a hill gate while every bead gathers inside its frame: no member is left out; all are included.', ['speech','gate'], [('mountain',1,.98,.45),('count-5',.95,-.25,.60)]),
    ('来','come-to-sprout','A not-yet-grown tree and two horns wait near the viewer; footsteps approach them from the road: come here.', ['sprout','horns'], [('footprints',0,-.95,.95),('arrow',0,.96,.70)]),
    ('很','very-tight-clamp','Leftward footsteps lead to a stubborn clamp gripping a very large heart: exaggerate the tightness to remember very.', ['footprints','first-clamp'], [('heart',.90,.12,.60),('arrow',-.94,.87,.65,3.14159)]),
    ('去','go-away-cocoon','A private cocoon leaves its patch of earth along an outward arrow: remember go as moving away from here.', ['earth','coil'], [('arrow',0,.89,.9)]),
    ('她','she-on-bench','A woman stands beside the also-bench and her badge: the woman in this imagined scene is she.', ['woman','sofa'], [('first-badge',-.95,.96,.45)]),
    ('想','heart-reflection','A mirror faces a heart beside an idea lamp: imagine turning an idea over in your heart as you think or want.', ['mirror','heart'], [('lamp',0,-.89,.65)]),
    ('能','able-moon-tools','A cocoon and moon receive two spoons as tools; the moon succeeds at scooping water, showing it is able to do the task.', ['coil','moon','spoon','spoon'], [('water',0,-.94,.75),('first-check',0,.97,.55)]),
    ('那','that-far-away','A pointing arrow aims at a small distant house: contrast the far-off target with the nearby large hand to remember that.', [('arrow',0,.12,1.6)], [('house',1.35,.82,.53),('hand',-1.30,-.63,.92)]),
    ('做','make-old-tale','A person turns an old tale in a book into a handmade toy boat: doing a task and making its result.', ['person','book'], [('boat',0,-.91,.65),('hand',0,.94,.55)]),
    ('什么','what-in-the-box','A question mark and curling question line hover over a closed box: ask what is inside it.', ['question','coil'], [('box',0,-.86,.75)]),
    ('点','clock-appointment','A clock sits on a fortune-telling stand above fire dots: imagine an appointment at a named hour, the o’clock use of 点.', ['table','flame'], [('clock',-.94,.82,.70),('flame',.65,-.89,.35),('flame',1.25,-.89,.35)]),
    ('没','did-not-strike','Water quenches a striking club before it reaches the drum; the blocked strike helps you remember did not.', ['water','bar'], [('drum',.95,-.86,.55),('first-not',0,.94,.65)]),
    ('年','year-cycle','A calendar stands inside circling arrows beside changing weather: imagine one complete yearly cycle.', ['calendar'], [('first-repeat',0,.95,.58),('sun',-1,-.76,.53),('snow',1,-.76,.53)]),
    ('吗','horse-question','A mouth asks a horse a question under a yes check and a no sign: 吗 marks a yes-or-no question.', ['mouth','horse'], [('question',0,.94,.60),('first-check',-.50,-.95,.42),('first-not',.50,-.95,.42)]),
    ('呢','what-about-nun','A mouth turns from one person toward a nun with a question bubble: what about her? That follow-up recalls 呢.', ['mouth','first-nun'], [('question',0,.95,.60)]),
    ('时候','time-to-wait','A clock hangs beside a person waiting on a seat: mark the time when the waiting happens.', ['clock','sitter'], [('chair',.99,-.85,.62)]),
    ('怎么','how-it-works','A question bubble and curling line surround a gear: ask how this mechanism works.', ['question','coil'], [('gear',0,-.90,.78)]),
    ('爱','protect-friend','A reaching claw lowers a cover over a friend beneath it: caring protection makes this an image of love.', [('first-claw',-1.35,.30,.90),('lid',0,.65,1.1),('person',1.20,-.15,.94)], [('heart',0,-.74,.72)]),
    ('喜欢','delight-and-joy','A delighted smile meets a joyful dancer beside a heart: picture the pleasure of something you like.', ['first-smile','dancer'], [('heart',0,-.90,.65)]),
    ('谁','who-spoke-bird','A speech bubble hovers beside a little bird wearing an identity badge: ask who is speaking.', ['speech','bird'], [('first-badge',.99,-.80,.52),('question',0,.96,.60)]),
    ('几','few-question-count','A slanting slash meets a bent curl over a few beads: ask how many, then count the small quantity.', [('bar',-.85,.23,.8,.90),'coil'], [('count-3',0,-.93,1.4)]),
    ('叫','call-tangled-cord','A mouth sends a call along a tangled cord toward a name badge: calling someone brings their name into the scene.', ['mouth','first-knot'], [('first-badge',0,-.88,.70)]),
    ('钱','metal-money-blades','Metal coins sit beside little blades, as if cut from the same metal: the spendable coins make money memorable.', ['coins','knife'], [('first-silver',0,-.94,.65)]),
    ('买','buy-head-cap','A bent cap rests above a head while coins approach a bag of goods: imagine buying the cap for the person.', [('hook',-.90,.50,.85,1.5708),('face',.90,-.05,1.05)], [('coins',-.75,-.85,.55),('bag',.40,-.86,.58)]),
    ('岁','age-evenings','A mountain watches another dusk sun set above a birthday cake: count the years of age, not mountain height.', ['mountain','sun'], [('cake',0,-.93,.62)]),
    ('朋友','friend-moons','Two companion moons shine beside a friend offering a hand: the paired moons and friendly person recall friend.', ['moon','person'], [('moon',-1.35,.87,.52),('hand',.30,-.94,.54)]),
    ('认识','recognize-badge-sign','An eye recognizes a familiar badge beside a recognizable sign: seeing both clues recalls knowing a person or recognizing them.', ['eye','first-badge'], [('flag',0,-.94,.68)]),
    ('块','piece-of-earth','A snapping clamp breaks a patch of earth into a separate block: remember one piece, also the everyday yuan unit.', ['earth','first-clamp'], [('box',0,-.95,.58),('coins',0,.95,.42)]),
    ('谢谢','double-thanks','Two grateful hands offer two hearts after receiving a gift: repeat the thank-you cue twice to recall 谢谢.', ['hand','hand'], [('heart',-1,.91,.45),('heart',1,.91,.45),('box',0,-.89,.68)]),
    ('多少','many-or-few','Many beads stand beside only a few beads under a question bubble: ask how many or how much.', ['count-9','count-2'], [('question',0,.99,.75)]),
    ('电影','electric-shadow','Electric lightning powers a screen showing a dark shadow: imagine moving pictures becoming a movie.', [('lightning',-.97,.15,1.10),('first-shadow',.97,.18,.85,0,.08)], [('screen',.97,.16,1.44,0,-.18),('camera',0,-.94,.72)]),
    ('哪','which-target','A mouth asks about a far-pointing arrow while two different gifts wait below: choose which one is meant.', ['mouth','arrow'], [('book',-.55,-.90,.55),('apple',.55,-.90,.55),('question',0,.96,.55)]),
    ('先生','first-grown-gentleman','A first-place flag stands beside a growing sprout and a gentleman’s badge: the imagined first-grown guest is addressed as Mr.', ['flag','sprout'], [('man',0,-.66,.83),('first-badge',0,.97,.40)]),
    ('些','some-here','A pin marks this spot beside two beads; a few additional beads nearby suggest some, not the whole collection.', ['first-pin','count-2'], [('count-3',0,-.95,.80)]),
    ('中国','middle-country','A middle marker stands in front of a globe, with a red flag on the country cue: use the center-country association to recall China.', ['first-target','globe'], [('flag',0,-.94,.63)]),
    ('名字','name-and-character','An identity badge rests beside a written page: the name is represented using written characters.', ['first-badge','paper'], [('pencil',0,-.92,.68)]),
    ('看见','catch-sight','A searching eye catches another eye looking back: both look and see converge on the object between them.', ['eye','eye'], [('apple',0,-.93,.72)]),
    ('字','child-under-writing-roof','A child shelters beneath a roof beside a written page: the sheltered learner is your cue for a written character.', [('roof',0,.72,1.70),('child',0,-.30,1.15)], [('paper',1.20,-.72,.62)]),
    ('漂亮','beautiful-floating-lamp','A floating boat glides toward a bright lamp with flowers nearby: imagine the lovely scene to recall beautiful.', [('boat',-.97,.0,1.10),'lamp'], [('water',-.97,-.43,1.18),('flower',0,-.93,.70)]),
    ('高兴','high-excitement','A tall tower stands beside an excited dancer under a happy face: joy seems to rise high.', ['tower','dancer'], [('first-smile',0,.95,.65)]),
    ('喂','phone-hello','A mouth speaks beside a frightened face holding a phone: replace the nervous silence with a telephone hello.', ['mouth','first-frown'], [('phone',0,-.88,.82)]),
    ('怎么样','how-is-pattern','A question bubble and curl hover beside a patterned board: ask how this new pattern looks or how it is.', ['question','coil','board'], [('first-ten-grid',1.38,-.02,.75),('eye',0,-.94,.62)]),
    ('菜','picked-vegetables','Grass grows beside a picking hand above a plate: imagine gathering fresh vegetables for a dish.', [('grass',-1,.02,1.1),('hand',.55,.24,.95)], [('leaf',.50,-.34,.55),('plate',.35,-.99,1.1)]),
    ('小姐','young-lady','A small bead rests beside an older-sister figure wearing a polite badge: use the small-sister cue to recall Miss.', ['count-1','girl'], [('first-badge',0,-.94,.60)]),
    ('对不起','sorry-no-rise','A mirror faces a no sign beside an upward arrow: picture failing to rise to someone’s expectations and saying sorry.', ['mirror','first-not',('arrow',1.40,.03,.88,1.5708)], [('heart',0,-.94,.65)]),
    ('同学','same-class-learners','Two matching badges identify learners sharing one book: people learning in the same class are classmates.', ['first-badge','book'], [('first-badge',-.97,.90,.48),('first-group',0,-.85,.67)]),
    ('再见','see-again-goodbye','Circling arrows promise another meeting beside an eye: wave goodbye with the hope of seeing each other again.', ['first-repeat','eye'], [('hand',0,-.95,.78)]),
    ('出租车','rented-exit-vehicle','An exit arrow leads past rental coins to a car: hire the vehicle for a taxi ride.', ['arrow','coins','car'], [('road',0,-1.04,1.7)]),
    ('没关系','no-bound-connection','An empty tray stands beside a closed lock and a tied cord; a reassuring check says the missing connection does not matter.', ['first-empty','lock','first-knot'], [('first-check',0,.98,.66)]),
    ('零','zero-rain-order','Rain falls beside an order flag onto an empty counting tray: the tray contains zero items.', ['rain','flag'], [('zero',0,-.83,.82)]),
    ('北京','north-capital','A north-pointing arrow rises beside a capital tower: remember Beijing with this north-capital cue, not as a street map.', [('arrow',-.90,.0,1.05,1.5708),'tower'], [('flag',0,-.91,.60)]),
    ('汉语','chinese-language','A red flag represents the Chinese cue beside a speech bubble and book: imagine speaking the Chinese language.', ['flag','speech'], [('book',0,-.92,.72)]),
    ('不客气','welcome-no-formality','A no sign meets a guest and a curl of air: wave away stiff formalities when saying you’re welcome.', ['first-not','person','steam'], [('heart',0,-.94,.62)]),
    ('就','as-soon-capital','An important capital tower sends a special star signal; the next action starts as soon as the signal appears.', ['tower','star'], [('arrow',0,-.93,.86)]),
    ('要','woman-wants-west','A west-pointing arrow leads to a woman reaching for a cup: hold her want or need in mind.', [('arrow',-.90,.05,1.10,3.14159),'woman'], [('cup',.30,-.95,.70)]),
    ('也','also-bench','An extra person joins the occupied bench: the added sitter is also included.', ['sofa'], [('person',-.67,.44,.58),('person',.68,.44,.58)]),
    ('到','arrival-cutoff','An arrival arrow meets a knife at the end of a road: the journey has reached its destination.', ['arrow','knife'], [('road',0,-1.0,1.45),('first-check',0,.94,.60)]),
    ('还','still-on-road','A road continues past a no sign blocking its finish: the traveler is still on the way, not finished yet.', ['road','first-not'], [('walker',0,-.78,.74)]),
    ('着','ongoing-sheep-watch','A sheep remains under the watching eye while an hourglass runs: the state continues during the observation.', ['sheep','eye'], [('first-hourglass',0,-.91,.65)]),
    ('给','give-wrapped-fit','Silk wraps a gift that fits into a waiting hand: imagine giving the package to its receiver.', ['silk','hand'], [('box',0,-.90,.65)]),
    ('让','allow-upward','A speech bubble gives permission beside an upward arrow: the speaker lets the child climb.', ['speech',('arrow',.95,.10,1.1,1.5708)], [('child',0,-.90,.56),('first-check',0,.95,.55)]),
    ('为','effort-for-someone','Two water drops surround a strong weight carried for a friend: imagine spending effort for someone else.', ['first-drop','first-weight','first-drop'], [('person',0,-.93,.48)]),
    ('可以','permission-by-key','A green permission check stands beside the key used to open a lock: with permission and a means, you may do it.', ['first-check','key'], [('lock',0,-.92,.75)]),
    ('吧','tail-suggestion','A mouth curls its tail toward a shared meal: imagine a gentle suggestion, “let’s eat,” ending with 吧.', ['mouth','first-tail'], [('bowl',0,-.94,.70)]),
    ('得','result-complement','Footsteps lead past a dawn sun to a thumb-like hand marking the result: 得 links an action to how it turns out.', ['footprints','sun','hand'], [('first-check',0,-.94,.65)]),
    ('真','really-straight-table','A straight pole stands on a small table beside a verified badge: imagine checking that the claim really is true.', ['pole','table'], [('first-check',0,.95,.68)]),
    ('已经','already-threaded','A completion check sits beside silk already threaded through a frame: the work was done before this moment.', ['first-check','silk'], [('frame',.98,-.04,1.18),('clock',0,-.93,.58)]),
    ('最','topmost-sun','A sun hangs highest above a reaching hand and two lower stars: the highest one is the most or the -est.', [('sun',-.95,.49,1.0),('hand',.95,.10,1.15)], [('star',-.96,-.84,.40),('star',-.36,-.84,.34)]),
    ('再','again-beard','One bar marks one turn while a hanging beard circles back under repeat arrows: imagine doing the action again.', [('bar',-.70,.76,1.1),('first-beard',-.70,-.02,1.05)], [('first-repeat',1.05,-.22,.95)]),
    ('因为','cause-for-result','A root-shaped cause leads by an arrow to a gift intended for someone: explain the gift by saying because of that cause.', ['first-root','box'], [('arrow',0,.92,.82)]),
    ('次','one-occasion','A piece of ice chills a yawning mouth beside a counting bead: one such moment is one occasion or time.', ['ice','mouth'], [('count-1',0,-.90,.90)]),
    ('知道','know-the-way','A knowledge book rests beside a road that reaches its goal: knowing the route helps recall know.', ['book','road'], [('first-target',0,.92,.62)]),
    ('问题','question-page','An asking mouth faces a page with a question mark: the unanswered page is a question or problem.', ['mouth','paper'], [('question',.95,.12,.70)]),
    ('它','it-under-roof','A spoon rests beneath a roof while a pointer identifies the object: call the nonhuman thing it.', [('roof',0,.70,1.8),('spoon',0,-.32,1.25)], [('arrow',-1.28,-.85,.65)]),
    ('但是','but-blocks-expectation','A barrier interrupts an otherwise confirmed route: although the first claim is true, but introduces the contrasting turn.', ['wall','first-check'], [('arrow',0,-.93,.82),('first-not',-.95,.91,.50)]),
    ('可能','possible-unlocked','Permission appears beside a useful tool and an unopened lock: the task might be possible, but it is not shown completed.', ['first-check','gear'], [('lock',0,-.92,.73)]),
    ('新','new-parent-axe','A parent stands beside an axe and a freshly made wooden toy: imagine the parent crafting something new.', ['person','axe'], [('boat',0,-.92,.67)]),
    ('找','search-for-halberd','A hand searches beside a halberd under a question bubble: look for the missing weapon’s owner.', ['hand','first-halberd'], [('question',0,.96,.63),('first-badge',0,-.94,.55)]),
    ('快','quick-snapping-heart','A heart races beside a snapping clamp while an arrow shoots past: exaggerate the speed to remember fast.', ['heart','first-clamp'], [('arrow',0,-.91,1.0)]),
    ('比','compare-two-spoons','Two spoons of different sizes sit side by side on a balance: compare one with the other, as in bigger than.', [('spoon',-.97,.03,.75),('spoon',.97,.03,1.4)], [('scale',0,-.88,.70)]),
    ('所以','therefore-method-place','A place marker fixes the cause on a board; a key provides the means leading to a checked result: therefore, that follows.', ['first-pin','key'], [('arrow',0,.92,.75),('first-check',0,-.93,.73)]),
    ('觉得','feel-and-receive','An observing eye faces a receiving hand holding a heart: notice something and take in the feeling to remember think or feel.', ['eye','hand'], [('heart',.95,.69,.60)]),
    ('向','toward-arrow','An arrow points toward a visible house: follow the direction to remember toward.', ['arrow'], [('house',1.35,.80,.60)]),
    ('一起','rise-together','One shared bar joins two people below a rising arrow: they start and rise together as one group.', ['bar',('arrow',.95,.05,1.15,1.5708)], [('first-group',0,-.88,.70)]),
    ('希望','hopeful-horizon','A hopeful heart faces a watching eye aimed at a distant sprout: imagine looking forward to good growth that has not happened yet.', ['heart','eye'], [('sprout',0,.94,.65)]),
    ('大家','everyone-big-home','A big doorway opens onto a home with a group assembled outside: the invitation includes everyone.', ['gate','house'], [('first-group',0,-.86,.80)]),
    ('非常','very-unusual','Refusal bars cross an ordinary calendar beside an exaggerated heart: imagine a feeling far beyond the usual, very strong.', [('first-times',-.95,.05,1.1),'calendar'], [('heart',0,-.83,.95)]),
    ('别','dont-cut-off','Another person waits beside a knife that cuts off the intended action: a no sign turns it into don’t.', ['person','knife'], [('first-not',0,-.93,.78)]),
    ('公司','public-manager-company','A public group gathers beside a manager with a work table: their organized workplace becomes a company.', ['first-group','person'], [('table',0,-.94,.82),('first-badge',1,.94,.45)]),
    ('第一','number-one','A counting board selects one golden bead beside a first-place trophy: number one is first.', ['calendar','count-1'], [('first-trophy',0,-.89,.79)]),
    ('告诉','tell-the-complaint','One mouth tells a message while another speech bubble carries a complaint: picture telling someone what happened.', ['mouth','speech'], [('ear',0,-.93,.75)]),
    ('事情','task-with-feeling','A task page rests beside a heart and a work tool: the matter needing attention carries a feeling with it.', ['paper','heart'], [('gear',0,-.92,.67)]),
    ('号','number-called','A mouth calls beside a bent hook holding a calendar: the hook tags the called number or date.', ['mouth','hook'], [('calendar',0,-.88,.72)]),
    ('件','one-clothing-item','A person and cow stand beside a single hanging shirt: 件 counts one piece of clothing or one matter, not a cow.', ['person','cow'], [('shirt',0,-.90,.76),('count-1',0,.96,.65)]),
    ('张','flat-item-counter','A bow stretches a long ribbon across a flat page: picture one spread-out sheet as a 张-counted object.', ['first-bow','silk'], [('paper',0,-.91,.76)]),
    ('准备','ready-target-kit','An accurate target stands beside a packed bag of tools: aim correctly and prepare everything before starting.', ['first-target','bag'], [('key',0,-.92,.57),('book',0,.95,.58)]),
    ('每','every-checked-bead','A complete row of five beads receives a check above it: imagine checking every bead, with none skipped.', ['count-5'], [('first-check',0,.90,.68)]),
    ('您','respectful-you','A you badge rests above a warm heart offered to its owner: add heartfelt respect when addressing you politely.', ['first-badge','heart'], [('person',0,-.92,.56)]),
    ('送','send-closed-gift','A road carries a closed gift box away along an arrow: send or give the package to someone else.', ['road','box'], [('arrow',0,.97,.80)]),
    ('笑','laughing-bamboo','Bamboo bends backward beside a laughing face: imagine a person bending with laughter among the stalks.', ['first-bamboo','dancer'], [('first-smile',0,.95,.62)]),
    ('完','finished-roof-coin','A final coin settles under a finished roof; a check shows there is no work left to finish.', [('roof',0,.70,1.75),('coins',0,-.43,1.2)], [('first-check',1.20,-.90,.65)]),
    ('路','feet-on-each-road','A foot follows a sign toward each branch of a road: imagine choosing the road for your next step.', ['foot','arrow'], [('road',0,-1.01,1.45)]),
    ('玩','king-coin-game','A king’s crown and a coin become game pieces beside a ball: set aside work and play.', ['hat','coins'], [('ball',0,-.93,.78)]),
    ('正在','correct-place-now','A correctness check stands beside a location pin while a person is working: the action is in progress right now.', ['first-check','first-pin'], [('person',0,-.83,.72),('gear',0,.96,.58)]),
    ('穿','tooth-through-hole','A tooth-shaped peg passes through a garment’s hole: imagine threading your body through clothing as you put it on.', ['frame','tooth'], [('shirt',0,-.88,.82)]),
    ('帮助','helping-two-hands','One helping hand meets an assisting hand above a heavy box: sharing the lift makes help concrete.', ['hand','hand'], [('box',0,-.93,.83)]),
    ('错','wrong-old-coin','A metal coin lands on the wrong old calendar page: the red no sign flags the mistake.', ['coins','calendar'], [('first-not',0,-.94,.76)]),
    ('卖','sell-ten-caps','Ten counting beads stand beside a bag for a buyer: exchange the goods for payment to remember sell.', ['count-10','bag'], [('coins',0,-.92,.67)]),
    ('懂','heart-directed-understanding','A heart listens to a director pointing at a clear diagram: the explanation finally makes sense, so you understand.', ['heart','person'], [('paper',0,-.91,.62),('first-check',0,.96,.58)]),
    ('身体','body-frame-health','A person stands beside a body frame made from limbs: keep the whole body together with a health heart.', ['person','first-bodyframe'], [('heart',0,-.91,.63)]),
    ('元','yuan-two-legs','Two beads balance above a child’s legs beside a coin: use the two-and-legs image as a memory cue for yuan.', ['count-2','leg'], [('leg',1.38,.02,1.14),('coins',0,-.95,.78)]),
    ('介绍','introduce-two-people','An introducer holds a badge toward another person under a speaking bubble: bring one person to another by introducing them.', ['person','first-badge'], [('person',0,-.92,.53),('speech',0,.97,.66)]),
    ('欢迎','joyful-welcome','A joyful dancer waves beside an open doorway: imagine welcoming a visitor with visible delight.', ['dancer','door'], [('hand',0,.95,.65)]),
    ('忙','busy-lost-heart','A heart rushes after a lost badge amid work tools: too many unfinished tasks make the person busy.', ['heart','first-badge'], [('gear',0,-.94,.63),('first-hourglass',0,.96,.56)]),
    ('离','leaving-tracks','A lid and a fierce face remain behind while creature tracks lead away: the growing distance recalls leave or distance from.', ['lid','first-fierce','footprints'], [('arrow',0,.97,.80)]),
    ('去年','last-year-calendar','An outward arrow passes a calendar page marked behind the current clock: picture the year that has already gone.', ['arrow','calendar'], [('clock',0,-.93,.66),('arrow',0,.96,.65,3.14159)]),
    ('票','west-show-ticket','A west-pointing arrow directs you to a show stage; a small paper admits you as a ticket.', [('arrow',-.95,.05,1.1,3.14159),'star'], [('paper',0,-.93,.70)]),
    ('意思','meaning-in-thought','An idea lamp illuminates a thinking heart above a written page: ask what meaning the page conveys.', ['lamp','heart'], [('paper',0,-.93,.76)]),
    ('回答','return-an-answer','A return arrow carries a spoken response back toward the asking mouth: the returning message is an answer.', [('arrow',-.97,.05,1.1,3.14159),'speech'], [('mouth',0,-.93,.68),('first-check',0,.96,.58)]),
    ('运动','transport-into-motion','A transport cart stands beside a moving runner and ball: turn ordinary movement into exercise or sport.', ['car','walker'], [('ball',0,-.94,.66)]),
    ('妻子','wife-child-family','A wife stands beside a child near a shared home: the family scene keeps the wife sense distinct from the child cue.', ['woman','child'], [('house',0,.96,.65)]),
    ('鱼','fish-field-tail','A curled head leads to a field-patterned body above one lower bar: add a swimming fish to complete the playful fish mnemonic.', ['coil','field','bar'], [('fish',0,.98,.80)]),
    ('船','vessel-table-mouth','A vessel carries a small table beside a mouth-shaped opening: imagine these odd passengers aboard a boat.', ['boat','table','mouth'], [('water',0,-1.0,1.4)]),
    ('丈夫','measured-husband','A man holding a measuring ruler stands beside a husband with a shared-home badge: recall the husband sense, not a height measurement.', ['man','man'], [('first-ruler',-.95,.94,.52),('house',0,-.93,.60)]),
    ('上班','up-to-work-class','An upward arrow points to a group assembled at work tables: go to work as the class of coworkers begins its shift.', [('arrow',-.97,.05,1.1,1.5708),'first-group'], [('table',0,-.94,.83)]),
    ('课','fruit-speech-lesson','A speech bubble explains a fruit beside a book: the little teaching demonstration becomes a lesson or class.', ['speech','fruit'], [('book',0,-.93,.71)]),
    ('考试','exam-try-page','An exam page waits beside a hand trying a pencil: show what you know by attempting the test.', ['paper','hand'], [('pencil',0,-.94,.78),('question',0,.97,.59)]),
    ('千','thousand-counting','A slash stands beside a ten-bead counter; multiply those ten groups by a hundred-cell board to picture one thousand.', [('bar',-.95,.12,.85,.85),'count-10'], [('first-ten-grid',0,-.78,.85),('first-times',0,.96,.50)]),
    ('慢','slow-flowing-heart','A heart follows a long flowing ribbon while an hourglass empties: make the movement deliberately slow.', ['heart','silk'], [('first-hourglass',0,-.92,.72)]),
    ('颜色','face-color-palette','A colored face meets a varied palette of fruit, leaves and water: their contrasting surfaces keep color in mind.', ['face','first-jewel'], [('leaf',-.55,-.93,.55),('apple',0,-.93,.55),('water',.65,-.91,.50)]),
    ('报纸','reported-paper','A reporting speech bubble delivers words to a broad paper beside a clock: fresh reports become a newspaper.', ['speech','paper'], [('clock',0,-.94,.58)]),
    ('贵','expensive-shell','A middle marker and one bar guard a valuable shell above a pile of coins: imagine the high price of this expensive treasure.', ['first-target','bar','shell'], [('coins',0,-.93,.80)]),
    ('踢','easy-kick','A foot points toward an easily moved ball, with an arrow showing the kick’s direction: remember kick as the foot’s action.', ['foot','arrow'], [('ball',0,-.91,.74)]),
    ('百','hundred-white-count','One bar stands above a white page beside a board with ten rows of ten cells: count the full board as one hundred.', ['bar','paper'], [('first-ten-grid',0,-.73,1.04)]),
    ('好吃','good-to-eat','A happy face watches an eating mouth above a steaming dish: food that tastes good is delicious.', ['first-smile','mouth'], [('bowl',0,-.94,.73),('steam',0,.97,.55)]),
    ('题','question-on-page','A confirmation mark asks whether the answer is right beside an unfinished page: the page presents a question or exercise.', ['first-check','paper'], [('question',.98,.01,.70)]),
    ('姓','growing-family-name','A woman tends a growing sprout beside a family identity badge: picture the surname passed through a growing family.', ['woman','sprout'], [('first-badge',0,-.93,.70)]),
    ('阴','moon-gate-overcast','A hill gate frames the moon while thick clouds hide the sun: the shaded sky recalls overcast.', ['gate','moon'], [('cloud',0,.96,1.00),('mountain',-.96,-.91,.45)]),
    ('公斤','kilogram-public-axe','A public scale weighs an axe against a single weight: this imagined kilogram standard reminds you of the weight unit.', ['scale','axe'], [('first-weight',0,-.94,.65)]),
    ('公共汽车','public-bus','A public group gathers together beside steam and a large vehicle: picture many passengers sharing a bus ride.', ['first-group','first-link','steam','car'], [('road',0,-1.06,1.8)]),
    ('啊','affectionate-exclamation','A mouth sends a warm call toward a heart: make the sound ah or oh as an exclamation.', ['mouth','heart'], [('speech',0,-.92,.67)]),
    ('把','handle-object-tail','A hand grips a curling tail beside a cup being moved: picture 把 introducing the object that an action handles.', ['hand','first-tail'], [('cup',0,-.95,.68),('arrow',0,.96,.60)]),
    ('被','clothes-receive-action','Clothing lies beside a skin hide under a hand applying a brush: focus on the garment receiving the action, the passive use of 被.', ['shirt','first-hide'], [('brush',0,-.94,.68),('hand',0,.96,.56)]),
    ('自己','self-own-reflection','A self badge faces its own mirror image: the same identity on both sides recalls oneself.', ['first-badge','mirror'], [('first-badge',.98,.08,.61,0,.18)]),
    ('用','use-a-tool','A hand grips a key beside a lock: choosing the tool for its purpose makes use visible.', ['hand'], [('key',0,-.32,.65),('lock',1.30,.30,.83)]),
    ('如果','if-fruit-choice','An uncertain question faces a fruit under an open gate: imagine “if the fruit is ripe” before choosing whether to take it.', ['question','fruit'], [('gate',0,-.79,.70)]),
    ('又','again-hand','A hand returns to the same gift under circling arrows: it repeats an action that already happened.', ['hand'], [('first-repeat',1.27,.20,.72),('box',0,-.96,.62)]),
    ('只','only-one-of-eight','A mouth requests only one bead while eight wait nearby: isolate the single chosen item from the rest.', ['mouth','count-8'], [('count-1',-.95,-.91,.90)]),
    ('更','even-more-ribbons','One bar marks the starting level, a speaking box announces it, and crossed ribbons point to a larger pile: even more than before.', ['bar','speech','first-times'], [('count-2',-.80,-.95,.72),('count-6',.80,-.96,.72)]),
    ('需要','need-water','An empty cup needs filling beside a wanting hand and water: lack plus desire makes need concrete.', ['cup','hand'], [('water',0,-.95,.75)]),
    ('地','manner-ground-bench','Earth and an also-bench sit below walking feet and a careful check: 地 links a description of manner to the action, as in walking carefully.', ['earth','sofa'], [('footprints',0,.93,.80),('first-check',0,-.94,.56)]),
    ('才','not-until-appointment','A talent trophy waits behind a closed gate until the clock reaches its appointment: not until that time can it be collected.', ['first-trophy'], [('gate',0,-.77,.90),('clock',1.30,.74,.57)]),
    ('跟','follow-clamped-steps','A foot follows a stubborn clamp moving along a path: stay with it and follow its steps.', ['foot','first-clamp'], [('footprints',0,-.95,.86)]),
    ('像','elephant-resemblance','A person stands beside an elephant with a matching silhouette in the mirror: compare what resembles what rather than claiming the person is an elephant.', ['person','first-elephant'], [('mirror',0,-.90,.73)]),
    ('还是','or-question-alternatives','A continuing road reaches a confirmation mark with two gifts waiting: ask whether to choose this one or that one.', ['road','first-check'], [('book',-.55,-.93,.52),('apple',.55,-.93,.52),('question',0,.95,.62)]),
    ('认为','consider-recognition','An eye recognizes a badge beside a heart offered for it: form a considered opinion about the person.', ['eye','heart'], [('first-badge',0,-.94,.64)]),
    ('应该','should-respond','A speaking bubble calls for a task beside a checked page: the expected response marks what someone should do.', ['speech','paper'], [('first-check',0,-.92,.77)]),
    ('位','respectful-person-counter','A person stands upright beside a second standing figure and a polite badge: 位 respectfully counts a person.', ['person','man'], [('first-badge',0,-.94,.68)]),
    ('带','carry-cloth-kit','Three crossing bars suggest the thirty cue beside a cover and cloth; bundle the cloth under the cover to bring or carry it.', ['first-thirty',('lid',.65,.63,1.1),('silk',.65,-.01,.85)], [('bag',.65,-.95,.62)]),
    ('种','grain-types','Grain grows beside a central sorting target with two different seeds: classify a kind or type by its distinguishing pattern.', ['wheat','first-target'], [('bean',-.40,-.94,.60),('rice',.48,-.94,.60)]),
    ('发现','sent-out-appears','An outward arrow reveals a jewel appearing from a box: finding the newly visible object becomes discovery.', ['arrow','first-jewel'], [('box',0,-.94,.62)]),
    ('一定','certainly-fixed','One bar is fixed by a pin above a checked destination: it cannot move, so the result feels definite and certain.', ['bar','first-pin'], [('first-check',0,-.91,.76)]),
    ('一直','continuous-line','One bar joins a straight pole beside an uninterrupted road: follow the unbroken line continuously, all along.', ['bar','pole'], [('road',0,-1.01,1.6)]),
    ('为了','for-a-finished-goal','A gift intended for someone hangs on a finished hook beside a target: the action is done in order to reach that purpose.', ['box','hook'], [('first-target',0,-.93,.73)]),
    ('世界','world-boundary','A family representing generations gathers beside a boundary frame around a globe: imagine all generations sharing the world.', ['first-generations','frame'], [('globe',.97,.08,.70)]),
    ('而且','and-another-shelf','A beard hangs beside a shelf already holding a book; an extra apple joins it: and also adds another thing.', ['first-beard','shelf'], [('book',.86,-.33,.34),('apple',1.15,.32,.32)]),
    ('必须','must-finish','A compulsory lock stands beside a beard with a task page trapped behind it: the page must receive a check before release.', ['lock','first-beard'], [('paper',0,-.93,.61),('first-check',0,.95,.55)]),
    ('老','old-spoon','An old figure leans on a spoon like a walking stick: its exaggerated age helps recall old.', ['elder','spoon'], [('clock',0,-.94,.55)]),
    ('其他','other-person','A pointer passes one selected badge and indicates a different man: that other person is outside the selected one.', ['arrow','man'], [('first-badge',0,-.94,.58)]),
    ('比赛','competition-prize','A scale compares two contestants beside a trophy: they compete to decide who wins the match.', ['scale','first-trophy'], [('first-group',0,-.93,.64)]),
    ('然后','then-after','A check completes the first task while a second page waits behind an arrow: then comes the next action, after that.', ['first-check',('arrow',.97,.05,1.15,3.14159)], [('paper',0,-.93,.63)]),
    ('条','long-object-counter','Returning footsteps reach a tree with one long ribbon hanging from it: 条 counts a long, strip-like thing.', ['footprints','tree'], [('silk',0,-.92,.80),('arrow',-.96,.92,.64,3.14159)]),
    ('放','place-in-square','A square tray meets a tapping hand that sets an apple inside it: place the object down.', ['first-square','hand'], [('apple',-.98,.04,.50)]),
    ('为什么','why-for-what','A gift-for-someone sits beside a what-question and a curling question line: ask why this gift was chosen, not what it contains.', ['box','question','coil'], [('first-root',0,-.95,.57)]),
    ('先','first-in-line','A flag marks the first of three waiting beads beside a forward arrow: this one acts before the others.', ['flag'], [('count-3',0,-.90,1.15),('arrow',1.10,.16,.70)]),
    ('关系','closed-tied-link','A closed lock connects to a tied cord linking two badges: the connection between them is their relationship.', ['lock','first-knot'], [('first-badge',-.48,-.96,.46),('first-badge',.48,-.96,.46)]),
    ('出现','exit-appears','An exit arrow points toward a jewel emerging into view beside an open door: the object appears.', ['arrow','first-jewel'], [('door',0,-.90,.75)]),
    ('了解','finished-untangling','A finished hook rests beside an untied cord and an open book: learning about the knot lets you understand how it works.', ['hook','silk'], [('book',0,-.93,.71)]),
    ('过去','past-behind','A passing arrow and a going traveler move beyond an old calendar: their already-finished route is the past.', ['arrow','walker'], [('calendar',0,-.92,.66),('arrow',0,.96,.66,3.14159)]),
    ('参加','join-add-one','A group welcomes a hand adding one bead to their shared tray: the newcomer joins and participates.', ['first-group','hand'], [('count-1',0,-.60,.64),('plate',0,-.99,.90)]),
    ('决定','decision-fixed','A hand chooses one key while a pin fixes the choice beside its lock: the decision is made.', ['hand','first-pin'], [('key',0,-.94,.65),('lock',0,.96,.55)]),
    ('分','divide-eight','Eight beads lie beside a knife and two trays: imagine splitting the group into four for each tray.', ['count-8','knife'], [('first-empty',-.60,-.95,.46),('first-empty',.60,-.95,.46)]),
    ('选择','choose-by-hand','A target marks the chosen apple beside a selecting hand: choose one item from the alternatives.', ['first-target','hand'], [('apple',-.95,.01,.43),('book',.38,-.94,.50)]),
    ('或者','or-narrated-choice','A branching arrow points to two options while a narrator speaks: choose the apple or the book, rather than both.', [('first-fork',-.96,.03,1.15),'speech'], [('apple',-.34,.58,.45),('book',-.34,-.52,.45)]),
    ('机会','machine-opportunity','A machine gear meets a usable key beside an open gate: a brief chance to operate it becomes an opportunity.', ['gear','key'], [('gate',0,-.91,.70),('clock',0,.96,.53)]),
    ('别人','separate-other-person','A separating wall stands beside a person with another badge: the person outside your own area is someone else.', ['wall','person'], [('first-badge',0,-.94,.64)]),
    ('使','official-causes-action','A person receives an official’s order beside a moving gear: the order makes the person cause the mechanism to turn.', ['person','man'], [('speech',.98,.95,.48),('gear',0,-.94,.65)]),
    ('其实','actually-real-object','A pointer singles out a solid apple beside its empty outline: the real thing, not the apparent outline, is what is actually there.', ['arrow','apple'], [('frame',0,-.92,.72)]),
    ('以后','after-this-key','A key opens the first gate while a later calendar waits behind it: after this step, the later event can happen.', ['key','calendar'], [('gate',0,-.88,.80),('arrow',0,.96,.75)]),
    ('要求','request-wanted-gift','A wanting hand reaches toward a speech bubble asking for a gift: a clearly expressed want becomes a request or requirement.', ['hand','speech'], [('box',0,-.93,.72)]),
    ('信','person-written-words','A person puts spoken words onto paper and into an envelope: the message becomes a letter.', ['person','speech'], [('envelope',0,-.92,.76)]),
    ('当然','of-course-fit','A piece fits in its expected position beside a confirming check: the obvious fit brings an of-course response.', ['first-pin','first-check'], [('first-jewel',0,-.94,.66)]),
    ('接','receive-from-attendant','A hand reaches toward an attendant carrying a cup: imagine receiving the offered object or answering their call.', ['hand','woman'], [('cup',0,-.94,.68)]),
    ('相信','believe-a-friend','A mirror faces a trusted badge above a heart: picture accepting the person’s words as believable.', ['mirror','first-badge'], [('heart',0,-.94,.72)]),
    ('虽然','although-rain','A rain cloud meets a confirmation check while a walker continues beneath it: although it rains, the walk still happens.', ['rain','first-check'], [('walker',0,-.89,.72)]),
    ('解决','untie-decide-solve','An untied ribbon lies beside a chosen key and an opened lock: untangling the obstacle and deciding the next step solve the problem.', ['silk','key'], [('lock',0,-.92,.72),('first-check',0,.95,.53)]),
    ('关于','about-marked-topic','A closed lock marks a location beside a pin and book: the marked book is the topic the speech is about.', ['lock','first-pin'], [('book',0,-.93,.58),('speech',0,.96,.60)]),
    ('完成','completed-success','A final check meets a trophy for success above a finished work page: every step is complete.', ['first-check','first-trophy'], [('paper',0,-.94,.68)]),
    ('努力','effort-lift','A helping hand works beside a heavy weight under a straining heart: sustained strength makes the effort visible.', ['hand','first-weight'], [('heart',0,-.94,.66)]),
    ('以前','before-front-page','A key sits in front of an earlier calendar page while a backward arrow points to it: remember before or previously.', ['key','calendar'], [('arrow',0,-.94,.86,3.14159)]),
    ('办法','task-method-tools','A task page stands beside the key that opens its lock: the usable solution is a method for handling the task.', ['paper','key'], [('lock',0,-.94,.72)]),
    ('特别','special-separated-star','A special star is separated from ordinary beads by a wall: notice the distinct item rather than the usual group.', ['star','wall'], [('count-5',0,-.94,.95)]),
    ('难','hard-to-catch-bird','A hand reaches after a little bird that keeps flying beyond a closed gate: the task is difficult to complete.', ['hand','bird'], [('gate',0,-.92,.77)]),
    ('注意','focus-on-idea','A target concentrates attention beside an idea lamp and a watching eye: focus on the idea instead of looking away.', ['first-target','lamp'], [('eye',0,-.94,.71)]),
    ('讲','explain-the-well','A speech bubble describes a well beside a listening ear: explaining how the well works makes tell or explain memorable.', ['speech','first-well'], [('ear',0,-.94,.64)]),
    ('万','ten-thousand-groups','A hundred-cell board faces another hundred-cell board above a multiplication sign: a hundred groups of a hundred gives ten thousand.', [('first-ten-grid',-.97,.09,1.10)], [('first-ten-grid',.97,.09,1.10),('first-times',0,-.97,.64)]),
    ('离开','leave-open-door','Footsteps move away from an opened door along an outward arrow: someone leaves the place behind.', ['footprints','door'], [('arrow',0,-.94,.91)]),
    ('以为','mistaken-tool-purpose','A key is chosen as a means for a gift box, but its lock refuses it: you thought it would work, mistakenly.', ['key','box'], [('lock',0,-.93,.61),('first-not',0,.96,.64)]),
    ('越','increasing-steps','Walking footsteps pass a ceremonial axe and climb toward taller piles of beads: each further step brings increasingly more.', ['footprints','axe'], [('count-2',-.55,-.96,.74),('count-6',.55,-.96,.74)]),
    ('影响','shadow-ringing-influence','A shadow reaches toward a ringing bell and changes the watcher’s mood: one thing affects another, an image of influence.', ['first-shadow','first-bell'], [('heart',0,-.94,.61)]),
    ('游戏','touring-game','A touring traveler moves toward a game board and ball: the trip becomes a playful game rather than work.', ['walker','first-ten-grid'], [('ball',0,-.94,.62)]),
    ('比较','compare-vehicles','A comparison scale stands beside two vehicles of different sizes: compare their sizes to judge which is relatively larger.', ['scale','car'], [('car',1.02,.89,.50)]),
    ('最近','most-near-time','A topmost star sits beside a calendar close to the clock: the nearest completed dates recall recently.', ['star','calendar'], [('clock',.32,-.92,.57)]),
    ('换','exchange-jewel','A hand offers a radiant jewel for a book across paired arrows: the two objects trade places in an exchange.', ['hand','first-jewel'], [('book',0,-.92,.67),('first-repeat',0,.96,.62)]),
    ('终于','finally-at-goal','An end flag stands beside a location pin after a long road: the traveler has finally reached the finish.', ['flag','first-pin'], [('road',0,-1.02,1.6),('first-check',0,.96,.55)]),
    ('脸','moon-face-group','A moon shines beside a gathered group while a large face watches them: connect the moon and together cues to your face mnemonic.', ['moon','first-group'], [('face',0,-.75,.97)]),
    ('总是','always-checked-dates','A total bead counter meets a confirmation check beside a repeating calendar: imagine the same result on every date, always.', ['count-5','first-check'], [('calendar',0,-.93,.65),('first-repeat',0,.96,.55)]),
    ('除了','except-removed-hook','A hand removes one item from a finished hook beside a bead group: the removed one is excepted from what remains.', ['hand','hook'], [('count-4',0,-.94,1.0)]),
    ('突然','sudden-burst','A lightning burst interrupts a confirming check beside a startled face: the change happens suddenly without warning.', ['lightning','first-check'], [('first-frown',0,-.94,.68)]),
    ('段','section-of-road','A short road stretch is bounded by two pins: isolate that section from the longer route on either side.', ['road'], [('first-pin',-.86,.26,.63),('first-pin',.86,.26,.63)]),
    ('检查','inspect-and-check','A inspecting eye studies a work page beside a checked target: verify the details before marking the inspection done.', ['eye','first-target'], [('paper',0,-.94,.72)]),
    ('米','meter-tree-measure','Two horns sit beside a tree and a measuring ruler: measure the tree in meters, the selected sense here rather than rice.', ['horns','tree'], [('first-ruler',0,-.96,.97)]),
    ('容易','easy-fit-container','A container accepts a key with a simple straight arrow: the task fits together easily without an obstacle.', ['first-empty','arrow'], [('key',-.93,.04,.63),('first-check',0,-.94,.64)]),
    ('根据','based-on-roots','Roots anchor a supporting base below a book: the claim rests on this evidence, so act according to it.', ['first-root','table'], [('book',.95,.73,.55)]),
    ('记得','remember-retrieve','A memory book stands beside a receiving hand that retrieves its marked page: bring the memory back to remember it.', ['book','hand'], [('paper',0,-.94,.61)]),
    ('辆','vehicle-counter-pair','A vehicle sits beside two beads and a matching vehicle: use 辆 to count individual vehicles, not passengers.', ['car','count-2'], [('car',-.94,.92,.55)]),
    ('简单','simple-single-piece','A short clear page meets one counting bead beside an uncluttered tool: the solution uses a single simple step.', ['paper','count-1'], [('key',0,-.94,.64)]),
    ('愿意','willing-heart-idea','A wishing heart faces an idea lamp and a friendly hand: the person is willing to take part in the proposed task.', ['heart','lamp'], [('hand',0,-.94,.71)]),
    ('楼','tree-basket-building','A tree supplies wood beside a basket-wearing person under a tower: imagine building the wooden floors upward.', ['tree','person'], [('basket',.98,.02,.65),('tower',0,.98,.55)]),
    ('清楚','clear-outlined-view','Clear water meets a sharply outlined frame with a jewel visible inside: the unobstructed view makes clear easy to recall.', ['water','frame'], [('first-jewel',.97,.04,.68)]),
    ('故事','old-tale-task','An old tale book opens beside a task page and a little stage: imagine telling a story about what someone did.', ['book','paper'], [('person',0,-.91,.60)]),
    ('一般','ordinary-sorted-items','One bar lies beside a sorting tray of equal beads: nothing stands out from the ordinary average group.', ['bar','first-empty'], [('count-5',.96,-.07,.75)]),
    ('可爱','cute-approved-heart','A permission check approves a loving heart beside a tiny kitten: the affectionate reaction recalls cute.', ['first-check','heart'], [('cat',0,-.88,.73)]),
    ('新闻','newly-heard-news','A fresh sprout stands beside an ear above a reporting page: newly heard reports become news.', ['sprout','ear'], [('paper',0,-.94,.77)]),
    ('声音','voice-and-sound','A speaking mouth faces a ringing bell with sound waves: listen to the voice and its audible sound.', ['mouth','first-bell'], [('ear',0,-.94,.60)]),
    ('马上','immediate-horse-up','A horse waits below an upward arrow beside a clock: imagine mounting at once, then remember the idiomatic immediately sense.', ['horse',('arrow',.97,.03,1.1,1.5708)], [('clock',0,-.94,.62)]),
    ('表示','display-show-message','A display board stands beside a pointing hand and a speech bubble: showing the board expresses a message.', ['board','hand'], [('speech',0,-.94,.69)]),
    ('经过','thread-through-passage','Silk threads through a frame beside a passing arrow: follow the path through the opening to remember pass through.', ['silk','arrow'], [('frame',-.94,.06,1.25)]),
    ('历史','history-records','An old calendar stands beside a record book under a backward arrow: the recorded earlier events become history.', ['calendar','book'], [('arrow',0,-.94,.80,3.14159)]),
    ('敢','dare-the-obstacle','A person approaches a high wall with a brave heart: imagine daring to attempt the difficult crossing.', ['person'], [('wall',1.17,.22,.98),('heart',0,-.94,.65)]),
    ('会议','meeting-discussion','A group able to act gathers beside a discussing speech bubble over a shared table: a meeting brings their views together.', ['first-group','speech'], [('table',0,-.94,.87)]),
    ('经常','often-threaded-dates','A thread runs beside an ordinary calendar through many repeated checks: the repeated dates make often memorable.', ['silk','calendar'], [('first-repeat',0,-.94,.68)]),
    ('节目','show-joint-eye','A bamboo joint joins a watching eye above a little stage: picture connected segments of a program or show.', ['first-bamboo','eye'], [('star',0,-.94,.72)]),
    ('作用','made-tool-function','A making hand stands beside a useful key and a working gear: watch what the tool is used for to recall its function or effect.', ['hand','key'], [('gear',0,-.94,.72)]),
    ('西','west-enclosed-stool','A stool sits beside an enclosure under a setting sun and west-pointing arrow: the enclosed stool is a playful cue for west.', ['table','frame'], [('sun',0,.97,.57),('arrow',0,-.94,.80,3.14159)]),
    ('差','poor-sheep-work','A sheep stands beside a work tool and a disappointed face: imagine an unsatisfactory result to remember poor or not-good quality.', ['sheep','gear'], [('first-frown',0,-.94,.69)]),
    ('结婚','marriage-knot','A tied knot joins a married pair above a shared heart: imagine tying the relationship when they get married.', ['first-knot','first-couple'], [('heart',0,-.94,.72)]),
    ('同意','same-idea-agreement','Two matching checks face one idea lamp: both people accept the same idea, so they agree.', ['first-check','lamp'], [('first-check',-.96,.95,.46)]),
    ('教','teach-child-by-tap','A devoted child studies a book while a tapping hand indicates the next line: the adult teaches the learner.', ['child','hand'], [('book',0,-.94,.73)]),
    ('几乎','almost-at-table','A small table faces a curling question breeze beside a ball near the edge: it almost reaches the target, but not quite.', ['table','steam'], [('ball',0,-.94,.54),('first-target',.95,-.88,.49)]),
    ('认真','careful-verification','A recognizing eye inspects a true, checked page beside a focused target: take the details seriously and work carefully.', ['eye','first-check'], [('paper',0,-.94,.70)]),
    ('附近','attached-nearby','A link attaches two neighboring houses while a pin marks their close location: the other house is nearby.', ['first-link','first-pin'], [('house',-.54,-.94,.46),('house',.54,-.94,.46)]),
    ('主要','main-host-desire','A host stands beside the wanted key to a large house: the central needed object is the main one.', ['person','hand'], [('key',.95,.56,.54),('house',0,-.94,.58)]),
    ('遇到','encounter-at-arrival','Two people meet beside an arrival arrow on the same road: coming to the same point creates an encounter.', ['first-group','arrow'], [('road',0,-1.03,1.5)]),
    ('年轻','young-light-year','A calendar stands beside a light feather and a growing child: few years and light movement make young memorable.', ['calendar','feather'], [('child',0,-.94,.66)]),
    ('久','long-running-time','An hourglass stands beside several earlier calendar pages and a clock: imagine waiting through a long time.', ['first-hourglass'], [('calendar',-1.17,-.68,.67),('clock',1.16,-.68,.67)]),
    ('画','draw-a-field','One upper bar frames an open container holding a field picture; a brush turns the enclosed scene into a drawing.', ['bar','frame','field'], [('brush',0,.97,.75)]),
    ('表演','display-performance','A display board faces a performer on a little stage beneath a star: showing the action to an audience becomes a performance.', ['board','dancer'], [('star',0,.98,.70),('first-group',0,-.94,.65)]),
    ('刚才','just-now-talent','A clock points to a freshly earned talent trophy beside a still-warm work page: the event happened just now.', ['clock','first-trophy'], [('paper',0,-.94,.65)]),
    ('办公室','public-task-room','A task page and public group gather beside a room containing a work table: imagine the shared work chamber as an office.', ['paper','first-group','room'], [('table',0,-.94,.78)]),
    ('环境','ringed-surroundings','A ring and a boundary frame collect a home, tree and water: notice the surroundings of the home as its environment.', [('zero',-.97,.05,1.80),('frame',.97,.05,1.58)], [('tree',-.97,.88,.36),('house',-.97,-.15,.57),('water',.97,-.32,.76),('leaf',.97,.65,.50)]),
]


def _object(spec, index, count, p):
    if isinstance(spec, str):
        if count == 1:
            x, scale = 0, 1.45
        elif count == 2:
            x, scale = (-.97,.97)[index], 1.13
        elif count == 3:
            x, scale = (-1.40,0,1.40)[index], .85
        elif count == 4:
            x, scale = (-1.62,-.54,.54,1.62)[index], .70
        else:
            raise ValueError('Unexpected first-batch part count')
        return p(spec,x,.03,scale)
    kind,x,y,scale,*rest=spec
    rotation=rest[0] if rest else 0
    z=rest[1] if len(rest)>1 else 0
    return p(kind,x,y,scale,rotation=rotation,z=z)


def register(add, p):
    path=Path(__file__).resolve().parents[2]/'public/data/lessons.json'
    lessons={lesson['word']:lesson for lesson in json.loads(path.read_text())}
    for word,slug,story,parts,extras in ROWS:
        lesson=lessons[word]
        glyphs=[item['glyph'] for item in lesson['memoryElements']]
        if len(parts)!=len(glyphs):
            raise ValueError('First-batch part mismatch: '+word)
        add(word,'complete-first-'+slug,story,glyphs,
            [_object(spec,i,len(parts),p) for i,spec in enumerate(parts)],
            [_object(spec,0,1,p) for spec in extras])
