"""Explicit, editable compositions for the expanded Blender collection.

One recipe per word: ordered labeled objects, supporting objects, spatial
relationships and a scene-specific story. This is not a fallback that admits
every vocabulary entry. Unlisted words remain in the production queue.
Positions use viewer X/Y/Z; the last two optional values are scale and rotation.
This module is deliberately importable without Blender for validation.
"""
import hashlib
import json
from pathlib import Path

RECIPES = {}


def source_revision(name):
    """A changed recipe or prop library invalidates only generated expansion assets."""
    here=Path(__file__).resolve().parent
    return {'recipeSha256':hashlib.sha256(json.dumps(RECIPES[name],ensure_ascii=False,sort_keys=True).encode()).hexdigest(),
            'sourceSha256':{file:hashlib.sha256((here/file).read_bytes()).hexdigest()
                            for file in ('explanation_props.py','explanation_scenes.py')}}


def obj(kind, x=0, y=0, scale=1, z=0, rotation=0):
    return {'prop':kind, 'position':[x,y,z], 'scale':scale, 'rotation':rotation}


def add(word, name, story, glyphs, parts, extras=()):
    if name in RECIPES or any(r['word']==word for r in RECIPES.values()):
        raise ValueError('Duplicate explanation: '+word)
    if len(glyphs)!=len(parts):
        raise ValueError('Every written part needs its own object: '+word)
    RECIPES[name]={'word':word,'story':story,'glyphs':list(glyphs),
                   'parts':list(parts),'extras':list(extras)}


p=obj

# Concrete nature and everyday objects. Supporting objects show the result or
# action described by the mnemonic, while the labeled objects preserve order.
add('书','book','A bound stack of pages becomes a book; follow its spine and cover as you recall 书.',['书'],[p('book',0,0,1.8)])
add('门','doorway','Two posts and a lintel frame a door standing open, ready for you to enter.',['门'],[p('door',0,0,1.65)])
add('鸟','bird','A bird balances on two feet, with a pointed beak, a folded wing and a tail.',['鸟'],[p('bird',0,0,2)])
add('马','horse','The horse stretches its long body between four legs; its mane and tail complete the picture.',['马'],[p('horse',0,0,1.9)])
add('伞','umbrella','A broad canopy spreads over one hooked handle: open your umbrella before the rain arrives.',['伞'],[p('umbrella',0,0,2)])
add('春','spring','A warm sun rises over fresh shoots and flowers: new growth announces spring.',['春'],[p('sprout',0,-.45,1.6)],[p('sun',.95,.85,.8),p('flower',-1,-.40,1.1),p('grass',.90,-.85,1.1)])
add('辣','chili','A bright red chili curves to a sharp tip; one bite reminds you of the heat of spicy food.',['辣'],[p('pepper',0,0,2)])
add('酸','sour','Picture a tart yellow lemon: the imagined taste helps you recall sour.',['酸'],[p('lemon',0,0,1.9)],[p('plate',0,-.75,1.5)])
add('盐','salt','White crystals spill from a little container onto a plate: a pinch of salt.',['盐'],[p('salt',0,-.30,2.2)],[p('plate',0,-.90,2),p('bottle',-1.25,.1,.8)])
add('长','long','A ribbon of silk stretches far across the island: follow its length to remember long.',['长'],[p('silk',0,0,2.7)])
add('白','white','A clean white sheet catches the sunlight; its pale surface is your cue for white.',['白'],[p('paper',0,0,1.8)],[p('sun',1.4,1.15,.6)])
add('黄','yellow','Golden grain and a ripe yellow fruit gather on a plate: hold that yellow color in mind.',['黄'],[p('fruit',0,-.10,1.6)],[p('wheat',-.95,0,1.1),p('plate',0,-.90,1.9)])
add('黑','black','A blackened cooking board sits over fire: imagine soot darkening it until it is black.',['黑'],[p('blackboard',0,.25,1.5)],[p('flame',0,-.85,.65)])
add('云','cloud','Two bars press a curled cocoon; imagine it puffing upward into a soft white cloud.',['二','厶'],[p('bar',-.70,-.40,.8),p('coil',.70,-.25,.8)],[p('bar',-.70,-.68,.8),p('cloud',0,.85,1.6)])
add('日','day-sun','Imagine a mouth-shaped frame enclosing one bright band of sunlight: another day begins.',['口','一'],[p('mouth',-.95,-.10,1.2),p('bar',.85,-.1,.8)],[p('sun',0,.85,1.05)])
add('草','early-grass','Grass reaches toward an early rising sun; fresh green blades greet the morning.',['艹','早'],[p('grass',-.65,-.65,1.6),p('sun',.85,.60,1.1)],[p('grass',.85,-.75,1.1)])
add('花','flower-change','A patch of grass changes into an open flower: follow the arrow from green blades to petals.',['艹','化'],[p('grass',-1,-.50,1.35),p('arrow',.1,-.2,.55)],[p('flower',1.1,0,1.5)])
add('树','facing-tree','A tree faces its own image in a mirror: the reflection helps you remember the facing part of 树.',['木','对'],[p('tree',-.95,-.15,1.3),p('mirror',.95,-.05,1.5)])
add('秋','autumn-grain','Ripe grain glows beside fire; their shared golden color brings autumn to mind.',['禾','火'],[p('wheat',-.85,-.05,1.6),p('flame',.85,-.05,1.4)])
add('冬','winter-walk','Footsteps lead back past two pieces of ice: feel the cold of winter on the walk home.',['夂','⺀'],[p('footprints',-.80,-.65,1.1),p('ice',.60,-.35,.65)],[p('ice',1.2,.25,.50),p('arrow',-.7,.45,.7,rotation=3.14159)])
add('家','pig-home','A pig rests beneath a protective roof: this imagined shelter is its home.',['宀','豕'],[p('roof',0,.65,1.8),p('pig',0,-.45,1.4)])
add('灯','fire-lamp','A small flame balances above a nail-shaped stand and lights up as a lamp.',['火','丁'],[p('flame',0,.60,.85),p('nail',0,-.45,1.4)],[p('plate',0,-1.25,1)])
add('桥','tree-bridge','Wood from a tree follows a tall arch across water, becoming a bridge.',['木','乔'],[p('tree',-1.3,-.20,1),p('bridge',.50,-.35,1.6)],[p('water',.55,-.75,1.6)])
add('地球','earth-ball','Patches of ground wrap around a round blue ball: picture the Earth with land and oceans.',['地','球'],[p('earth',-1.2,-.50,.85),p('globe',.65,.05,1.7)])
add('海洋','ocean','Two stretches of blue water meet without a dividing shore: together they suggest the ocean.',['海','洋'],[p('water',-.9,-.1,1.4),p('water',.90,-.1,1.4)],[p('boat',.45,.3,.60),p('fish',-1,.25,.65)])
add('空气','air','An empty frame reveals curling air passing through it; the movement makes invisible air imaginable.',['空','气'],[p('frame',-.50,0,1.4),p('steam',.45,0,1.6)])
add('森林','deep-forest','Three trees crowd beside a pair of trees; forest and woods join into a dense forest.',['森','林'],[p('tree',-1.05,-.1,1.25),p('tree',1.05,-.1,1.25)],[p('tree',-.45,-.25,.9,z=-.65),p('tree',-1.6,-.3,.9,z=-.65),p('tree',1.6,-.30,.9,z=-.65)])
add('花园','flower-garden','Flowers bloom inside a small enclosed garden, turning its planted beds into a flower garden.',['花','园'],[p('flower',-.55,-.05,1.4),p('field',.4,-.75,1.5)],[p('flower',.8,-.25,1),p('frame',0,-.6,1.5,rotation=1.5708)])
add('公园','public-park','People gather among garden plants: this shared green place is a public park.',['公','园'],[p('person',-1,-.30,.85),p('tree',.65,-.05,1.4)],[p('flower',1.4,-.6,.7),p('child',-.30,-.58,.55)])
add('月亮','bright-moon','The moon borrows a glowing lamp; imagine their combined light shining through the night.',['月','亮'],[p('moon',-.75,.35,1.4),p('lamp',.85,-.35,1.35)])
add('太阳','blazing-sun','A little sun swells into an oversized sun: imagine too much sunlight filling the sky.',['太','阳'],[p('sun',-.95,-.2,.65),p('sun',.75,.20,1.6)],[p('arrow',-.3,-.70,.60)])
add('今天','today-clock','A clock hangs beneath a cloud: the time is now, under this sky, today.',['今','天'],[p('clock',-.60,-.25,1.2),p('cloud',.50,.75,1.4)])
add('明天','tomorrow-sky','Sun and moon brighten the sky above a fresh calendar page: imagine turning it to tomorrow.',['明','天'],[p('sun',-.9,.5,.9),p('cloud',.9,.65,1.1)],[p('moon',-.25,.7,.55),p('calendar',.30,-.60,1.2)])
add('昨天','yesterday-page','A backward arrow points across a calendar beneath the sky: turn back one day to yesterday.',['昨','天'],[p('calendar',-.65,-.25,1.2),p('cloud',.85,.6,1.15)],[p('arrow',-.9,.7,.65,rotation=3.14159)])
add('明白','bright-understanding','Sunlight falls on a white page; imagine its message becoming bright and clear as you understand.',['明','白'],[p('sun',-.85,.6,1),p('paper',.55,-.35,1.4)],[p('moon',-1.45,-.20,.55)])
add('下雨','falling-rain','A downward arrow follows raindrops from a cloud toward an open umbrella: rain is falling.',['下','雨'],[p('arrow',-1.2,.40,.85,rotation=-1.5708),p('rain',.35,.75,1.4)],[p('umbrella',.40,-.75,.9)])

# Food and drinks.
add('水果','water-fruit','Water gathers beside ripe fruit; imagine the splash filling the fruit with juice.',['水','果'],[p('water',-.80,-.45,1.25),p('fruit',.80,-.05,1.55)])
add('苹果','apple-fruit','Pick a red fruit from the apple tree: the apple waits just below its leafy branch.',['苹','果'],[p('tree',-.80,0,1.4),p('apple',.85,-.3,1.4)],[p('apple',-.95,.46,.36,z=.36)])
add('葡萄','grape-harvest','Grapes hang from a vine above a basket; lower the bunch into the basket at harvest time.',['葡','萄'],[p('grapes',-.65,.40,1.35),p('basket',.65,-.60,1.3)],[p('leaf',-1.0,1.10,.55)])
add('香蕉','fragrant-banana','Curling fragrance rises from a ripe bunch of bananas: remember their smell and curved shape together.',['香','蕉'],[p('steam',-.65,.65,1),p('banana',.45,-.35,1.7)])
add('西瓜','west-melon','A west-pointing arrow faces the setting sun beside a striped melon: imagine a watermelon cooling at sunset.',['西','瓜'],[p('arrow',-.90,.15,.9,rotation=3.14159),p('melon',.85,-.25,1.6)],[p('sun',-1.45,-.55,.65)])
add('牛奶','cow-milk','A cow stands beside a bottle of fresh milk: cow plus milk gives you cow’s milk.',['牛','奶'],[p('cow',-.8,-.2,1.3),p('milk',1.0,-.25,1.4)])
add('羊肉','lamb-counter','A sheep beside a cut of meat on a plate marks its source: mutton or lamb.',['羊','肉'],[p('sheep',-.85,0,1.25),p('food-meat',.95,-.35,.9)],[p('plate',.95,-.50,1.2)])
add('鸡蛋','chicken-egg','A hen watches over a pale egg in a nest-like basket: connect chicken with egg.',['鸡','蛋'],[p('chicken',-.85,-.10,1.35),p('egg',.90,-.05,1.2)],[p('basket',.90,-.50,1.0)])
add('米饭','rice-bowl','Loose rice grains spill toward a filled bowl: the grains become a cooked rice meal.',['米','饭'],[p('rice',-1,-.45,1.5),p('bowl',.65,-.35,1.65)],[p('rice',.65,-.10,1.6),p('steam',.65,.85,.85)])
add('面包','bread-package','A smiling face appears beside a loaf tucked into a package: imagine unwrapping face-shaped bread.',['面','包'],[p('face',-.90,.4,.75),p('bag',.75,-.35,1.45)],[p('bread',.7,.25,1.2)])
add('面条','noodle-strips','Imagine a dough face stretching into strips; the strips curl into a bowl of noodles.',['面','条'],[p('face',-.95,.4,.75),p('noodles',.60,-.35,1.65)],[p('chopsticks',.95,.65,.8,rotation=-.30)])
add('果汁','fruit-juice','A ripe fruit sits above a waiting cup: imagine squeezing its juice into the cup.',['果','汁'],[p('fruit',-.60,.55,1),p('cup',.65,-.45,1.5)],[p('water',-.45,-.55,.75)])
add('咖啡','coffee-cup','One mouth asks for coffee; the other refuses anything else. Both guard the same steaming cup.',['咖','啡'],[p('mouth',-.95,.6,.8),p('mouth',.95,.6,.8)],[p('cup',0,-.55,1.6),p('steam',0,.6,.85),p('bar',1.0,.6,.45,rotation=.8,z=.15)])
add('啤酒','beer-mug','A mug waits beside a bottle; imagine the bottle pouring beer into the mug.',['啤','酒'],[p('cup',-.80,-.2,1.5),p('bottle',.85,-.05,1.45)])
add('茶','tea-leaves','A person gathers green leaves beneath a tree and sets them beside a cup for brewing tea.',['艹','人','木'],[p('leaf',-1.5,-.60,.70),p('person',-.30,-.35,.85),p('tree',1.10,.10,1.35)],[p('cup',-1.25,.0,.70)])
add('甜','sweet-taste','A tongue reaches toward a wrapped sweet: imagine the sweet taste on your tongue.',['舌','甘'],[p('tongue',-.85,.05,1.45),p('candy',.85,.05,1.55)])
add('糖','rice-candy','Rice arrives at a palace-like house and emerges as candy: a sweet transformation to remember sugar.',['米','唐'],[p('rice',-1.2,-.6,1.3),p('house',.70,.05,1.25)],[p('candy',-.55,.40,1)])
add('吃','eating','An open mouth asks for food; a begging question bubble hovers above one waiting rice bowl.',['口','乞'],[p('mouth',-.85,.05,1.35),p('question',.85,.75,1.05)],[p('bowl',.70,-.65,1.3),p('rice',.70,-.42,1.2)])
add('喝','drinking','A mouth keeps asking why until a full cup arrives: remember the moment of taking a drink.',['口','曷'],[p('mouth',-.85,.1,1.35),p('question',.85,.75,1.05)],[p('cup',.60,-.55,1.3)])

# Furniture, clothing and practical objects.
add('桌子','child-table','A child stands at a broad wooden table, ready to spread out a book and work.',['桌','子'],[p('table',.30,-.40,1.7),p('child',-1.25,-.25,.90)],[p('book',.55,.18,.50,rotation=-1.5708)])
add('椅子','child-chair','A child sits on a wooden chair; its back and four legs make the seat easy to remember.',['椅','子'],[p('chair',.55,-.35,1.65),p('sitter',.55,.14,.72,z=.35)])
add('杯子','child-cup','A child carries a large handled cup: picture the child beside the cup before recalling 杯子.',['杯','子'],[p('cup',.65,-.2,1.6),p('child',-1,-.25,1)])
add('盘子','child-plate','A child sets a tiny toy boat on a broad plate and imagines docking it there.',['盘','子'],[p('plate',.55,-.55,1.8),p('child',-1.20,-.25,.95)],[p('boat',.55,-.17,.50)])
add('筷子','child-chopsticks','A child holds two long chopsticks above a bowl of noodles, ready to eat.',['筷','子'],[p('chopsticks',.70,.30,1.35,rotation=-.25),p('child',-1,-.20,1)],[p('noodles',.70,-.80,1.2)])
add('帽子','child-hat','A broad hat rests on a child’s head: the child makes the hat’s purpose immediately visible.',['帽','子'],[p('hat',0,.86,1.1),p('child',0,-.30,1.35)])
add('裤子','child-trousers','A child stands next to a pair of long trousers: imagine stepping one leg into each side.',['裤','子'],[p('pants',.85,-.05,1.65),p('child',-.95,-.20,1.15)])
add('裙子','child-skirt','A child stands beside a flaring skirt, ready to twirl its wide hem.',['裙','子'],[p('skirt',.85,-.10,1.7),p('girl',-.95,-.20,1.1)])
add('袜子','child-socks','A child finds two warm socks waiting together: one for each foot.',['袜','子'],[p('sock',.70,0,1.25),p('child',-1,-.2,1.1)],[p('sock',1.30,-.28,.95)])
add('衣服','wardrobe','A shirt and a pair of trousers hang together: clothes to put on before going out.',['衣','服'],[p('shirt',-.85,.10,1.35),p('pants',.85,-.05,1.35)])
add('衬衫','lined-shirt','A pale cloth lining sits beside a blue shirt: imagine stitching the lining inside to finish the shirt.',['衬','衫'],[p('lining',-.9,-.05,1.4),p('shirt',.75,.05,1.55)])
add('包','wrapped-coil','A bag wraps around a curled green snake: imagine carefully enclosing the coil in a package.',['勹','巳'],[p('bag',0,-.10,1.7),p('coil',0,-.15,1.05,z=.34)])
add('行李箱','travel-suitcase','A traveler’s footsteps lead past a plum packed beside a wheeled box: imagine taking the plum in your suitcase.',['行','李','箱'],[p('footprints',-1.35,-.85,.70),p('plum',-.30,-.15,1.1),p('suitcase',1.10,-.05,1.3)])
add('黑板','school-blackboard','A dark slate surface covers a wooden board, making a blackboard for the next lesson.',['黑','板'],[p('blackboard',-.40,.05,1.7),p('board',1.10,-.2,.80)],[p('pencil',.3,-1.0,.60,rotation=1.5708)])
add('铅笔','writing-pencil','A lead-colored writing point takes the place of a brush: use this pencil for your next line.',['铅','笔'],[p('pencil',-.80,0,1.7),p('brush',.85,0,1.5)],[p('paper',0,-.65,.70)])
add('眼镜','eye-glasses','An eye looks through two polished mirror-like lenses; imagine the pair as eyeglasses.',['眼','镜'],[p('eye',-1,.05,1.2),p('mirror',.50,.0,.90)],[p('mirror',1.35,0,.9),p('bar',.93,0,.28)])
add('冰箱','ice-box','Blocks of ice fill a cupboard-like box: imagine it keeping food cold as a refrigerator.',['冰','箱'],[p('ice',-.9,.10,1.2),p('shelf',.85,0,1.45)],[p('milk',.63,-.36,.45),p('apple',1.11,.32,.45)])
add('钥匙','lock-key','A spoon lies beside a lock; imagine reshaping its handle into the toothed key resting below.',['钥','匙'],[p('lock',-.8,.05,1.55),p('spoon',.85,.25,1.15)],[p('key',.75,-.75,.95)])
add('信封','letter-envelope','A trusted message, marked with a heart, rests beside a sealed envelope: tuck it inside before sending it.',['信','封'],[p('paper',-.80,.10,1.2),p('envelope',.75,-.10,1.5)],[p('heart',-.80,.1,.35,z=.12)])
add('日记','daily-diary','A small sun marks a day beside an openable notebook: record a memory of that day in a diary.',['日','记'],[p('sun',-.90,.45,1),p('book',.65,-.15,1.5)],[p('pencil',1.45,-.1,.70)])
add('叶子','little-leaf','A child holds a large green leaf; its central vein and branching sides stand out clearly.',['叶','子'],[p('leaf',.70,.05,1.7),p('child',-1,-.25,1.1)])
add('房间','room-between','A little room stands beside the space between a pair of doorposts: picture the room beyond that opening.',['房','间'],[p('house',-.85,0,1.1),p('door',.90,-.05,1.2)])
add('厨房','cooking-room','A steaming cooking pot sits beside a room: put the cooking place inside and you have a kitchen.',['厨','房'],[p('pot',-.85,-.40,1.35),p('house',.85,0,1.15)],[p('steam',-.85,.65,.85)])
add('客厅','guest-room','A visitor arrives beside a sofa and doorway: the room is ready to receive a guest.',['客','厅'],[p('person',-1.20,-.25,1),p('sofa',.55,-.50,1.5)],[p('door',1.35,.30,.85,z=-.6)])
add('沙发','sand-sofa','Imagine a sofa rising from a sandy patch; an outward arrow helps recall the send-out sound cue in this loanword.',['沙','发'],[p('earth',-.95,-.65,1),p('arrow',.95,.75,.65)],[p('sofa',.35,-.20,1.6)])

# Visible bodies and animals with explicitly mnemonic component links.
add('口','framed-mouth','An open frame closes with one lower bar: imagine the enclosure becoming a mouth.',['冂','一'],[p('gate',-.80,.0,1.1),p('bar',.90,-.40,.8)],[p('mouth',.90,.35,.9)])
add('看','shaded-eye','A hand shades an eye from the sun so it can look into the distance.',['手','目'],[p('hand',-.6,.6,1.25,rotation=-1.5708),p('eye',.40,-.10,1.5)])
add('听','listen-knock','An axe taps near a mouth-shaped opening; imagine listening carefully to the knock.',['口','斤'],[p('mouth',-.85,.1,1.4),p('axe',.85,.1,1.5)])
add('眼睛','green-eyes','One open eye reflects a green pupil in another: picture the pair looking back at you.',['眼','睛'],[p('eye',-.85,0,1.3),p('eye',.85,0,1.3)])
add('耳朵','ear-blossom','An ear opens beside a flower; imagine it unfolding like a blossom to catch every sound.',['耳','朵'],[p('ear',-.8,.05,1.65),p('flower',.8,.05,1.45)])
add('鼻子','child-nose','A child leans toward an oversized nose and a fragrant flower: picture taking a deep sniff.',['鼻','子'],[p('nose',.60,.15,1.7),p('child',-1.05,-.25,1.1)],[p('flower',1.35,-.45,.7)])
add('头发','growing-hair','A head grows strands of hair; an outward arrow pictures the hair being sent out from the scalp.',['头','发'],[p('hair',-.40,-.10,1.9),p('arrow',1.10,.65,.8,rotation=.8)])
add('脚','moon-foot','A moon seems to step backward on a little foot: imagine its retreat to remember this body-part mnemonic.',['⺼','却'],[p('moon',-.75,.40,1.2),p('arrow',.8,.20,.8,rotation=3.14159)],[p('foot',-.55,-.75,.8)])
add('腿','moon-legs','A moon retreats on long legs; follow the backward arrow and notice each leg moving.',['⺼','退'],[p('moon',-.60,.60,1.25),p('arrow',.95,.30,.8,rotation=3.14159)],[p('leg',-.85,-.70,.9),p('leg',-.25,-.70,.9)])
add('双','pair-hands','Two hands reach toward one another, making a matching pair.',['又','又'],[p('hand',-.65,0,1.5),p('hand',.65,0,1.5)])
add('猫','cat-seedlings','An animal prowls beside fresh seedlings; pointed ears, whisker-like cheeks and a curled tail reveal a cat.',['犭','苗'],[p('cat',-.55,-.2,1.5),p('sprout',1,.0,1.4)])
add('狗','talking-dog','An animal speaks a full sentence in a speech bubble: the talking dog wants your attention.',['犭','句'],[p('dog',-.40,-.40,1.5),p('speech',.80,.65,1.25)])
add('熊猫','bear-cat','A round panda-like bear sits beside a playful cat: combine the bear and cat cues to remember panda.',['熊','猫'],[p('panda',-.80,-.1,1.4),p('cat',.95,-.25,1.0)])
add('老虎','elder-tiger','An elder stands at a respectful distance from a striped tiger: old plus tiger helps you recall 老虎.',['老','虎'],[p('elder',-1.2,-.20,.95),p('tiger',.60,-.20,1.6)])
add('蝴蝶','paired-butterflies','A bearded butterfly meets a leaf-winged butterfly: their beard and leaf cues help recall the two syllables.',['蝴','蝶'],[p('butterfly',-.90,.1,1.25),p('butterfly',.90,.1,1.25)],[p('fur',-.9,-.32,.4,z=.18),p('leaf',1.28,.25,.5,z=.15)])

# People, family and social scenes.
add('坐','sitting-together','Two people lower themselves onto the earth and sit side by side.',['人','人','土'],[p('sitter',-.85,-.15,1.05),p('sitter',.85,-.15,1.05),p('earth',0,-.95,1.9)])
add('住','living-with-host','A traveler meets the host beside a house: this is the place where the traveler will live.',['亻','主'],[p('walker',-1.1,-.30,.90),p('person',.90,-.25,.95)],[p('house',0,.30,.90,z=-.65)])
add('女人','woman-person','A woman stands beside another person; identify the woman in the pair to recall 女人.',['女','人'],[p('woman',-.75,-.15,1.3),p('person',.85,-.30,1.05)])
add('男人','man-person','A man stands beside another person; the pair keeps man and person together in your memory.',['男','人'],[p('man',-.80,-.1,1.3),p('person',.85,-.30,1.05)])
add('孩子','children','Two children gather beside a toy ball: both written parts lead you back to the idea of a child.',['孩','子'],[p('child',-.75,-.30,1),p('girl',.75,-.30,1)],[p('ball',0,-.85,.45)])
add('儿子','young-son','A pair of small legs leads to a child waiting nearby: picture a young son running to his family.',['儿','子'],[p('leg',-.90,-.35,1),p('boy',.75,-.1,1.25)],[p('leg',-1.3,-.35,1)])
add('女儿','young-daughter','A woman welcomes a small child; the little legs are the cue that completes daughter.',['女','儿'],[p('woman',-.70,-.05,1.35),p('girl',.75,-.55,.75)])
add('妈妈','mother-call','Two mother figures stand together: repeat the mother cue as a child calls Mama.',['妈','妈'],[p('woman',-.85,-.1,1.3),p('woman',.85,-.1,1.3)],[p('child',0,-.70,.55,z=.35)])
add('爸爸','father-call','Two father figures turn toward a child: repeat the father cue as the child calls Baba.',['爸','爸'],[p('man',-.85,-.1,1.3),p('man',.85,-.1,1.3)],[p('child',0,-.70,.55,z=.35)])
add('姐姐','older-sisters','Two older sisters stand beside a smaller child, ready to help her reach a book.',['姐','姐'],[p('girl',-.85,-.15,1.25),p('girl',.85,-.15,1.25)],[p('child',0,-.75,.55,z=.35),p('book',0,.65,.50)])
add('哥哥','older-brothers','Two older brothers stand beside a younger child: the taller pair are the older brothers.',['哥','哥'],[p('boy',-.85,-.15,1.3),p('boy',.85,-.15,1.3)],[p('child',0,-.75,.55,z=.35)])
add('妹妹','younger-sisters','Two little sisters stand below a taller family member: notice the younger pair.',['妹','妹'],[p('girl',-.85,-.60,.75),p('girl',.85,-.60,.75)],[p('woman',0,.0,1.25,z=-.6)])
add('弟弟','younger-brothers','Two little brothers play beside a taller family member: notice the younger pair.',['弟','弟'],[p('boy',-.85,-.60,.75),p('boy',.85,-.60,.75)],[p('person',0,0,1.25,z=-.6),p('ball',0,-.95,.38,z=.40)])
add('奶奶','grandmother-milk','Two milk bottles wait beside an elder’s chair: imagine your paternal grandmother offering a warm drink.',['奶','奶'],[p('milk',-1.25,-.45,.85),p('milk',1.25,-.45,.85)],[p('elder',0,-.20,1.15)])
add('爷爷','grandfather','Two silver-haired elders greet a child: repeating the grandfather cue recalls paternal grandfather.',['爷','爷'],[p('elder',-.85,-.1,1.25),p('elder',.85,-.1,1.25)],[p('child',0,-.70,.55,z=.4)])

# Counts and spatial relations are shown with actual quantities and positions.
add('一','one','One single bar spans the island; count it once to remember one.',['一'],[p('bar',0,0,2.2)])
add('二','two','One bar rests above another: count the two separate bars.',['一','一'],[p('bar',0,.45,1.7),p('bar',0,-.35,2)])
add('三','three','One upper bar joins the two lower bars: count all three.',['一','二'],[p('bar',0,.7,1.8),p('bar',0,-.05,1.4)],[p('bar',0,-.8,2)])
add('五','five','Five gold beads sit inside a counting frame; count every bead once.',['五'],[p('count-5',0,-.05,2)],[p('frame',0,0,1.65)])
add('八','eight','Eight gold beads form two rows: count five, then three more.',['八'],[p('count-8',0,-.10,2.4)])
add('十','ten','One bar crosses a pole; ten beads sit beside the cross as a counting aid.',['一','丨'],[p('bar',-.65,.35,1.15),p('pole',-.65,.10,1.4)],[p('count-10',1,-.25,1.5)])
add('七','seven','One bar supports a bent hook; seven golden beads hang below the hook.',['一','乚'],[p('bar',0,.90,1.8),p('hook',0,.25,.85)],[p('count-7',0,-.70,1.8)])
add('九','nine','A slanting rod meets a curl; nine gold beads gather underneath as your counting cue.',['丿','乙'],[p('bar',-.85,.45,.7,rotation=.9),p('coil',.75,.45,.8)],[p('count-9',0,-.70,1.9)])
add('四','four','A small child stands inside an enclosure with four corners; count the corners around the child.',['囗','儿'],[p('frame',0,0,1.75),p('child',0,-.15,1)],[p('count-4',0,-1.13,1.6,z=.4)])
add('六','six','A lid shelters two of eight beads; count the six remaining beside it: eight minus two is six.',['亠','八'],[p('lid',-.95,-.30,.70),p('count-6',.65,-.35,1.5)],[p('count-2',-.95,-.65,1,z=-.12)])
add('两','two-travelers','One top bar spans an open frame holding two travelers together: a pair ready to go.',['一','冂','从'],[p('bar',0,1.35,1.7),p('frame',0,0,1.65),p('person',-.42,-.30,.78)],[p('person',.42,-.30,.78)])
add('上','above','A signpost points upward above one ground line; follow it up.',['⺊','一'],[p('arrow',0,.60,1.05,rotation=1.5708),p('bar',0,-.65,2)])
add('下','below','One high bar forms a ceiling; a pointing arrow below it directs your gaze down.',['一','卜'],[p('bar',0,1.0,2),p('arrow',0,-.10,1.2,rotation=-1.5708)])
add('小','tiny-beads','Eight tiny beads gather under a hook: compare their small size with the large hook above.',['亅','八'],[p('hook',0,.45,1.5),p('count-8',0,-.85,1.2)])
add('少','few-beads','A slanting bar separates a few small beads from the rest: only a few remain on this side.',['小','丿'],[p('count-3',-.85,-.40,1.3),p('bar',.35,.0,1.1,rotation=1.1)],[p('count-7',1.2,-.50,.75)])
add('多','many-evenings','One sunset joins another sunset; many evening marks fill the calendar below.',['夕','夕'],[p('sun',-.85,.45,.95),p('sun',.85,.45,.95)],[p('calendar',0,-.75,1.2)])
add('半','half-cow-cake','Imagine a cow-shaped cake marked by two horns; a knife divides it at the middle to make half.',['丷','牛'],[p('horns',-.90,.65,1),p('cow',.5,-.2,1.5)],[p('knife',.4,.65,.8,rotation=-1.5708)])
add('低','low-person','A person bends attention toward the low base beside them; the arrow points down to that base.',['亻','氐'],[p('person',-.75,-.25,1.2),p('earth',.80,-.85,1.1)],[p('arrow',.80,.20,.8,rotation=-1.5708)])
add('短','short-arrow','An arrow shrinks until it is scarcely longer than a bean: a very short arrow.',['矢','豆'],[p('arrow',-.55,.2,.55),p('bean',.55,-.10,1.4)])
add('矮','short-height','A low arrow points toward a drooping plant that fits beneath a chair: keep the height short.',['矢','委'],[p('arrow',-.95,-.55,.65),p('sprout',.55,-.6,.75,rotation=.5)],[p('chair',.55,.05,1.8,z=-.25)])
add('高','high-tower','A lid caps a tower, while a mouth hovers by its high window; look up to its height.',['亠','口','冋'],[p('lid',.4,1.18,1.1),p('mouth',-1,.45,.85),p('tower',.4,-.05,1.3)])
add('中间','middle-gap','A pole stands exactly in the middle of an open doorway: notice the space on both sides.',['中','间'],[p('pole',0,0,1.4,z=.15),p('door',0,0,1.7)])
add('旁边','beside-edge','A person stands beside a flag at the edge of a road: picture the position beside that boundary.',['旁','边'],[p('person',-.85,-.25,1.2),p('flag',.85,-.20,1.25)],[p('road',0,-1.2,1.8)])
add('左右','left-right','Two arrows point away from the center: the left one goes left and the right one goes right.',['左','右'],[p('arrow',-.85,0,1.1,rotation=3.14159),p('arrow',.85,0,1.1)])
add('左边','left-edge','A left-pointing arrow ends at the road’s left edge; the small flag marks that boundary.',['左','边'],[p('arrow',0,.25,1.4,rotation=3.14159),p('flag',-1.5,-.4,.85)],[p('road',0,-.90,1.8)])
add('右边','right-edge','A right-pointing arrow ends at the road’s right edge; the small flag marks that boundary.',['右','边'],[p('arrow',0,.25,1.4),p('flag',1.5,-.4,.85)],[p('road',0,-.90,1.8)])
add('前面','front-face','An arrow leads to a face placed in front of a doorway: the face is on the near side.',['前','面'],[p('arrow',-1.15,-.35,.70),p('face',0,-.15,1.1,z=.95)],[p('door',.25,.10,1.45,z=-.5)])
add('后面','behind-face','A face peeks around the far side of a doorway; follow the route to find it behind.',['后','面'],[p('arrow',-1.15,-.35,.70,rotation=3.14159),p('face',.95,.20,.85,z=-.7)],[p('door',0,0,1.4)])
add('外','outside-at-dusk','At dusk a pointing arrow leads away from the house: follow it outside.',['夕','卜'],[p('sun',-1.15,.8,.75),p('arrow',1,.0,1)],[p('house',-.55,-.35,1)])
add('北方','north-flag','An upward compass arrow points north beside a square flag: mark the northern direction.',['北','方'],[p('arrow',-.80,0,1.3,rotation=1.5708),p('flag',.85,-.05,1.4)])

# Actions, transport, play and learning.
add('问','door-question','A mouth appears in an open doorway and asks a question.',['门','口'],[p('door',0,0,1.7),p('mouth',0,-.10,.85,z=.25)],[p('question',1.20,.85,.75)])
add('回','return-loop','A mouth waits inside an enclosure; imagine it circling the edge and returning to the same spot.',['囗','口'],[p('frame',0,0,1.8),p('mouth',0,-.1,1.1,z=.18)],[p('arrow',1.2,-.80,.65,rotation=3.14159)])
add('开','opening-gate','Two raised hands lift one bar above an open passage: the gate is opening.',['一','廾'],[p('bar',0,1.1,2),p('hand',-.65,.30,1.1)],[p('hand',.65,.30,1.1),p('door',0,-.30,1.35,z=-.40)])
add('关','closing-sky','Imagine two horns pushing a sky-filled doorway shut; the light beyond is about to disappear.',['丷','天'],[p('horns',-.95,.05,1.5),p('cloud',.65,.65,1)],[p('door',.65,-.20,1.2)])
add('出','sprout-out','A sprout grows upward and out of an open container: follow its stem to the exit.',['屮','凵'],[p('sprout',0,.35,1.4),p('bucket',0,-.65,1.55)])
add('进','enter-courtyard','A road leads directly into a well-shaped courtyard opening: follow the path to enter.',['辶','井'],[p('road',-.60,-.85,1.6),p('frame',.65,.0,1.4)])
add('入口','entrance','An inward arrow leads to a mouth-like opening: that opening is the entrance.',['入','口'],[p('arrow',-1,.0,1.0),p('door',.75,-.05,1.5)])
add('走','walking-ground','A foot lifts away from its stopping place on the earth; the footprints show where walking begins.',['土','止'],[p('earth',-.80,-.75,1.4),p('foot',.80,-.10,1.4)],[p('footprints',.20,-.95,1.1)])
add('跑步','running-steps','A striding runner follows a trail of steps around the ground: imagine speeding up into a run.',['跑','步'],[p('walker',-.55,-.05,1.4),p('footprints',.85,-.9,1.25)])
add('散步','scattered-steps','Footprints scatter along a path beside a walker: an easy walk with no hurry.',['散','步'],[p('footprints',-.65,-.90,1.4),p('walker',.65,-.05,1.4)])
add('跳舞','dancing','A jumping arrow rises beside a dancer with spread arms: put jumps and dance steps together.',['跳','舞'],[p('arrow',-.95,.10,1,rotation=1.5708),p('dancer',.60,.05,1.5)],[p('music',1.45,.80,.65)])
add('游泳','swimming','A little touring flag marks the water beside a swimmer: imagine moving through the pool on a tour.',['游','泳'],[p('flag',-1.3,.10,.85),p('person',.35,-.15,1.0,rotation=-1.5708)],[p('water',.10,-.60,2.4)])
add('学习','learning-wings','A child studies a book beside a practice feather: imagine learning how a wing works through practice.',['学','习'],[p('book',-.75,-.10,1.3),p('feather',.95,.10,1.4)],[p('child',-1.45,-.50,.75)])
add('读','reading-aloud','A speech bubble rises above a book on a seller’s table: buy the book and read it aloud.',['讠','卖'],[p('speech',-.80,.60,1.15),p('table',.65,-.65,1.3)],[p('book',.65,-.05,.75),p('coins',1.25,-.35,.45)])
add('写','writing-gift','A cover shelters a wrapped gift; a pencil waits nearby to write the recipient’s name.',['冖','与'],[p('lid',0,.9,1.6),p('bag',0,-.10,1.2)],[p('pencil',1.1,-.10,1.1),p('paper',-.95,-.30,.7)])
add('说话','talking','Two speech bubbles face one another, passing a conversation back and forth.',['说','话'],[p('speech',-.85,.25,1.35),p('speech',.85,-.15,1.35)])
add('唱歌','singing','An open mouth sends out musical notes: voice and song become singing.',['唱','歌'],[p('mouth',-.85,0,1.5),p('music',.85,.20,1.6)])
add('休息','rest-breath','A person rests beside a tree while gentle breath curls upward: slow down and take a break.',['休','息'],[p('sitter',-.60,-.5,.95),p('steam',1,.2,1.2)],[p('tree',-.85,.3,1.4,z=-.5)])
add('睡觉','sleep-notice','A bed waits beneath a moon; an eye notices the pillow and imagines closing for sleep.',['睡','觉'],[p('bed',-.35,-.5,1.6),p('eye',.85,.65,.95)],[p('moon',-1.1,.9,.75)])
add('起床','rising-bed','An upward arrow rises beside a bed: leave the pillow behind and get out of bed.',['起','床'],[p('arrow',-.95,.55,.95,rotation=1.5708),p('bed',.35,-.50,1.65)])
add('飞机','flying-machine','A feather-like wing joins a machine gear; above them a small airplane takes flight.',['飞','机'],[p('feather',-1,-.45,.95),p('gear',1,-.45,.95)],[p('plane',0,.65,1.7)])
add('自行车','self-powered-bicycle','A rider supplies the steps that move this vehicle: your own effort powers a bicycle.',['自','行','车'],[p('person',-1.25,-.2,.95),p('footprints',-.15,-.95,.75),p('bicycle',.65,-.05,1.55)])
add('火车站','steam-train-station','Fire powers a train toward a waiting platform and doorway: the vehicle stops at the station.',['火','车','站'],[p('flame',-1.55,-.15,.7),p('train',-.25,-.45,1.15),p('door',1.25,.20,1.15)])
add('电视','electric-view','An electric bolt powers a screen with an eye on it: electricity lets you view television.',['电','视'],[p('lightning',-1.15,.10,1),p('screen',.50,-.15,1.55)],[p('eye',.50,-.05,.50,z=.18)])
add('手表','wrist-display','A hand holds a small clock face where its wrist meets the sleeve: a watch displays the time.',['手','表'],[p('hand',-.25,.30,1.6),p('clock',-.25,-.55,.7,z=.18)])
add('时间','time-gap','A clock sits in the gap between two doorposts: picture time passing through that opening.',['时','间'],[p('clock',0,.05,1.2,z=.2),p('door',0,.05,1.75)])
add('小时','small-hour','A tiny clock sits beside a larger clock face: picture one small portion of the day, an hour.',['小','时'],[p('clock',-1,-.30,.60),p('clock',.65,.05,1.65)])
add('分钟','divided-minute','A dividing knife approaches a clock face: imagine slicing its hour into sixty minutes.',['分','钟'],[p('knife',-.9,.2,1.2,rotation=-1.0),p('clock',.65,0,1.65)])
add('踢足球','kicking-football','A kicking foot sends a ball forward; the footprints help you remember the foot in football.',['踢','足','球'],[p('leg',-1.20,.15,1.15,rotation=.8),p('footprints',-.70,-.85,.85),p('ball',1,-.35,1.05)])
add('打篮球','basketball','A hand sends a ball toward a raised basket: picture the shot dropping inside.',['打','篮','球'],[p('hand',-1.40,.15,1.05),p('basket',1,.30,1.3),p('ball',.15,.85,.80)])
add('网球','tennis','A ball crosses a taut net with a racket waiting nearby: picture a tennis rally.',['网','球'],[p('net',-.25,-.10,1.8),p('ball',1,.65,.65)],[p('racket',-1.3,.10,1)])
add('乒乓球','table-tennis','Two small paddles face each other across a table, sending one little ball back and forth.',['乒','乓','球'],[p('racket',-1.15,.40,.65),p('racket',1.15,.40,.65),p('ball',.20,.70,.28)],[p('table',0,-.65,1.8),p('net',0,-.03,.7)])
add('羽毛球','shuttlecock','A feather and a soft patch of fur flank a cork ball with feather ribs: imagine this soft feathered shuttlecock flying.',['羽','毛','球'],[p('feather',-1.2,.15,1.05),p('fur',-.4,.25,.75),p('shuttle',.9,-.05,1.65)])
add('爬山','climbing-mountain','An upward path points past a walker toward a mountain peak: imagine climbing the mountain.',['爬','山'],[p('walker',-1.25,-.40,.9),p('mountain',.55,-.10,1.6)],[p('arrow',-.6,.70,.75,rotation=1.05)])
add('洗澡','washing-bath','Water pours toward a bath-like basin while a bather waits beside it: time for a bath.',['洗','澡'],[p('water',-.95,-.55,1.25),p('bowl',.65,-.45,1.8)],[p('person',.7,.10,.65)])
add('冷','cold-order','Ice blocks gather beneath a commanding flag: imagine an order that fills the room with cold.',['冫','令'],[p('ice',-.85,-.40,1.25),p('flag',.85,.05,1.4)],[p('ice',-.30,.25,.65)])
add('热','hot-hand','A hand hovers above small flames; imagine the heat making it pull away.',['执','灬'],[p('hand',0,.55,1.4),p('flame',-.6,-.70,.75)],[p('flame',.60,-.70,.75)])
add('温度','temperature','Heat rises beside a marked measuring pole: compare the warmth with a scale of degrees.',['温','度'],[p('steam',-.75,.0,1.5),p('pole',.70,0,1.7)],[p('bar',.93,-.70,.25),p('bar',.93,-.20,.25),p('bar',.93,.30,.25),p('bar',.93,.80,.25)])
add('红','red-silk','Red silk lies beside a worker’s tools: imagine the work of dyeing the silk red.',['纟','工'],[p('silk',-.6,.10,1.6),p('axe',1,-.10,1.1)])
add('绿','leaf-green-silk','Silk lies beside a page recording a leaf’s color: imagine that recorded green spreading into the threads.',['纟','录'],[p('green-silk',-.80,-.10,1.3),p('paper',.80,0,1.2)],[p('leaf',.80,.03,.7,z=.12)])
add('蓝','blue-supervisor','Grass grows beside a blue-clothed supervisor: imagine the grass painting the uniform blue.',['艹','监'],[p('grass',-.80,-.60,1.5),p('person',.80,-.05,1.45)])

# A second batch reuses the same visual vocabulary in new relationships.
add('刀','knife','A broad metal blade meets a wooden handle: picture a small kitchen knife.',['刀'],[p('knife',0,0,2.2)])
add('页','page','One sheet carries a few written lines: turn this single page in your mind.',['页'],[p('paper',0,0,1.9)])
add('毛','fur','Fine strands rise from a small patch of fur: notice each hair in the soft surface.',['毛'],[p('fur',0,0,2)])
add('猪','storytelling-pig','An animal tells its story through a speech bubble; its curly tail and pink snout identify the pig.',['犭','者'],[p('pig',-.5,-.35,1.6),p('speech',.80,.65,1.2)])
add('火','horns-fire','Two horn-like tips rise above a person-shaped spark: imagine the outline swelling into a flame.',['丷','人'],[p('horns',-.95,.50,1),p('person',.95,-.15,1)],[p('flame',0,.10,1.1)])
add('血','blood-dish','A slanting red mark leads to a dish with a small red drop: picture blood collected in the dish.',['丿','皿'],[p('bar',-.85,.40,.8,rotation=1.0),p('plate',.65,-.45,1.5)],[p('food-meat',.65,-.25,.35)])
add('里','inside-field','A planted field rests inside a surrounding patch of earth: look within its boundary to remember inside.',['田','土'],[p('field',0,-.30,1.25),p('earth',0,-.75,2.1)])
add('内','person-within','A person stands within an open frame: notice the space inside its boundaries.',['冂','人'],[p('gate',0,0,1.8),p('person',0,-.25,1.05)])
add('空','empty-work','An empty frame waits beside a worker’s axe: imagine the work finished and the space left empty.',['穴','工'],[p('frame',-.60,0,1.55),p('axe',1,-.15,1.25)])
add('困','sleepy-tree','A tree stands inside a tight enclosure; imagine growing sleepy while resting in that enclosed shade.',['囗','木'],[p('frame',0,0,1.9),p('tree',0,-.15,1.2)])
add('梦','forest-dream','Two trees fade beneath a low evening sun: picture the woods appearing in a dream at dusk.',['林','夕'],[p('tree',-.95,-.25,1.2),p('sun',1.05,.70,.85)],[p('tree',.10,-.35,1.1)])
add('近','near-axe','An axe stands right beside the end of a short road: it is near enough to reach.',['辶','斤'],[p('road',-.50,-.75,1.35),p('axe',.70,-.05,1.25)])
add('远','distant-coin','A long road leads away to a tiny coin at its far end: imagine traveling far to collect it.',['辶','元'],[p('road',-.10,-.75,2),p('coins',1.45,-.55,.45)])
add('旧','old-sun-pole','A weathered pole stands beside the sun: imagine many days of sunlight making the pole old.',['丨','日'],[p('pole',-.8,0,1.8),p('sun',.80,.35,1.2)])
add('香','fragrant-grain','Grain warms beneath the sun; imagine its fragrance rising into the air.',['禾','日'],[p('wheat',-.75,-.10,1.5),p('sun',.80,.6,1.05)],[p('steam',-.15,.65,.65)])
add('苦','bitter-herbs','Grass grows beside an ancient tablet-like slab: imagine an old herbal recipe that tastes bitter.',['艹','古'],[p('grass',-.85,-.55,1.6),p('board',.80,.1,1.4)])
add('满','full-pool','Water fills the space between grass and two figures; imagine the little pool filled to the brim.',['氵','艹','两'],[p('water',0,-.85,2),p('grass',-1.20,-.20,1.2),p('count-2',1.05,.15,1.4)])
add('深','deep-pit','A ladder disappears toward water beneath an open frame: imagine exploring a deep pit.',['氵','罙'],[p('water',-.25,-1.05,1.6),p('ladder',.4,-.05,1.6)],[p('frame',-.25,.85,1.15,rotation=1.5708)])
add('洗','wash-first','Water waits beside one first-place marker: washing comes first before handling food.',['氵','先'],[p('water',-.70,-.4,1.5),p('count-1',.80,.1,2)],[p('hand',.80,-.5,.90)])
add('渴','thirsty-question','Water sits beside a questioning mouth: why wait any longer when you are thirsty?',['氵','曷'],[p('water',-.7,-.55,1.5),p('question',.70,.35,1.5)],[p('cup',.65,-.70,.85)])
add('饿','hungry-person','A person reaches toward a bowl of food: imagine an empty stomach asking to eat.',['饣','我'],[p('bowl',-.85,-.55,1.5),p('person',.70,-.05,1.4)],[p('rice',-.85,-.32,1.3)])
add('饱','full-package','A food bowl sits beside a packed bag: imagine your stomach as a package filled after a meal.',['饣','包'],[p('bowl',-.85,-.4,1.5),p('bag',.80,-.05,1.5)],[p('rice',-.85,-.16,1.3)])
add('疼','winter-ache','A sickbed stands beside winter ice; imagine the cold making an aching body hurt.',['疒','冬'],[p('bed',-.5,-.50,1.5),p('ice',1,.1,1)],[p('snow',1,.85,.70)])
add('累','tired-fieldwork','Silk trails across a planted field: imagine the tiring work of gathering every strand.',['田','糸'],[p('field',-.65,-.60,1.5),p('silk',.8,.1,1.35)])
add('懒','lazy-rest','A seated person rests beside a sofa while a broom waits unused: picture putting off the work out of laziness.',['懒'],[p('sitter',-.65,-.45,1.25)],[p('sofa',-.60,-.72,1.55,z=-.25),p('broom',1.15,-.10,1.5)])
add('胖','round-moon','A round body cue borrows half of a moon: imagine the moon becoming plump beside a tiny comparison bead.',['⺼','半'],[p('moon',-.70,.15,1.5),p('ball',.85,-.15,1.4)],[p('knife',.85,.65,.60)])
add('瘦','slender-elder','An elder stands beside a sickbed; imagine a slender figure after a long illness as this mnemonic for thin.',['疒','叟'],[p('bed',-.65,-.55,1.4),p('elder',1,-.05,1.3)])

# Emotions are visibly linked to the recurring heart cue.
add('音乐','musical-sound','A drum makes a sound beside musical notes: sounds arranged together become music.',['音','乐'],[p('drum',-.85,-.2,1.4),p('music',.85,.10,1.6)])
add('快乐','quick-music','A fast arrow rushes toward musical notes: imagine quick, lively music making you happy.',['快','乐'],[p('arrow',-.9,.05,1.1),p('music',.8,.10,1.65)])
add('开心','open-heart','An open door welcomes a bright heart: imagine opening your heart and feeling happy.',['开','心'],[p('door',-.65,0,1.35),p('heart',.85,.05,1.4)])
add('小心','small-careful-heart','A tiny bead sits beside a large heart: treat something small with care and be careful.',['小','心'],[p('count-1',-.85,-.20,1.2),p('heart',.70,0,1.65)])
add('放心','released-heart','An arrow releases a heart into open space: imagine letting your worry go and feeling reassured.',['放','心'],[p('arrow',-.9,.05,1.2),p('heart',.85,.10,1.6)])
add('担心','burdened-heart','A loaded bag weighs beside a heart: imagine carrying that burden as worry.',['担','心'],[p('bag',-.85,-.10,1.4),p('heart',.85,.15,1.5)],[p('coins',-.85,.3,.55)])
add('伤心','hurt-heart','A small bandage-like cross sits beside a heart: imagine an emotional hurt leaving you sad.',['伤','心'],[p('medical',-.85,-.1,1.2),p('heart',.80,.05,1.65)])
add('爱情','loving-emotion','Two hearts lean toward one another: love and emotion meet in romantic love.',['爱','情'],[p('heart',-.65,.05,1.45,rotation=.15),p('heart',.65,.05,1.45,rotation=-.15)])
add('心情','heart-mood','A heart reflects another heart like its emotional weather: notice the feeling in your heart, your mood.',['心','情'],[p('heart',-.85,.15,1.5),p('heart',.85,-.05,1.2)])
add('热情','warm-heart','A flame warms a heart: imagine offering a warm and enthusiastic welcome.',['热','情'],[p('flame',-.85,-.05,1.3),p('heart',.80,.10,1.5)])
add('同情','shared-feeling','Two equal beads sit beside a heart: imagine sharing the same feeling with someone in sympathy.',['同','情'],[p('count-2',-.85,-.1,1.6),p('heart',.85,.10,1.55)])
add('生气','growing-steam','A sprout grows beneath curling steam: imagine anger growing until steam seems to rise from your head.',['生','气'],[p('sprout',-.70,-.25,1.4),p('steam',.70,.10,1.8)])
add('信心','trusted-heart','A sealed trusted letter sits beside a heart: imagine keeping that trust in your heart as confidence.',['信','心'],[p('envelope',-.85,-.1,1.2),p('heart',.80,.10,1.6)])
add('自信','self-trust','A person faces a heart-sealed letter of trust: imagine that trust directed toward yourself.',['自','信'],[p('person',-.8,-.10,1.4),p('envelope',.85,.05,1.3)],[p('heart',.85,.05,.30,z=.08)])
add('哭','crying-mouths','Two open mouths hover above a dog: imagine hearing their sad cries together.',['口','口','犬'],[p('mouth',-.85,.65,1),p('mouth',.85,.65,1),p('dog',0,-.65,1.2)])
add('吵','noisy-mouth','An open mouth makes a fuss over a few little beads: imagine the noise of a pointless quarrel.',['口','少'],[p('mouth',-.85,.10,1.5),p('count-3',.85,-.15,1.7)])
add('响','sound-toward','A mouth sends a sound in the direction of an arrow: imagine the sound ringing toward you.',['口','向'],[p('mouth',-.85,.05,1.4),p('arrow',.85,.05,1.2)])

# School, work, medicine, communication and travel.
add('学校','school-books','A learning book stands beside a school building: imagine carrying it through the door to class.',['学','校'],[p('book',-.85,-.05,1.4),p('house',.85,0,1.2)])
add('学生','growing-student','A learning book stands beside a growing sprout: a student grows through study.',['学','生'],[p('book',-.85,-.05,1.4),p('sprout',.85,-.05,1.55)])
add('老师','elder-teacher','An elder stands beside a teacher’s blackboard: imagine learning from the older teacher.',['老','师'],[p('elder',-.95,-.1,1.3),p('blackboard',.65,.15,1.4)],[p('book',.65,-.70,.75)])
add('教室','teaching-room','A blackboard for teaching stands beside a small room: put the teaching tools inside to make a classroom.',['教','室'],[p('blackboard',-.85,.05,1.2),p('house',.85,-.10,1.15)])
add('图书馆','map-book-library','A map, a book and a public building gather in one scene: a library holds books that open up the world.',['图','书','馆'],[p('map',-1.35,.1,.9),p('book',0,-.15,1.1),p('house',1.3,0,.95)])
add('数学','counting-study','Ten counting beads lie beside a study book: learning to count leads into mathematics.',['数','学'],[p('count-10',-.85,-.20,1.7),p('book',.90,.05,1.5)])
add('数字','written-numbers','Counting beads sit beside a written page: imagine recording the count as a number.',['数','字'],[p('count-5',-.85,-.10,1.7),p('paper',.85,.05,1.5)])
add('字典','character-dictionary','A written character page sits beside a thick reference book: look up the character in the dictionary.',['字','典'],[p('paper',-.85,.10,1.2),p('book',.85,-.1,1.65)])
add('句子','child-sentence','A child speaks into a bubble with several sound marks: imagine the sounds joining into a complete sentence.',['句','子'],[p('speech',.65,.60,1.4),p('child',-.75,-.35,1.2)])
add('语言','spoken-language','Two speech bubbles trade spoken words: imagine a shared language carrying the conversation.',['语','言'],[p('speech',-.85,.10,1.4),p('speech',.85,.10,1.4)])
add('词语','word-expression','A little written page joins a speech bubble: a written word becomes an expression you can say.',['词','语'],[p('paper',-.85,-.05,1.2),p('speech',.85,.25,1.4)])
add('阅读','examining-book','An eye examines a book closely: follow the lines as you read.',['阅','读'],[p('eye',-.9,.30,1.2),p('book',.70,-.15,1.65)])
add('复习','repeat-practice','A backward arrow returns to a practice feather: revisit the same lesson to review it.',['复','习'],[p('arrow',-.85,.05,1.1,rotation=3.14159),p('feather',.85,.0,1.6)],[p('book',0,-.80,.75)])
add('预习','prepare-practice','A book waits ready beside a practice feather: prepare the lesson before practicing it.',['预','习'],[p('book',-.85,-.10,1.4),p('feather',.85,.1,1.55)],[p('clock',0,.80,.55)])
add('学期','study-calendar','A learning book sits beside a calendar: the stretch of scheduled study is a school term.',['学','期'],[p('book',-.85,-.05,1.4),p('calendar',.85,.10,1.3)])
add('工作','making-work','Tools meet a half-built table: working with the tools makes something useful.',['工','作'],[p('axe',-.95,.0,1.3),p('table',.55,-.40,1.5)])
add('工具','work-tools','An axe and a brush wait together for a job: choose the tool that fits the work.',['工','具'],[p('axe',-.75,0,1.6),p('brush',.80,.0,1.5)])
add('修理','repair-plan','A tool stands beside a diagram-like page: use a reasoned plan to repair the broken object.',['修','理'],[p('axe',-.95,.10,1.2),p('paper',.85,.10,1.2)],[p('chair',0,-.65,.80)])
add('照片','photo-light','Light falls on a small flat picture: imagine saving a slice of the scene as a photograph.',['照','片'],[p('sun',-.85,.50,1),p('map',.65,-.15,1.5)],[p('camera',.65,-.95,.60)])
add('照相机','camera-light','A flash shines toward two facing figures while a camera captures them: the machine makes their picture.',['照','相','机'],[p('lightning',-1.45,.30,.7),p('person',-.30,-.25,.90),p('camera',1.1,.0,1.2)],[p('person',-.80,-.25,.90,z=-.30)])
add('打电话','phone-call','A hand taps an electric phone; a speech bubble shows the conversation starting.',['打','电','话'],[p('hand',-1.25,-.15,1),p('lightning',0,.65,.8),p('speech',1.2,.2,1.1)],[p('phone',0,-.5,1.1)])
add('电子','electric-child','A tiny child stands beside an electric bolt: picture a small electric helper as the cue for electronic.',['电','子'],[p('lightning',-.70,.10,1.4),p('child',.85,-.20,1.2)])
add('电子邮箱','electronic-inbox','An electric bolt and a tiny child deliver an envelope to a box: imagine mail arriving in an electronic inbox.',['电','子','邮','箱'],[p('lightning',-1.55,.3,.7),p('child',-.65,-.5,.65),p('envelope',.35,.25,.85),p('box',1.25,-.50,1.0)])
add('上网','online-net','An upward arrow rises toward a net while a screen waits below: imagine connecting to the network online.',['上','网'],[p('arrow',-.85,.10,1.1,rotation=1.5708),p('net',.80,.10,1.3)],[p('screen',.80,-.90,.6)])
add('网站','network-station','A net stands beside a small station-like doorway: picture a place to visit on the network, a website.',['网','站'],[p('net',-.85,0,1.3),p('door',.85,0,1.35)])
add('地图','ground-map','A patch of ground becomes a sheet showing roads and destinations: a map of the place.',['地','图'],[p('earth',-.90,-.65,1.3),p('map',.75,.15,1.6)])
add('地点','place-dot','One bead marks a spot on the ground: that exact location is the place.',['地','点'],[p('earth',0,-.65,2),p('count-1',0,-.10,1.8)])
add('地方','square-place','A square frame marks out a patch of ground: this defined area is a place.',['地','方'],[p('earth',-.4,-.65,1.6),p('frame',.70,.0,1.25)])
add('地址','address-marker','A flag marks the site of a house on a patch of ground: imagine writing the address of that exact spot.',['地','址'],[p('earth',-.70,-.95,1.5),p('flag',.90,-.10,1.4)],[p('house',-.65,-.20,1)])
add('城市','city-market','A wall shelters a little market table: imagine the streets and shops of a city behind the wall.',['城','市'],[p('wall',-.85,.05,1.45),p('table',.85,-.50,1.2)],[p('fruit',.85,.05,.5)])
add('长城','long-wall','A long ribbon runs beside a stretch of brick wall: follow the wall’s length to remember the Great Wall.',['长','城'],[p('silk',0,.75,2.2),p('wall',-.70,-.35,1.3)],[p('wall',.75,-.35,1.3)])
add('国家','country-home','A flag marks a territory beside a house: imagine all the homes within a country’s boundary.',['国','家'],[p('flag',-.85,.05,1.4),p('house',.85,-.10,1.2)])
add('机场','plane-field','An airplane machine stands above a broad landing field: this is the airport.',['机','场'],[p('plane',0,.25,1.7),p('field',0,-.95,2)],[p('road',0,-.78,1.5)])
add('地铁','underground-train','Ground lies above a metal train: imagine riding on tracks beneath the earth, the subway.',['地','铁'],[p('earth',0,.75,2),p('train',0,-.55,1.9)])
add('电梯','electric-ladder','An electric bolt powers a ladder-like shaft: imagine it carrying you between floors as an elevator.',['电','梯'],[p('lightning',-.85,.10,1.25),p('ladder',.85,.0,1.6)])
add('司机','machine-driver','A person manages the controls beside a vehicle machine: picture the driver in charge.',['司','机'],[p('person',-1.1,-.2,1.2),p('car',.55,-.45,1.7)])
add('乘坐','riding-seated','A rider sits beside a vehicle, ready to take the seat inside and ride.',['乘','坐'],[p('person',-.9,-.15,1.15),p('sitter',.85,-.15,1.15)],[p('car',0,-.95,.75)])
add('出发','setting-off','An open doorway leads to an outward arrow: leave the doorway and set off.',['出','发'],[p('door',-.70,-.05,1.5),p('arrow',1,.10,1.1)])
add('降落','plane-landing','Two downward arrows guide an airplane toward the ground: imagine descending and landing.',['降','落'],[p('arrow',-1.3,.45,.85,rotation=-1.5708),p('arrow',1.3,.45,.85,rotation=-1.5708)],[p('plane',0,-.35,1.25),p('road',0,-1.1,1.7)])
add('旅行','travel-walk','A packed suitcase stands beside a trail of footsteps: take your luggage and travel.',['旅','行'],[p('suitcase',-.8,-.05,1.5),p('footprints',.85,-.75,1.3)])
add('旅游','tour-flag','A suitcase waits beside a tour flag and a small map: follow the route on your travels.',['旅','游'],[p('suitcase',-.9,-.1,1.4),p('flag',.90,-.05,1.4)],[p('map',.40,-.90,.65)])
add('宾馆','visitor-hotel','A visitor arrives beside a house with a bed waiting nearby: picture staying overnight at a hotel.',['宾','馆'],[p('person',-1.1,-.10,1.2),p('house',.65,.10,1.25)],[p('bed',.65,-.95,.65)])
add('医院','healing-courtyard','A first-aid case stands beside a courtyard-like building: imagine entering a place of healing, a hospital.',['医','院'],[p('medical',-.90,-.10,1.3),p('house',.85,.0,1.3)])
add('医生','healing-growth','A medical case stands beside a growing sprout: picture a doctor helping health grow again.',['医','生'],[p('medical',-.85,0,1.4),p('sprout',.85,-.10,1.5)])
add('护士','guarding-care','A medical case stands beside a learned caregiver’s book: imagine a nurse guarding a patient’s well-being.',['护','士'],[p('medical',-.85,.0,1.35),p('book',.85,-.05,1.4)])
add('药','herbal-medicine','Medicinal grass waits beside an appointment clock and a capsule: remember to take medicine at the right time.',['艹','约'],[p('grass',-.95,-.50,1.4),p('clock',.95,.25,1.0)],[p('pill',.1,-.35,1.1)])
add('生病','growing-illness','A growing sprout stands beside a sickbed: imagine an illness beginning to grow and needing rest.',['生','病'],[p('sprout',-1.0,0,1.25),p('bed',.45,-.50,1.7)])
add('发烧','fever-heat','An outward arrow sends heat from a flame toward a sickbed: imagine the body giving off heat during a fever.',['发','烧'],[p('arrow',-.95,.45,.9),p('flame',.80,.20,1.1)],[p('bed',0,-.80,1.2)])
add('健康','healthy-well','An upright person stands beside a heart and a sprout: imagine strength, well-being and healthy growth.',['健','康'],[p('person',-.85,-.10,1.4),p('heart',.85,.2,1.2)],[p('sprout',.85,-.80,.70)])
add('刷牙','tooth-brushing','A bristled brush approaches a white tooth: picture brushing every surface clean.',['刷','牙'],[p('brush-teeth',-.75,.05,1.55),p('tooth',.80,.05,1.65)])
add('牙膏','tooth-paste','A tooth waits beside a capsule-shaped dab of paste: imagine squeezing toothpaste onto a brush.',['牙','膏'],[p('tooth',-.75,.05,1.6),p('pill',.85,.0,1.2)],[p('brush-teeth',.2,-.85,.65,rotation=1.5708)])
add('毛巾','soft-towel','A patch of soft fur sits beside a woven cloth: imagine a towel that feels just as soft.',['毛','巾'],[p('fur',-.85,.05,1.4),p('towel',.85,.05,1.6)])
add('洗手间','hand-washing-room','Water and a hand wait between doorposts: picture a room for washing your hands.',['洗','手','间'],[p('water',-1.3,-.55,.95),p('hand',-.15,-.05,1.2),p('door',1.15,.0,1.2)])
add('打扫','hand-sweep','A hand reaches for a broom: imagine sweeping the floor clean.',['打','扫'],[p('hand',-.80,.05,1.5),p('broom',.80,.05,1.5)])
add('镜子','child-mirror','A child stands before a tall mirror: imagine recognizing the reflected face.',['镜','子'],[p('mirror',.75,.10,1.65),p('child',-1,-.15,1.2)])
add('窗户','window-door','A cross-divided window sits beside a doorway: the two openings connect the room to the world outside.',['窗','户'],[p('window',-.85,0,1.3),p('door',.85,0,1.3)])
add('盒子','child-box','A child places a small toy into an open box: remember the container beside the child.',['盒','子'],[p('box',.70,-.35,1.5),p('child',-1,-.10,1.25)],[p('ball',.70,.1,.40)])
add('勺子','child-spoon','A child holds a spoon above a bowl: the long handle brings each scoop within reach.',['勺','子'],[p('spoon',.8,.15,1.5),p('child',-1,-.10,1.25)],[p('bowl',.75,-.85,1.05)])
add('包子','child-bun','A child unwraps a soft steamed bun: imagine the filling tucked inside its dough package.',['包','子'],[p('bun',.75,-.10,1.6),p('child',-1,-.15,1.2)])
add('饺子','child-dumpling','A child studies the folded edge of a dumpling before taking a bite.',['饺','子'],[p('dumpling',.75,-.10,1.7),p('child',-1,-.10,1.25)])
add('蛋糕','egg-cake','An egg sits beside a frosted cake: imagine mixing the egg into the cake before baking.',['蛋','糕'],[p('egg',-1,-.15,1.1),p('cake',.65,-.10,1.6)])
add('生日','growing-birthday','A sprout grows toward a sun above a candle-topped cake: another year of growth reaches its birthday.',['生','日'],[p('sprout',-1.1,-.10,1.2),p('sun',1.05,.70,.85)],[p('cake',.30,-.55,1.15)])
add('饼干','dry-biscuit','A little cake-like biscuit rests beside dry stalks of grain: imagine its crisp, dry bite.',['饼','干'],[p('cookie',-.65,-.2,1.7),p('wheat',.95,.0,1.4)])
add('菜单','single-menu','Vegetable leaves sit beside one printed sheet: choose your meal from the menu.',['菜','单'],[p('leaf',-.85,.05,1.4),p('paper',.85,.05,1.55)])
add('饭馆','rice-restaurant','A bowl of rice stands beside a public building: imagine the rice meals served in this restaurant.',['饭','馆'],[p('bowl',-.85,-.45,1.45),p('house',.85,.05,1.2)],[p('rice',-.85,-.2,1.3)])
add('餐厅','dining-hall','A mouth waits beside a dining table under a room’s roof: picture a hall for eating.',['餐','厅'],[p('mouth',-1,.15,1.15),p('table',.65,-.50,1.4)],[p('roof',.65,.90,1.2),p('bowl',.65,.0,.65)])
add('小吃','little-snack','A tiny bun sits beside an open mouth: a little something to eat is a snack.',['小','吃'],[p('bun',-.85,-.05,.8),p('mouth',.80,.10,1.5)])
add('矿泉水','mineral-spring-water','A rocky mountain shelters a spring pool beside a water bottle: picture mineral water from a spring.',['矿','泉','水'],[p('mountain',-1.35,.05,.9),p('water',-.1,-.65,1.1),p('bottle',1.2,-.15,1.2)])
add('垃圾桶','rubbish-bin','Two discarded paper pieces wait beside a bucket: put both pieces of garbage into the bin.',['垃','圾','桶'],[p('paper',-1.2,-.55,.45,rotation=.4),p('paper',-.5,-.75,.40,rotation=-.3),p('bucket',.85,-.1,1.6)])
add('植物','growing-plant','A living tree stands beside a small potted sprout: these growing things are plants.',['植','物'],[p('tree',-.85,0,1.3),p('sprout',.90,.10,1.2)],[p('pot',.90,-.7,.85)])
add('动物','moving-animal','A direction arrow points alongside a walking horse: imagine a living thing moving as an animal.',['动','物'],[p('arrow',-.95,.50,.9),p('horse',.55,-.25,1.6)])
add('阳光','sunshine','A bright sun casts light toward a little lamp: imagine sunlight filling everything around it.',['阳','光'],[p('sun',-.75,.40,1.3),p('lamp',.85,-.35,1.4)])
add('天气','sky-air','A cloud hangs over curling air beside the sun: sky and air together make the weather.',['天','气'],[p('cloud',-.70,.50,1.35),p('steam',.95,-.20,1.35)],[p('sun',-1.1,-.55,.65)])
add('气候','air-over-time','Air curls beside a calendar: picture weather patterns observed over a long wait, the climate.',['气','候'],[p('steam',-.80,.1,1.65),p('calendar',.85,0,1.4)])
add('季节','season-joints','A tree stands beside a pole divided into sections: imagine the year divided into seasons.',['季','节'],[p('tree',-.8,0,1.4),p('pole',.90,0,1.5)],[p('bar',.9,-.50,.35),p('bar',.9,0,.35),p('bar',.9,.50,.35)])
add('凉快','quick-cool','An ice cube sends a quick arrow of coolness toward you: imagine feeling pleasantly cool.',['凉','快'],[p('ice',-.80,0,1.5),p('arrow',.85,0,1.2)])
add('暖和','warm-together','A warm lamp shines over two people together: imagine sharing its gentle warmth.',['暖','和'],[p('lamp',-.9,.10,1.4),p('person',.65,-.3,.9)],[p('person',1.25,-.3,.9)])
add('早上','morning-rise','An early sun rises beside an upward arrow: the morning is beginning.',['早','上'],[p('sun',-.80,.15,1.35),p('arrow',.85,.10,1.1,rotation=1.5708)])
add('上午','before-noon','An upward arrow approaches a high sun: picture the morning hours leading up to noon.',['上','午'],[p('arrow',-.85,.0,1.1,rotation=1.5708),p('sun',.85,.70,1.15)])
add('下午','after-noon','A downward arrow leads away from the high noon sun: the afternoon follows.',['下','午'],[p('arrow',-.85,-.05,1.1,rotation=-1.5708),p('sun',.85,.70,1.15)])
add('中午','middle-noon','A pole marks the middle below a high sun: imagine the sun over the middle of the day, noon.',['中','午'],[p('pole',0,-.50,1.2),p('sun',0,.95,1.0)])
add('晚上','evening-moon','A moon climbs beside an upward arrow: evening rises into the night.',['晚','上'],[p('moon',-.80,.2,1.5),p('arrow',.85,.0,1.1,rotation=1.5708)])
add('星期','star-week','Seven stars fill a small calendar period: use the seven lights to remember a week.',['星','期'],[p('star',-.95,.45,.80),p('calendar',.80,-.20,1.5)],[p('count-7',-.85,-.65,1.3)])
add('按时','press-on-time','A hand presses toward a clock: imagine matching the required time exactly.',['按','时'],[p('hand',-.85,.25,1.3),p('clock',.85,-.05,1.55)])
add('准时','accurate-time','An arrow points directly at a clock’s center: accuracy and time meet when you arrive on time.',['准','时'],[p('arrow',-.95,.0,1.05),p('clock',.85,0,1.6)])
add('迟到','late-arrival','A clock waits beside a doorway while a traveler is still outside: imagine arriving late.',['迟','到'],[p('clock',-.95,.50,1.1),p('door',.80,.0,1.4)],[p('walker',-.85,-.7,.65)])
add('现在','here-now','An eye notices a flag planted at this spot: what appears here at this moment is now.',['现','在'],[p('eye',-.85,.20,1.25),p('flag',.85,0,1.5)])
add('开始','open-beginning','An open doorway leads to the first footprint on a path: opening the way begins the journey.',['开','始'],[p('door',-.70,.0,1.5),p('footprints',.95,-.75,1.1)])
add('结束','tied-bundle','A curled knot sits beside a bundle of long sticks: tie the bundle when the work is finished.',['结','束'],[p('coil',-.85,.15,1.2),p('chopsticks',.75,-.05,1.6)],[p('silk',.75,-.25,.55)])
add('相反','opposite-directions','Two arrows face in opposite directions: notice how one reverses the other.',['相','反'],[p('arrow',-.85,0,1.15),p('arrow',.85,0,1.15,rotation=3.14159)])
add('相同','matching-pair','Two matching cups face each other with the same shape and size: they are identical.',['相','同'],[p('cup',-.8,0,1.4),p('cup',.8,0,1.4)])
add('一样','one-pattern','One bar points to two matching leaf patterns: picture both leaves being the same.',['一','样'],[p('bar',-.95,.10,.75),p('leaf',.55,.05,1.3)],[p('leaf',1.25,.05,1.3)])
add('对面','opposite-face','An arrow faces a smiling head on the other side: the person sits opposite you.',['对','面'],[p('arrow',-.90,.05,1.1),p('face',.85,.05,1.65)])
add('见面','meeting-face','An eye catches sight of a familiar face: imagine meeting the person in front of you.',['见','面'],[p('eye',-.90,.10,1.3),p('face',.85,.05,1.6)])
add('排队','people-queue','Three people stand in a neat row beside a team flag: line up and wait your turn.',['排','队'],[p('person',-1.2,-.40,.9),p('flag',1.40,0,1.2)],[p('person',-.35,-.40,.9),p('person',.50,-.40,.9)])
add('排列','ordered-row','Beads line up beside a straight bar: arrange each one in order along the line.',['排','列'],[p('count-5',0,.10,2.2),p('bar',0,-.60,2)])
add('顺序','ordered-steps','An arrow runs from one bead to two, then three: follow the sequence in order.',['顺','序'],[p('arrow',0,.75,1.4),p('count-1',-1.2,-.35,1.4)],[p('count-2',0,-.35,1.4),p('count-3',1.1,-.35,1.4)])
add('增加','increasing-count','An upward arrow rises beside a growing pile of beads: imagine adding more to increase the count.',['增','加'],[p('arrow',-.90,0,1.2,rotation=1.5708),p('count-10',.85,-.1,1.7)])
add('减少','decreasing-count','A downward arrow leaves only a few beads behind: reduce the number until fewer remain.',['减','少'],[p('arrow',-.90,0,1.2,rotation=-1.5708),p('count-3',.85,-.1,1.7)])
add('抬','lifting','Two hands raise an open box: picture lifting it together from below.',['抬'],[p('box',0,.55,1.4)],[p('hand',-.6,-.40,1.2),p('hand',.6,-.40,1.2)])
add('抱','hug-package','A hand curls beside a package: imagine holding the package close in your arms.',['扌','包'],[p('hand',-.80,.0,1.4),p('bag',.60,0,1.5)])
add('拉','pulling-person','A hand reaches toward a standing person; a backward arrow shows the pull.',['扌','立'],[p('hand',-.75,.25,1.3),p('person',.85,-.10,1.4)],[p('arrow',-.70,-.75,.85,rotation=3.14159)])
add('推','pushing-bird','A hand gently pushes toward a little bird; the arrow shows the forward direction.',['扌','隹'],[p('hand',-.80,.05,1.35),p('bird',.85,.0,1.35)],[p('arrow',0,-.80,.90)])
add('拿','holding-fit','Two fitting pieces meet above a hand: imagine bringing them together and taking hold.',['合','手'],[p('box',-.65,.35,1.1),p('hand',.75,-.10,1.5)],[p('lid',-.65,.9,1.0)])
add('扔','throwing-pitcher','A hand releases a handled cup along an outward arrow: imagine the motion of throwing.',['扌','乃'],[p('hand',-.9,-.05,1.4),p('cup',1,.45,1)],[p('arrow',.15,.25,.65)])
add('停','stop-pavilion','A traveler reaches a roofed pavilion and stops beside it for a rest.',['亻','亭'],[p('walker',-1.1,-.15,1.2),p('house',.70,0,1.2)])
add('停止','stop-steps','A pavilion stands at the end of a trail of feet: imagine stopping there instead of taking another step.',['停','止'],[p('house',-.75,.0,1.3),p('foot',.95,-.35,1.3)])
add('站','standing-booth','A person stands upright at a little booth-like table: stay on your feet while waiting.',['立','占'],[p('person',-.95,-.1,1.4),p('table',.75,-.40,1.4)],[p('roof',.75,.90,1.1)])
add('礼物','courtesy-gift','A welcoming hand offers a neatly packed bag: an object given with courtesy becomes a gift.',['礼','物'],[p('hand',-.85,.05,1.4),p('bag',.85,.0,1.5)])
add('购物','buying-things','Coins wait beside a bag of goods: exchange the money for the things while shopping.',['购','物'],[p('coins',-.85,-.30,1.5),p('bag',.85,.0,1.5)])
add('付款','paying-funds','A hand moves coins toward a second stack of funds: picture paying the amount due.',['付','款'],[p('hand',-.85,.10,1.4),p('coins',.85,-.25,1.6)],[p('coins',-.65,-.55,.6)])
add('现金','visible-cash','An eye spots golden coins on the table: money that is present in your hand is cash.',['现','金'],[p('eye',-.85,.30,1.2),p('coins',.85,-.2,1.8)])
add('零钱','spare-change','A zero-shaped ring sits beside a few coins: imagine the small change left after a payment.',['零','钱'],[p('zero',-.80,.10,1.2),p('coins',.80,-.2,1.5)])
add('工资','work-wages','A working tool stands beside a supply of coins: these resources are the wages earned through work.',['工','资'],[p('axe',-.85,.05,1.4),p('coins',.85,-.25,1.75)])
add('奖金','gold-prize','A star-shaped prize rises above a pile of golden coins: imagine receiving a cash bonus.',['奖','金'],[p('star',-.85,.35,1.2),p('coins',.85,-.25,1.75)])
add('价格','price-grid','Coins sit beside a ruled board: imagine each square recording a product’s price.',['价','格'],[p('coins',-.85,-.25,1.6),p('window',.85,.05,1.3)])
add('商店','trade-shop','Coins and a market table wait beside a small building: a shop is a place for trade.',['商','店'],[p('coins',-1,.0,1.05),p('house',.85,.0,1.3)],[p('table',-1,-.80,.95)])
add('服务员','attendant-duty','A uniformed person carries out a task beside a tray and a companion: picture an attendant serving the group.',['服','务','员'],[p('shirt',-1.35,.10,1),p('plate',-.05,-.55,1.1),p('person',1.25,-.10,1.15)])
add('售货员','shop-salesperson','A selling table displays goods beside a person: the salesperson helps customers choose.',['售','货','员'],[p('table',-1.20,-.55,1.05),p('bag',-.1,.05,.9),p('person',1.20,-.10,1.15)])
