import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Pause,Play,RotateCcw,Sparkles} from 'lucide-react';
import type {Character,Lesson} from '../types';
import {THEATRE_LESSONS} from './lessons';
import SceneIllustration from './SceneIllustration';
import GlyphStage from './GlyphStage';
import Reconstruction from './Reconstruction';
import {captureStage,requestVisualHelp,scriptedHint} from './visualTutor';
import type {VisualHelp} from './visualTutor';
import './theatre.css';

const stops=[.38,.65,1];
export default function Theatre({lessons,characters,word,onWordChange,onLibrary}:{lessons:Lesson[];characters:Record<string,Character>;word:string;onWordChange:(word:string)=>void;onLibrary:()=>void}){
 const index=Math.max(0,THEATRE_LESSONS.findIndex(l=>l.word===word));
 const lesson=THEATRE_LESSONS[index],source=lessons.find(l=>l.id===lesson.wordId)!;
 const [progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[highlight,setHighlight]=useState<string|null>(null),[recall,setRecall]=useState(false),[completed,setCompleted]=useState<string[]>([]),[help,setHelp]=useState<VisualHelp|null>(null),[available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[helpError,setHelpError]=useState(''),[snapshot,setSnapshot]=useState('');
 const stage=useRef<HTMLDivElement>(null),request=useRef(0);
 const phase=progress<.46?0:progress<.99?1:2;
 useEffect(()=>{setProgress(0);setPlaying(false);setRecall(false);setHighlight(null);setHelp(null);setHelpError('');setSnapshot('');setBusy(false);request.current++;},[lesson.word]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(media.matches);setPlaying(false);};media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{fetch('/api/visual-tutor/status').then(r=>r.ok?r.json():null).then(v=>setAvailable(v?.available===true)).catch(()=>setAvailable(false));},[]);
 useEffect(()=>{if(!playing||reduced)return;let frame=0;let last=performance.now();const tick=(time:number)=>{const elapsed=Math.min(time-last,80);last=time;setProgress(p=>Math.min(1,p+elapsed/12000));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,reduced]);
 useEffect(()=>{if(progress===1)setPlaying(false);},[progress]);
 useEffect(()=>()=>{if(snapshot)URL.revokeObjectURL(snapshot);},[snapshot]);
 const jump=(p:number)=>{setProgress(p);setPlaying(false);setRecall(false);};
 const select=(glyph:string)=>{setHighlight(h=>h===glyph?null:glyph);setHelp(null);};
 const ask=async(question:string)=>{setPlaying(false);setHelpError('');const id=++request.current;setBusy(true);try{const answer=available&&stage.current?await requestVisualHelp({word:lesson.word,selected:highlight,progress,screenshot:await captureStage(stage.current),question}):scriptedHint(lesson,highlight,question);if(id!==request.current)return;setHelp(answer);setHighlight(answer.highlight);if(answer.action==='replay')setProgress(.15);if(answer.action==='compare')setProgress(.65);}catch{if(id===request.current){setHelp(scriptedHint(lesson,highlight,question));setHelpError('The visual tutor could not respond. Showing a scripted hint.');}}finally{if(id===request.current)setBusy(false);}};
 return <main className="theatre-page">
  <div className="theatre-top"><span className="eyebrow">THE MEMORY THEATRE <i/> FIRST TEN</span><button className="text-button" onClick={onLibrary}>Explore all 1,000 words <ArrowRight size={15}/></button></div>
  <div className="theatre-heading"><div><h1>A scene to remember.</h1><p>See the images. Find the elements. Make the meaning stick.</p></div><span className="theatre-count">{String(index+1).padStart(2,'0')} <small>/ 10</small></span></div>
  {!recall&&<nav className="scene-picker" aria-label="Choose visual lesson">{THEATRE_LESSONS.map((l,i)=><button key={l.word} aria-label={`Lesson ${i+1}: ${l.word}`} aria-current={index===i?'step':undefined} onClick={()=>onWordChange(l.word)}><span lang="zh-Hans">{l.word}</span><small>{lessons.find(w=>w.id===l.wordId)?.meaning.split(';')[0]}</small>{completed.includes(l.word)&&<Check size={12}/>}</button>)}</nav>}
  <section className="theatre-card" aria-label={recall?'Reconstruction exercise':`${lesson.word} visual lesson`}>
   <div className="scene-title"><div><span className="scene-word" lang="zh-Hans">{recall?'?':lesson.word}</span><span><b>{recall?'Remember the scene':source.pinyin}</b><span>{source.meaning}</span></span></div><label className="motion-toggle"><input type="checkbox" checked={reduced} onChange={e=>{setReduced(e.target.checked);setPlaying(false);}}/>Still steps</label></div>
   {!recall?<><div className="theatre-stage" ref={stage} data-progress={progress.toFixed(3)} data-lesson={lesson.word}>
    <div className="illustration-layer" inert={progress>.58} aria-hidden={progress>.58} style={{opacity:Math.max(0,1-Math.max(0,progress-.43)/.2),pointerEvents:progress>.58?'none':'auto'}}><SceneIllustration scene={lesson.scene} progress={progress} reducedMotion={reduced} highlight={highlight} onSelect={select}/></div>
    <GlyphStage lesson={lesson} characters={characters} progress={progress} highlight={highlight}/>
   </div><div className="theatre-stage-caption" aria-live="polite"><span>{['01 / THE SCENE','02 / THE ELEMENTS','03 / THE MEANING'][phase]}</span><h2>{phase===0?lesson.title:phase===1?'The images become writing.':source.meaning}</h2><p>{lesson.stageCaptions[phase]}</p></div>
   <div className="theatre-timeline"><button className="play-scene" aria-label={reduced?'Advance one step':playing?'Pause scene':'Play scene'} onClick={()=>{if(reduced){jump(stops.find(s=>s>progress+.01)??0);return;}if(progress>=1)setProgress(0);setPlaying(v=>!v);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><label className="scrub-label"><span className="sr-only">Story progress</span><input aria-label="Story progress" type="range" min="0" max="1000" step="1" value={Math.round(progress*1000)} onChange={e=>jump(Number(e.target.value)/1000)}/></label><button className="icon-button" aria-label="Restart scene" onClick={()=>jump(0)}><RotateCcw size={17}/></button></div>
   <div className="scene-steps">{['Watch the story','See the elements','Read the word'].map((text,i)=><button key={text} aria-pressed={phase===i} onClick={()=>jump(stops[i])}><span>{i+1}</span>{text}<ChevronRight size={13}/></button>)}<button onClick={()=>{setPlaying(false);setRecall(true);setHelp(null);}}><span>4</span>Rebuild it <ChevronRight size={13}/></button></div>
   </>:<div className="theatre-recall"><button className="text-button" onClick={()=>setRecall(false)}><ArrowLeft size={14}/>Back to the scene</button><Reconstruction key={lesson.word} lesson={lesson} onComplete={()=>setCompleted(c=>c.includes(lesson.word)?c:[...c,lesson.word])}/></div>}
  </section>
  {!recall&&<section className="theatre-connect"><div className="theatre-cues"><span className="micro">KEEP THESE IMAGES</span><div>{lesson.parts.map((p,i)=><button key={i} aria-pressed={highlight===p.glyph} onClick={()=>select(p.glyph)} style={{'--cue':p.color} as React.CSSProperties}><b lang="zh-Hans">{p.glyph}</b><span>{p.image}</span></button>)}</div><p>{lesson.story}</p><small>Invented memory story · A sound component keeps its image.</small></div><div className="theatre-helper"><span className="micro"><Sparkles size={14}/>{available?'VISUAL TUTOR':'GUIDED HINTS · SCRIPTED'}</span><p>{help?.message||'Select an image or element. Let its shape bring the scene back.'}</p>{help&&<small>{help.mode==='live'?'Astra inspected this scene.':'Scripted hint · no AI image analysis.'}</small>}{helpError&&<small role="status">{helpError}</small>}<div><button className="secondary" disabled={busy} onClick={()=>ask('Help me connect this selected image to the written element and meaning.')}>{busy?'Looking…':available?'Ask about this scene':'Get a memory hint'}</button>{['清','晴'].includes(lesson.word)&&<button className="text-button" disabled={busy} onClick={()=>ask('I confuse 清 and 晴. Show me the difference.')}>清 or 晴?</button>}</div><button className="text-button frame-preview-button" onClick={async()=>{setPlaying(false);try{if(stage.current){const png=await captureStage(stage.current);setSnapshot(URL.createObjectURL(await(await fetch(png)).blob()));}}catch{setHelpError('The scene snapshot could not be made.');}}}>Preview the scene sent to the tutor</button>{snapshot&&<details open className="frame-preview"><summary>Captured frame · no upload</summary><img src={snapshot} alt={`Captured visible scene for ${lesson.word}`}/><a href={snapshot} download={`hanzi-${lesson.word}.png`}>Save this frame</a></details>}</div></section>}
  <div className="theatre-bottom"><details><summary>History & sources <span>The story is a memory invention.</span></summary><p>These scenes connect visible shapes to a selected meaning. They are not historical accounts of how the writing was created.</p><p>{source.characters.map(c=><span key={c} className="history-char"><b lang="zh-Hans">{c}</b> {characters[c]?.decomposition} · <a href={`https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=${encodeURIComponent(c)}`} target="_blank" rel="noreferrer">Historical reference ↗</a></span>)}</p><a href={source.source} target="_blank" rel="noreferrer">Dictionary entry ↗</a><a href="https://github.com/skishore/makemeahanzi/tree/bddc96d41bef78427ed0e034e9f7e31d71fd1b92" target="_blank" rel="noreferrer">Stroke & structure source ↗</a><p>Chinese strokes use the sourced outlines. Color and movement are teaching choices. Artwork was generated with the built-in image tool; its model is not selectable. {available?'Live image understanding is available through the local tutor connection.':'Live image understanding is unavailable here; hints are scripted.'}</p></details><div><button className="icon-button" aria-label="Previous visual lesson" disabled={index===0} onClick={()=>onWordChange(THEATRE_LESSONS[index-1].word)}><ArrowLeft size={18}/></button><button className="primary" onClick={()=>onWordChange(THEATRE_LESSONS[(index+1)%10].word)}>{index===9?'Start again':'Next scene'} <ArrowRight size={16}/></button></div></div>
 </main>;
}
