import {useRef,useState} from 'react';
import {ArrowRight,Brain,Check,CheckCircle2,Sparkles} from 'lucide-react';
import type {Lesson,Session,Trial} from './types';
import {distractors,elementQuestion,planExperiment,shuffle,summarize} from './logic';
import MemoryImages from './MemoryImages';
type Focus='elements'|'meaning';
type Item=ReturnType<typeof planExperiment>[number]&{question:ReturnType<typeof elementQuestion>};
export default function Practice({lessons,onFinish,onBack}:{lessons:Lesson[];onFinish:(s:Session)=>void;onBack:()=>void}){
 const [phase,setPhase]=useState<'setup'|'study'|'recall'|'done'>('setup');
 const [size,setSize]=useState(10),[scope,setScope]=useState('stress'),[focus,setFocus]=useState<Focus>('elements');
 const [plan,setPlan]=useState<Item[]>([]),[order,setOrder]=useState<Item[]>([]),[index,setIndex]=useState(0);
 const [choices,setChoices]=useState<string[]>([]),[picked,setPicked]=useState<string|null>(null),[trials,setTrials]=useState<Trial[]>([]);
 const [times,setTimes]=useState<Record<string,number>>({}),[questionAt,setQuestionAt]=useState(0);
 const started=useRef(performance.now());
 const start=()=>{const p=planExperiment(scope==='stress'?lessons.filter(l=>l.stressTest):lessons,size).map(x=>({...x,question:elementQuestion(x.lesson,lessons)}));setPlan(p);setPhase('study');setIndex(0);setTrials([]);setTimes({});started.current=performance.now();};
 const options=(p:Item)=>focus==='elements'?p.question.choices:distractors(p.lesson,lessons);
 const nextStudy=()=>{setTimes(t=>({...t,[plan[index].lesson.id]:performance.now()-started.current}));started.current=performance.now();if(index+1<plan.length)setIndex(index+1);else{const recall=shuffle(plan);setOrder(recall);setChoices(options(recall[0]));setIndex(0);setPicked(null);setQuestionAt(performance.now());setPhase('recall');}};
 const expected=(p:Item)=>focus==='elements'?p.question.answer.glyph:p.lesson.meaning;
 const answer=(choice:string)=>{if(picked!==null)return;setPicked(choice);const p=order[index];setTrials(t=>[...t,{lessonId:p.lesson.id,condition:p.condition,correct:choice===expected(p),selected:choice,responseMs:performance.now()-questionAt,studyMs:times[p.lesson.id]}]);};
 const nextQuestion=()=>{if(index+1<order.length){setIndex(index+1);setChoices(options(order[index+1]));setPicked(null);setQuestionAt(performance.now());}else{onFinish({id:crypto.randomUUID(),date:new Date().toISOString(),focus,contentRevision:'elements-2',trials});setPhase('done');}};
 if(phase==='setup')return <section className="practice setup"><span className="eyebrow"><Brain size={16}/> REMEMBER THE ELEMENTS</span><h1>Rebuild the word<br/><em>from its story.</em></h1><p className="intro">Study the visible elements and their memory images, then fill in a missing element. Half the cards add a story so you can compare whether the connection helps.</p><div className="experiment-steps"><div><span>01</span><h3>Recognize</h3><p>Match each shape to a consistent image.</p></div><div><span>02</span><h3>Connect</h3><p>Picture the images acting together.</p></div><div><span>03</span><h3>Rebuild</h3><p>Recall the missing written element.</p></div></div><div className="setup-options"><label>Practice<select value={focus} onChange={e=>setFocus(e.target.value as Focus)}><option value="elements">Element recognition</option><option value="meaning">Word meanings</option></select></label><label>Word set<select value={scope} onChange={e=>setScope(e.target.value)}><option value="stress">43 tricky cases</option><option value="all">All 1,000 words</option></select></label><label>Session length<select value={size} onChange={e=>setSize(Number(e.target.value))}><option value={10}>10 words</option><option value={20}>20 words</option><option value={40}>40 words</option></select></label></div><button className="primary" onClick={start}>Start recall test <ArrowRight size={17}/></button><p className="fineprint">Invented memory stories, with no independent language review yet. This short test measures immediate recognition; it does not establish long-term retention.</p></section>;
 if(phase==='done'){const stats=summarize([{id:'current',date:'',trials}]);return <section className="practice finish"><CheckCircle2 size={38}/><span className="eyebrow">SESSION COMPLETE · {focus==='elements'?'ELEMENT RECOGNITION':'WORD MEANINGS'}</span><h1>You recalled<br/><em>{trials.filter(t=>t.correct).length} of {trials.length} answers.</em></h1><div className="result-pair">{stats.map(s=><div key={s.condition}><span className="micro">{s.condition==='story'?'WITH A STORY':'WITHOUT A STORY'}</span><strong>{s.correct} / {s.total}</strong><p>{Math.round(s.meanStudyMs/1000)}s average study time</p></div>)}</div><p className="intro">Compare the connections that helped. Word difficulty, prior knowledge and study time can affect these early results.</p><button className="primary" onClick={()=>setPhase('setup')}>Try another set <ArrowRight size={16}/></button><button className="text-button" onClick={onBack}>Return to the library</button></section>;}
 const item=phase==='study'?plan[index]:order[index],correct=expected(item);
 return <section className="practice trial"><div className="trial-meta"><span className="eyebrow">{phase==='study'?'STUDY':'RECALL'}</span><span>{index+1} / {plan.length}</span></div><div className="progress-line"><i style={{width:`${(index+1)/plan.length*100}%`}}/></div>{phase==='study'?<><div className="trial-word" lang="zh-Hans">{item.lesson.word}</div><div className="pinyin">{item.lesson.pinyin}</div><h2>{item.lesson.meaning}</h2><MemoryImages elements={item.lesson.memoryElements}/>{item.condition==='story'?<div className="study-story"><Sparkles size={18}/><p>{item.lesson.story}</p><span>Invented memory story</span></div>:<p className="study-baseline">Match the shapes to their images and remember the word's meaning.</p>}<button className="primary" onClick={nextStudy}>{index+1===plan.length?'Begin recall':'Next word'}<ArrowRight size={17}/></button></>:<>{focus==='elements'?<><h2 className="rebuild-meaning">{item.lesson.meaning}</h2><p className="question">{item.lesson.memoryElements.length===1?'Which character matches this meaning?':'Which written element is missing?'}</p><MemoryImages elements={item.lesson.memoryElements} missing={item.question.missing} hideLabels/></>:<><div className="trial-word" lang="zh-Hans">{item.lesson.word}</div><p className="question">Which meaning did you study?</p></>}<div className={`answer-options ${focus==='elements'?'element-answers':''}`}>{choices.map((c,i)=><button key={c} disabled={picked!==null} className={picked!==null?(c===correct?'correct':c===picked?'incorrect':''):''} onClick={()=>answer(c)}><span>{String.fromCharCode(65+i)}</span><b lang={focus==='elements'?'zh-Hans':undefined}>{c}</b>{picked!==null&&c===correct&&<Check size={18}/>}</button>)}</div>{picked!==null&&<div className="answer-feedback" role="status"><p>{picked===correct?'That’s right.':`The answer is ${correct}.`}{focus==='elements'&&` ${item.question.answer.glyph} → ${item.question.answer.image}`}</p><button className="primary" onClick={nextQuestion}>{index+1===order.length?'See results':'Next question'}<ArrowRight size={16}/></button></div>}</>}<button className="text-button exit-test" onClick={onBack}>Exit test · discard unfinished session</button></section>;
}
